### ISSUE TITLE
Ocarina of Time missing Items/Equipment

### ISSUE THREAD

**Issue by JMC47** [citra-emu/citra#1024]
For as long as I can test, the equipment and item screens on OoT won't actually display the items/equipment.  It will display how many of each you have, for things such as deku nuts, sticks, and bombs, but you can't actually see the item itself.

![missingootequipment](https://cloud.githubusercontent.com/assets/6598209/9103314/b4803756-3bca-11e5-92eb-c5cd458c0649.jpg)

It impacts playability unless you're very patient.  Happens on both hardware and software renderer.

**Comment by archshift** [comment]
Anything noteworthy in the game logs?

**Comment by tfarley** [comment]
I mentioned this briefly in #880. One place this issue touches is a shader RCP instruction performing a divide by a very small number. But as evidenced by #948 the RCP implementation probably isn't the root cause. Apparently that DP3 PR didn't fix this part of the issue, but there's probably a similar error elsewhere in the shader instruction handling.

**Comment by JMC47** [comment]
Logs don't say anything fun.
