### ISSUE TITLE
Kingdom Hearts 3D - Dream Drop Distance Crash When Entering In-Game

### ISSUE THREAD

**Issue by TheSoraHD** [citra-emu/citra#1093]
Happens just before doing the tutorial or fighting Ursula.
![image](https://cloud.githubusercontent.com/assets/8531824/9578341/3ca5fee0-4fe9-11e5-9ca0-f15bf2c3c7f2.png)

**Comment by yuriks** [comment]
This can probably be fixed by extracting the config save file from your 3DS, but there's no convenient way of doing this at the moment. (It requires a way to dump and decrypt the NAND and then use a Linux tool to unpack the save.)

I'm going to close this issue and open a different one tracking adding a tool to make dumping of this file more convenient (or if that's not possible, to HLE it in Citra, since there's several games which require doing this.)

**Comment by yuriks** [comment]
Try #1097

**Comment by TheSoraHD** [comment]
Works like a charm, now it's like 1-hour playable skipping cutscenes! ^_^

**Comment by HeroineChan** [comment]
Why it become like this? O.o
![untitled 3](https://cloud.githubusercontent.com/assets/16014270/11414259/4185a9b8-942e-11e5-901d-0e2b61f30110.png)
