### ISSUE TITLE
ScanDirectoryTree will infinitely recurse upon meeting a symlink to its parent directory.

### ISSUE THREAD

**Issue by archshift** [citra-emu/citra#1115]

**Comment by LittleWhite-tb** [comment]
Well, using a counter was a way to solve it, of course, but why not just checking if the file is a symlink, and in such case, we would ignore it ?
When I was reading code, I was completely wondering why "recursion" was an int and not a bool.

**Comment by JayFoxRox** [comment]
It used to be a boolean and was only recently changed. The PR / review phase had been there for a long time btw.
Also disabling symlinks is a really bad idea imho.

I also sometimes symlink some of my games as I don't have enough storage on my SSD to keep them all in one folder + I can manually sort them with symlinks  (and especially my hardware tests for use in a dropbox are symlinked).

However, it shouldn't be a GUI option either (Confusing to users). Having the option in the ini/config file is probably good though.

**Comment by LittleWhite-tb** [comment]
I was thinking about disabling the symlink. Even if it can be useful, since you can precise the input folder, the need of symlink is decreased. Otherwise, maybe it is possible to detect symlink recursion ?
By not letting the user define this value will cause two things :
* no advantages to have a counter, since there is high chance it is too high (no performance gain, we just avoid the infinite loop)
* if the counter is too low, users will report a bug
Of course, letting the user choose the value is very difficult for non technical users.

(Sorry to have missed the review phase ...)
