### ISSUE TITLE
Digimon World Re: Digitize Decode - Unable to boot both HW and SW

### ISSUE THREAD

**Issue by Kloen** [citra-emu/citra#1129]
This game it's most likely unable to boot.

On HW and SW, it only shows a dark, then white, and then dark again screen, and print these:
![image](https://cloud.githubusercontent.com/assets/9112818/9768846/a940d234-5726-11e5-9cf4-87d0e375c78a.png)

**Comment by mailwl** [comment]
i think its easy to cure

**Comment by Kloen** [comment]
Updated with the crash error on HW.

**Comment by Subv** [comment]
@yuriks, It appears to be some y2r problem?

**Comment by Kloen** [comment]
Update: The HW issue it's only on Intel cards, should check the drivers tomorrow, on my main PC the result it's the same as in the software render.

**Comment by Kloen** [comment]
Update: blindly implementing y2r:u 0x00040000 which if I'm right it's GetOutputFormat().
![image](https://cloud.githubusercontent.com/assets/9112818/9796493/bd4c40ee-57f6-11e5-9604-06d5bd36c221.png)

It seems that there are a problem with all the graphic resources of the game, using GLIntercept I found some resources that should had been printed on screen before.

**Comment by Kloen** [comment]
Managed to navigate throught menus idk how, both HW/SW (includes openl-tex-forwarding, will check without it once I reach home, cause HW render does not work on my Intel HD 4600 without that branch):
![image](https://cloud.githubusercontent.com/assets/9112818/10014374/1e92ccda-6119-11e5-85dd-a584d3cfa4a4.png)

**Comment by Romsstar** [comment]
Using the most recent Nightly Build and a custom build where I used GetFormatInfo from Subv's branch result in the same thing:
- Enabling the Hardware Renderer with the game will immediately make Citra crash.
As Kloen already reported this issue on Intel Cards, in my case an Intel HD 530.
- Even after #1097 the game still requires config saveblock data or it won't boot at all.
- The game font is not being rendered. Actually most graphics are being rendered just wrong, but
the font is not being rendered at all.
-When you try to load the savedata it crashes, unfortunately even with debugging on it failed to  provide a reason. 
I assume it has something to do with this part. I attached the debuglog.
[debuglog.txt](https://github.com/citra-emu/citra/files/150222/debuglog.txt)

"[ 107.490148] Service.FS <Debug> core\hle\service\fs\fs_user.cpp:Service::FS::GetFormatInfo:762: archive_path=[Empty]"

I attached the config_savedata and some test savegames so this issue can be investigated. Unfortunately I don't know how to pinpoint those issues.
[config_savedata.zip](https://github.com/citra-emu/citra/files/150221/config_savedata.zip)

![11](https://cloud.githubusercontent.com/assets/17484361/13383114/86e668f8-de84-11e5-87a0-4517f3fbcf76.PNG)
![crash2](https://cloud.githubusercontent.com/assets/17484361/13383125/c5320202-de84-11e5-8f34-df495193757f.PNG)

My team and I are planning to translate this game, and we need to be able to debug certain areas which turns out to be kinda difficult without seing the font ^^''

Sorry this is my first time posting so I don't know what else could help or provide any insight. Please bear with me. If there is anything else I can help to solve this issue please tell me.

**Comment by Romsstar** [comment]
I tried to debug this with renderdoc today, unfortunately it causes bluescreens on my machine. I really don't know why... But I tried and logged everything till the saveloading process with GLIntercept. While it probably is useless, I still will attach it to this post. 
[gliInterceptLog.txt](https://github.com/citra-emu/citra/files/151228/gliInterceptLog.txt)

**Comment by mailwl** [comment]
> Plans are in place to increase Renderdoc™'s functionality over time, adding support for other platforms and APIs such as OpenGL.

looks like it's for DX only

**Comment by Romsstar** [comment]
Oh, I'm sorry, I just went by yuriks advice to ran it through Renderdoc. 
I'll gladly try any alternative, but he guessed that it's a geometry shader issue and seing the glIntercept Log I'm inclined to believe it might be the case, but then again this is hardly my area of expertise, so I don't really know.

**Comment by yuriks** [comment]
RenderDoc *does* work for OpenGL (as well as DX and Vulkan).

You probably have some kind of driver issue if it's causing it to crash.

**Comment by Romsstar** [comment]
I tried with renderdoc again. This time both, Citra and Renderdoc gave me the errorcode:
```
API ERROR 1280: Error has been generated. GL  error GL_INVALID_OPERATION in <null>: <ID: 173538523> Generic error

```
It was the same errorcode in both, citra and renderdoc. I don't know if that really helps...

**Comment by Romsstar** [comment]
Just providing the newest screenshots. This is a newly started game, using config blockdata from #1433. The game requires also GetFormatInfo and GetInputFormat and GetOutputFormat. I used Subvs implementation and JamePeng's implementation of y2r from #1426. Unfortunately the game still requires dumped metadata because the metadata citra creates is fautlty. 

![newestscreen](https://cloud.githubusercontent.com/assets/17484361/13427295/5572f928-dfb3-11e5-8482-4d777bd8b7ed.PNG)

Current Build with 
![agumon](https://cloud.githubusercontent.com/assets/17484361/13427356/c84218c6-dfb3-11e5-9f07-44b0e0983ad1.PNG)

How it's supposed to look like (Well more or less)
![npjh50588_00001](https://cloud.githubusercontent.com/assets/17484361/13427370/e2979b74-dfb3-11e5-8929-509eb9cadaef.jpg)

**Comment by Kloen** [comment]
Well, in fact, I was able to run it only implementing **y2r::GetOutputFormat.**

I'll try to take another look on it on my AMD, cause on software it's slow... and I just face the same intel cards problem when trying out The legend of legacy.

**Comment by Romsstar** [comment]
On Software it's brutal :/ Damn I wish someone would fix the Intel issue, as I don't have the money to buy a new GPU right now. Kloen did you use a dumped savegame? With a dumped savegame I think GetOutputFormat works for me too. I was referring to loading the game without a savegame.

**Comment by Kloen** [comment]
I didn't use any savegame or anything. I just dumped and loaded the game on citra, without any other modification. Crash, then blindly implemented GetOutpurFormat, and just following a video of gameplay, I was able to go ingame.

About the Intel Cards problem, I wasn't able to track it... I only know that it occurs when somehow it reachs this line:
https://github.com/citra-emu/citra/blob/master/src/video_core/renderer_opengl/gl_rasterizer.cpp#L215

![image](https://cloud.githubusercontent.com/assets/9112818/13427998/dbdfc01e-dfb7-11e5-81f6-595b290df203.png)

@Romsstar  #1434 only fixes the boot on The legend of legacy, not the HW problem.. That's something related to the renderer_opengl that I wasn't able to find yet.

**Comment by Romsstar** [comment]
@Kloen: I just ran it again through GLintercept and  I came to the same result as you last time. Yeah I know, not really helping lol. Interestingly the images it doesn't display are loaded because I was able to find them in the Images Folder. Here are some samples. As you see there is the texture of Agumon and the splash screen at the beginnning which is also black only. Interestingly the images are mirrored and rotated 180. But I don't know if that's because GLIntercept does that or something else is going on. 

I attached some samples, maybe the nature of the images could help understand why they are not being loaded? Really don't know...

![image_2d_0007_2072](https://cloud.githubusercontent.com/assets/17484361/13432002/177574de-dfcc-11e5-9034-7b48076b7552.png)
![image_2d_0030_18956](https://cloud.githubusercontent.com/assets/17484361/13432005/1776995e-dfcc-11e5-8138-5e03f7b248b3.png)
![image_2d_0031_18957](https://cloud.githubusercontent.com/assets/17484361/13432004/1775f51c-dfcc-11e5-9097-ea8f1efe53b9.png)
![image_2d_0039_18965](https://cloud.githubusercontent.com/assets/17484361/13432003/177582b2-dfcc-11e5-9e34-b91837c7a50a.png)
![image_2d_0045_18971](https://cloud.githubusercontent.com/assets/17484361/13432001/17742282-dfcc-11e5-850d-5dfa179125c8.png)




aded and GlIntercept actually saved them.

**Comment by Kloen** [comment]
@Romsstar These are the resources that should have been printed on the screen, I found the same ones when I tested this game. 

The fact that they are rotated it's fine xD

The thing that we should try to understand it's why aren't those resources being printed on the screen. And I'm not expert enough on this topic, I'm just beginner with C++ and even more with OpenGL... so... We should dig further on citra to find the problem.

**Comment by Romsstar** [comment]
I just debugged the savedata loading issue:
"00007FF77E7F63EF in citra-qt.exe: 0xC0000005: Zugriffsverletzung beim Lesen an Position 0x000002293D8444B5" it's basically the same message as yours for the Intel HW issue, access violation when trying to read... Could you test the savedata I uploaded above in my post (config_savedata.zip)  see if it crashes when you try to load a savegame on your AMD GPU? If it doesn't it must be also related to the Intel Issue.

**Comment by Romsstar** [comment]
Update: Leaving new comment as the old one started to become cluttered. 

Attaching VS to it, I discovered, that during saveloading it breaks in rasterizer.cpp
at 

static u32 GetDepth(int x, int y) {

The problem seems to lie in the return of the src_pixel value.

**Comment by Romsstar** [comment]
#1436 resolves the HW Renderer issue on Intel Cards, HWRenderer enabled also resolves the Saveloading issue (But only on hardware, still crashes on Software). The rendering problems (font, etc) still persist.

**Comment by Romsstar** [comment]
Could anyone please confirm that the Circle Pad (not Pro!) is indeed not working here and that you can't move the character? I have to make sure it's no error on my end.

**Comment by yuriks** [comment]
Circle pad *should* work, but I know that there may be bugs. Input in some games seems to behave strangely for me.

**Comment by Romsstar** [comment]
Well I can report that it's definitely not working on this game.
Also new bugs/unimplemented functions discovered: The game breaks during the battle in the intro due to probably one (or all) following unimplemented functions. 

```
[  72.470114] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function 'SendCaptureBufferInfo': port=APT:U, cmd_buff[1]=0x20, cmd_buff[2]=0x80002, cmd_buff[3]=0x538784
[  72.470644] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function 'ReleaseRight': port=gsp::Gpu
[  72.471053] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function 'ReplySleepQuery': port=APT:U, cmd_buff[1]=0x300, cmd_buff[2]=0x66630000
[  65.747643] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function 'SaveVramSysArea': port=gsp::Gpu
[  72.479958] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function 'AcquireRight': port=gsp::Gpu, cmd_buff[1]=0x0, cmd_buff[2]=0x0, cmd_buff[3]=0xFFFF8001
[  72.480390] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function 'RestoreVramSysArea': port=gsp::Gpu
```

**Comment by Romsstar** [comment]
Update: #1462 actually fixed some of the graphic issues and at least we got now some menues displaying black boxes instead of nothing before. Still looks pretty bad and the controls still don't work. 

Also with that the game started displaying some new error messages which weren't in the log before. Here's the new log
![newestlog](https://cloud.githubusercontent.com/assets/17484361/13574478/8f9662c2-e484-11e5-8a4c-d3be6c3cfb6d.PNG)

**Comment by lioncash** [comment]
> [19:37] <JayFoxRox> https://github.com/citra-emu/citra/issues/1129 < close please bunnei or some other maintainer
> [19:37] <JayFoxRox> [fixed for some time, don't know exact revisions]
