### ISSUE TITLE
Implement Date/Time

### ISSUE THREAD

**Issue by filfat** [citra-emu/citra#1210]
It appears like time isn't yet implemented as you always get 2147482427718.

Can't see any reason why we would like to emulate the time instead of just passing along the time from the device running the emulator.

Cheers :)

**Comment by luziferius** [comment]
Passing time from the host device is usually a good idea in normal virtualized environments, as it keeps clocks sync, but not for a console emulator.
Whenever the emulator is not running at 100% speed , passing time from the host will cause severe issues with emulated games. If the emulator runs at 33% speed, all ingame clocks will run at 3x speed (realtime) instead of the emulated 33% speed.

**Comment by yuriks** [comment]
@luziferius This clock only has second resolution (and is only updated every few seconds, iirc), and it mostly used for things like night/day effects or save file timestamps. It's not used for game timing.

**Comment by Subv** [comment]
Some games (like Quell Reflect) seem to hang because of this

**Comment by MerryMage** [comment]
related to #1641

**Comment by poutros** [comment]
Hasn't it been added in https://github.com/citra-emu/citra/pull/1963.
