### ISSUE TITLE
CMakeLists: Compile as C++14 on non-windows target

### ISSUE THREAD

**Issue by bunnei** [citra-emu/citra#1245]
#1175 was closed due to some mainstream Linux distros still shipping with GCC 4.8, which does not support all of the proposed features. This issue is to serve as a reminder to revisit this PR in 6 months (or so) once C++14 functionality is more widely accessible.

**Comment by Subv** [comment]
It's been exactly a year since this issue was opened, what's the status of this?

**Comment by Subv** [comment]
It seems [many distributions](http://distrowatch.com/search.php?pkg=gcc&relation=less&pkgver=4.9&distrorange=InLatest#pkgsearch) still ship with GCC < 4.9, this is very sad.

**Comment by freiro** [comment]
@Subv We should also check which distributions [provide GCC5](http://distrowatch.com/search.php?pkg=gcc&relation=greaterequal&pkgver=5&distrorange=InAny#pkgsearch).
Only CentOS is a concern but according to [this](http://distrowatch.com/search.php?pkg=gcc&relation=less&pkgver=5&distrorange=InLatest#pkgsearch) it's possible to install it.

**Comment by mikakev1** [comment]
IMHO, Centos isn't the distribution one may choose for it's graphical capabilities, it's more related to enterprise's stuff, plus it's quite outdated because stability is the goal. I can't imagine people trying to bring everything that's needed to build and *USE* citra into it. 
You should only concern with recent distribution where GCC is at  v5+ and MESAGL v11.1+, or you may end up being flooded by issues regarding MESAGL's stack.

**Comment by jroweboy** [comment]
Fun fact, citra's been cpp 14 on all systems since this commit https://github.com/citra-emu/citra/commit/a976c2e3ba146df2fda9293c6fce9e11d96ac038 on Jun 30 so this doesn't seem to be a real issue anymore
