### ISSUE TITLE
citra hangs when Gdbstub is enabled

### ISSUE THREAD

**Issue by RavenHome1** [citra-emu/citra#1249]
the emulator just freezes and nothing happens, also a newbie question but what is a Gdbstub and does it even have any effect on games?

![captureddcdcd](https://cloud.githubusercontent.com/assets/12820322/11326400/707ac0b0-9171-11e5-9821-b76544517e5a.PNG)

**Comment by Subv** [comment]
That is by design, it is waiting for a debugger to connect.

**Comment by RavenHome1** [comment]
@Subv can you please provide more info on what a Gdbstub is?

**Comment by jroweboy** [comment]
@RavenHome1 Gdb is a process debugger and a gdb stub is the code in citra that enables you to connect gdb (the debugger) to citra and instead of debugging citra, you can debug the game citra is emulating instead. 

On an unrelated note, there maybe be a better way to inform the users that enabling the gdb stub is a bad idea and will actually slow down the emulator. But thats not a high priority I bet :)

**Comment by RavenHome1** [comment]
@jroweboy thank you for clearing that out, i strongly suggest adding some warning method or most of the time people will end up spamming issue tracker about it, thinking it is not functional

**Comment by mailwl** [comment]
how to connect Citra to Ida pro?
