### ISSUE TITLE
citra.exe Application Error (0xc000007b) (WINDOWS 10)

### ISSUE THREAD

**Issue by ROXTheDragonSlayer10** [citra-emu/citra#1366]
Can Someone Explain?
i was trying to open Citra (in---> Windows 10)
And then "Poof!"
"The Application was unable to start Corectly (0xc000007b).Click OK to Close The 
Application."
Ugh man,What do i do?
i changing Dll file in system32 and sysWOW64,its not worked
Can Someone Tell me?

**Comment by yuriks** [comment]
https://github.com/citra-emu/citra/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by LittleWhite-tb** [comment]
As an advice : you should never change the DLL placed in system32/sysWOW64 folder.
This error often appears when a 64 bits application is linked with 32 bits DLL, or something related to a mismatch between 64 bits/32 bits.
But, at this point, since you are touching the system folder and configuration, there is no way to find quickly a solution. But, you can try : Dependency Walker.

**Comment by Aryan10** [comment]
I am getting same error and I not touched anything...

**Comment by MerryMage** [comment]
https://citra-emu.org/wiki/faq/
