### ISSUE TITLE
Bravely Default has extremely fast key repeat

### ISSUE THREAD

**Issue by yuriks** [citra-emu/citra#1408]
For some reason, menus in Bravely Default have very fast key repeat. The game seems to move the cursor or accept menus on every frame while a button is held down. This makes navigating the game menus quite hard.

**Comment by wwylele** [comment]
Copied from #1507, seems related:
## Pokemon Picross input issue

The issue happens when you choose control method to be "Stylus".
### On real console
During the game, you can use D-Pad or Circle Pad to switch between two pattern (solid or "x") to be drawn. That's saying:
 - when you press and hold "Up" on D-Pad, or push up Circle Pad and hold it, you are in "drawing" state and you can fill in grids on the board with stylus
 - when you press and hold "Down" on D-Pad, or push down Circle Pad and hold it, you are in "cross out" state and you can put "x" in the grids. 
 - if you release D-Pad or Circle Pad, you are now in "idle" state, and you can draw nothing with stylus. 

![pic](https://cloud.githubusercontent.com/assets/4592895/13725742/3f17522e-e8b3-11e5-893a-e4ca5c7e52b3.PNG)

An icon is shown at the left up corner of the bottom screen, indicating which state you are in. For example, if you are in "drawing state", the upper red icon will be shining.

### On Citra
Both D-Pad and Circle Pad seem broken. When you push up Circle Pad and hold it, the game responses as if you are not holding it, but pushing it up and releasing it in a high frequency. You can see the icon is not shining normally, but continuously switching between "filling" state and "idle" state. At the same time you can hardly draw anything with stylus (mouse). Similar thing happens to D-Pad.


[Log](http://pastebin.com/xaVfnuiy)

**Comment by TheSoraHD** [comment]
I think #1185 is also related.

**Comment by wwylele** [comment]
Is this fixed by #1510 ?

**Comment by archshift** [comment]
Yes!
