### ISSUE TITLE
romfsInit() makes emulator crash

### ISSUE THREAD

**Issue by Rinnegatamante** [citra-emu/citra#1412]
I tried a 3dsx which should initialize romFs but at startup it just crashes the whole emulator.

The code is this: https://github.com/Rinnegatamante/lpp-3ds/blob/master/source/main.cpp#L59-L166

It won't even reach the "Start Interpreter" part for sure.

I also tried the same executable with a very old version of Citra i have on my PC (executables data is 03/05/2015) and with this version it loads fine.

That's the crash screenshot, don't know if there is also some log file, if so, please tell me where i can found them and i'll attach them to this issue.

http://rinnegatamante.it/crash.png

I'm sure the problem is with romfsInit cause commenting it "solved" the problem.

**Comment by sant0ro** [comment]
Maybe as i can see in Programming Paradigms. Some Interfaces wasn't Implemented. So blank Models can't simply Run. As a Interface is only like a Class that tell what need to be implementated and followed in a Model.

In this case, as i can see some functions of the Interface wasn't implementated.
Maybe the Emulator tried to start some Model implemented by the Interface, but after that tried to switch to a different Model that doesn't have these methods.

Or simply they are not implemented.
"ConfigureNew3DS", "CheckNew3DS", "Initialize", "AcquireRight" And again "Initiliaze".

Initialize methods (in C# as far i know) are used for Static Classes that doesn't have other instances. 

Or used in Factories (as a Singleton) that clones the Interface filling with a Closure.

Remembering, this Emulator is under Development.
I'm not collaborator of this Repo, but i can see a whole community trying to use to production usages, but the Emulator isn't ready for that.

Good luck!.

**Comment by Rinnegatamante** [comment]
Don't know what you mean about production usages. (If you mean running commercial games (?), then what i want to execute is an homebrew (which also worked fine on an older version))
Also the unrecognized functions just doesn't crash the emulator usually but just got "skipped" leaving the emulation still good.

**Comment by sant0ro** [comment]
Nope, in Software Design Patterns the following:

1. Release Versions: Version ready for public Usage
2. Production Versions: Version ready for massive usage and stress
3. Development Versions: Version not-read for public, available for public, but under development. That mean that isn't nice reporting bugs of features that aren't coded. Or bugs that happens starting ROM's (in this special case) since the Collaborators said that Citra is actually an "Experimental Nintendo 3DS Emulator"
3.1. Ve Have also Versioning Tags, Main Tag Label in Development can be:
beta, alpha, omega, charlie, etc.
3.2. When the Software is in a "Safe-Thread or Simple Safe Build" means that are compatible for each x86/64 Platforms (or not) but is ready for usage without Memory Leaks or Performance Problems, the "Non-Safe" are the oposit.
3.3. Experimental Softwares, like Citra, is good to be used for Testing, so please don't be sad if you game save is losed or game crashes in some moment. They will not do Specific Support for In-Game Bugs. Since this is an Open Source Project. Github Issues are used for Features Bugs, Code Bugs/Issues, Proposal's, Etc.

Answering your question, is really weird that Happens. Since i don't know how this Emulator is made, that means maybe something Crashed Internally.

Nintendo 3DS Files, uses a different Ciphered Algorithm, not the usally Nintedo DS Algorithm.
The most hardest thing, is not the Obfuscation, but 3DS, and NDS Files are "Executables" for Nintendo Respectively Environments, so aren't Files with Readable Source Code.

I can give a Example de Microsoft's .NET Framework, were each Language like C#, and C++ after Compiling by MSBUILD are passed by an Interpreter called IL Assembler. 
.NET Softwares (all .NET languages) on build, are translated to IL Codes, and after that to Binaries.
Every .NET Framework also Includes an IL Disassembler, the Software that make able to the System.Reflection works. Because that we can see the Common .NET Disassemblers. Microsoft gave a tool to Decompile every Software made in .NET

Differently Nintendo didn't gave that. Since if Nintendo gives their Framework Tools for Public, is really more easiest to Decompile.

Also is hard the Multiplatform Interoperability. 3DS and NDS Files are made for Nintendo DS OS Environment. So Citra need to Respectively Convert each Packet and Their Data to Valid (Windows, OS X, Linux) Graphical Data, since OpenGL is a Framework and Library ready for Any of Most Used Operational Systems, is easy do for OpenGL. 

I Recommend this Project use OpenGL 2.X, since 3.X aren't compatible with PC's before 2012.

Also we have other problem, Make The Emulator Understand the Nintendo Key Scheme and Convert to UPNP (USB-X) Plug And Play Devices. That means the Emulator need understand Every Keyboard, Operational System already give this to us, and Convert to Understandable Nintendo Packets.

Citra like other Emulators has in-built a Client/Server Environment, The Server Handles the ROM and the Client is the Display Graphic.

We can give an example as Ragnarok, We Have UI Client that you Download and the Server. Chronos and eAthena Are also Emulators that NEED understand the Ragnarok Client Packets.

Citra is the Server that need Understand the .3DS Packets.

The most hardest aren't the graphics, but the Third-Party Devices since:
1. Convert Mouse or Touchpad or Touchscreen to 3DS Actions (OS give the Drives to this Devices, only need convert to Valid Client Data)
2. Microphone
3. Sound
4. FX
5. 3D Data (will be really hard that)
6. Wireless
7. Battery Status (ACPI Devices from Nintendo 3DS)

I know this answer is big, but is a scenario to each non-developer using Citra read.
Since this is really IMPORTANT, to a good aknowledge and protected the Repository for massive Spammed Issues.

Cheers!

**Comment by Rinnegatamante** [comment]
Problems that  appears starting ROMs? I don't want to sound rude but what the hell are you saying?
You're just writing answers with no info related to the issue making the issue tedious to read to whatever dev wants to carry about the problem.

Also i'm not starting a ROM (even if you said i've done so) but an homebrew (So something i developed and i want to DEBUG with this emulator to avoid to lose time ejecting SD every time i have to test it on real hardware).

And also the same HOMEBREW (not ROM) runned fine on an old version of the emulator. (And this is only the 3rd time i say so.)

At least read what someone says before starting shooting sentences.

**Comment by sant0ro** [comment]
Idk why you want to RUN Homebrew.

Isn't tedious since i'm explaining everything, and lot a few lines.

Idk if some collaborator will answer you, since that isn't a Citra issue, but a personal issue.

You was rude, saying what the hell i'm saying, since you want only the instructions to solve your problem, and not know the entire "map" of what is happening in this repo.

Homebrew is a ROM. Since need be Understanded by Nintendo Envrionment (i can be wrong also).

That's my last answer in this issue, good luck.

**Comment by mailwl** [comment]
Homebrew is NOT ROM
@Rinnegatamante , did you try NTR Debugger? AFFAIK, you don't need eject SD every time

**Comment by Rinnegatamante** [comment]
I usually use a real hardware personally but some Lua Player Plus users reported me about this problem and since they like to use Citra3DS as debugging tool, i want to help them. For the moment i added a new pre-processor instruction to disable romFs initialization but it's not a really good "patch".

NTR Debugger also is usable only on a console with fw <= 9.2 (10.3 if we consider the possibility to downgrade).

**Comment by neobrain** [comment]
@sant0ro Can't tell if you're an actual person or a Markov Chain bot, but if it's the former please find a more concise way of summarizing information and restrict it to what's relevant to this issue. Also, please refrain from questioning people's motifs here, since that's not relevant to the issue topic.

**Comment by Cruel** [comment]
Are you using latest ctrulib?

And does the same thing happen when running the [romfs example](https://github.com/devkitPro/3ds-examples/tree/master/romfs)?

**Comment by Rinnegatamante** [comment]
I'm using latest ctrulib and it seems it doesn't happen for the romFs example (But executing it still seems to produce something weird since i get a 0x0000000A error from romfsInit().

**Comment by Subv** [comment]
Is this still an issue? You didn't provide a .3dsx file to test.

**Comment by yuriks** [comment]
Likely the same as #1862, but that one has a testcase.

**Comment by wwylele** [comment]
Fixed by #2561
