### ISSUE TITLE
 The Legend of Korra: A New Era Begins - Broken characters in 3D scenes

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1530]
Tested on latest master https://github.com/citra-emu/citra/commit/9a627aa30b16542eb64115a83dc075055dbabaf4
### 3DS

![korra3ds 1](https://cloud.githubusercontent.com/assets/11453507/13785329/770790b4-ead3-11e5-87de-a833e210e05b.JPG)
### Citra

![korra 1](https://cloud.githubusercontent.com/assets/11453507/13785344/8257deb0-ead3-11e5-99ec-85974ada10bc.JPG)

![korra 2](https://cloud.githubusercontent.com/assets/11453507/13785364/8ff176b2-ead3-11e5-90f8-0bf0fbad33b1.JPG)

REFERENCE VIDEO [HERE](https://www.youtube.com/watch?v=9MXz5QeXK8w)

**Comment by JayFoxRox** [comment]
The characters are drawn fine first (confirmed using GPU debugger) and then they are partially obscured by a black model which is probably supposed to be the outline instead.

This is probably z-fighting. It might also be winding related but I haven't checked that.
Can probably be fixed with better depth implementation.

**Comment by newretro** [comment]
**Return to popolocrois a story of seasons fairytale** has the same bug

![01](https://cloud.githubusercontent.com/assets/17784684/13811041/320e4820-eb84-11e5-893e-117083ce3d49.jpg)

**Comment by JayFoxRox** [comment]
@newretro Could you open a seperate issue for that (and remove the post above)? It might look like the same bug but you never know until it's further researched / fixed. You can still reference this issue as an assumption in the new issue.
Title should be "[Game name] - [Whats do you observe]" (probably very similar to this issue, though, I'd prefer "[Game name] - 3D characters partially black" as observation for this). Assumptions go into the body of the issue, not the title. Also please include a reference screenshot from a real 3DS.

**Comment by Punk34** [comment]
It looks like cel-shading emulation problem.

![mommvki](https://cloud.githubusercontent.com/assets/13983158/13812405/0390c528-eb8d-11e5-80dd-20503d1872b0.jpg)

**Comment by JayFoxRox** [comment]
Geometry Shaders, using DMP_silhouette.
"Legend Of Korra" fixed in https://github.com/JayFoxRox/citra/tree/gs-debugger (needs cleanup)

"Return of PopoloCrois" also fixed in same branch.
However, it still had different problems (because of uniforms or something, same shader though):

**THIS IS NOT THE SAME ISSUE.**

@newretro  @Punk34  Reminder:

**DON'T POST DIFFERENT GAMES IN THE SAME ISSUE EVEN IF THE PROBLEM LOOKS SIMILAR.**

**Comment by wwylele** [comment]
Is this fixed?

**Comment by JohnGodgames** [comment]
Yep

![korra](https://user-images.githubusercontent.com/11453507/30372595-a396e1ca-987e-11e7-9e13-107ad1ffd109.PNG)
