### ISSUE TITLE
Add option to to rotate the screens for book-style games

### ISSUE THREAD

**Issue by internetakias** [citra-emu/citra#1534]
Like the DS, some games on the 3DS (New Love Plus and New Love Plus + are the only examples I can think of right now) have you hold the 3DS on its side like a book, so an option to emulate that should probably be added for those kinds of games.

**Comment by yuriks** [comment]
Should probably be done together with options to show only the top screen, etc.

**Comment by i30817** [comment]
I've always wanted a option to resize only the smaller screen and put it over the larger in desmume too.

It would be nice when it's actually useful and you don't have two monitors...

Also (obviously) sending the images to two different screens if available would be good.

**Comment by internetakias** [comment]
![2016-05-20_00-50-29](https://cloud.githubusercontent.com/assets/5077063/15418326/08c2ef78-1e67-11e6-9f07-c221d96263d9.png)
Example

**Comment by jroweboy** [comment]
@internetakias This is part of something that I'm working on. I'm thinking will be step three after the rest of PRs are worked out. The first one is here #1753 to add new screen layouts. I'm working right now on another PR to support multiple windows, one for each screen. Then I plan on working to make everything screen related completely configurable. There is a decent amount of discussion on the matter, but I want to take things one step at a time. The ability to rotate the screens will probably be a part of that third one, since it will require some work to reflow screen layouts based on rotation as well. Right now, adding a new layout is a decent chunk of code and some math (for example https://github.com/citra-emu/citra/pull/1753/files#diff-17283da885c9e1c0923030e5d141b69fR86), and adding in rotations to this would just complicate it even more. Thats why I'm planning on doing that part later, so I get some time to think about how to integrate it the best way possible :) Of course, if anyone else feels like adding support, you are more than welcome to!

**Comment by datvm** [comment]
Hi, can we have an update on it? Really hope there is option for this, especially for Giant combat on Mario & Luigi series (Dream Team and Bowser Inside Story + Bowser Jr.). It's playable without rotating, just a bit hard.

![Untitled](https://user-images.githubusercontent.com/6388546/54829234-8a6c7c80-4ce8-11e9-9836-194e2d042a1e.png)

Here is a save file right before a giant battle if you need it for testing (Mario and Luigi: Bowser's Inside Story + Bowser Jr.):

[001d1400.zip](https://github.com/citra-emu/citra/files/2996884/001d1400.zip)

**Comment by doyzi2** [comment]
I am interested too.

**Comment by korkies22** [comment]
Any updates?

**Comment by Henrai** [comment]
Are we still working it? Can I have a try?
