### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mandiahg** [citra-emu/citra#1548]
Hello guys recently i downloaded this ''Cintra'' and im having a bugg wich i tried everything i could download mic.net framenetwork directx etc.. and im keeping  having this annoying spam Error (0xc000007b) Please i need help so i can use this app ... thank's 
![screenshot_1](https://cloud.githubusercontent.com/assets/17962130/13904109/d3c891a2-ee95-11e5-81b1-171f5a13024a.png)

**Comment by smartkaartik** [comment]
When I try to start any game, Citra immediately crashes!

It is very likely that this issue is caused by your GPU or drivers not supporting OpenGL 3.3. Try updating to the latest drivers if possible, and verify that either your driver control panel or a tool like GPU Caps Viewer reports that you can use at least OpenGL 3.3. If updating drivers doesn't help, you'll need to upgrade your GPU or wait until we remove this limitation from the software renderer. (The hardware renderer will never support lower OpenGL versions.)

**Comment by j-selby** [comment]
Which version of Windows are you running? That error is likely caused by a 32-bit platform, which Citra does not support nor target.

**Comment by yuriks** [comment]
Yes, this error is caused by not having a 64-bit windows.

@mandiahg Please use the forums instead for user support.

@smartkaartik Don't post unrelated problems in other issues.
