### ISSUE TITLE
Fantasy Life - Failed to detect SD card

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1607]
![fantasy](https://cloud.githubusercontent.com/assets/11453507/14078954/356163c0-f4fa-11e5-901b-96b8780ab30d.JPG)

[LOG](http://pasted.co/4254db47)

**Comment by JayFoxRox** [comment]
Stuff from the Log:
0x100D0084 (GetDemoDataTitleInfos) not implemented / stubbed.
Also: OpenLinkFile, ListDataTitleTicketInfos, GetDataTitleInfos, GetNumContentInfos pop up in the log.
Also: `[  56.061729] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::OpenArchive:389: failed to get a handle for archive archive_id=0x0000000A archive_path=[Empty]`

**Comment by mailwl** [comment]
no, this error because SDMCWriteOnly archive not implemented.

Here, https://github.com/mailwl/citra/tree/sdmcwo
i reuse SDMC as SDMCWriteOnly, and game pass this error

**Comment by majinkakashi** [comment]
I suddenly had this problem also, I don't understand how to fix as you are saying. I'm not using an emulator. 
this happened on my 3ds in which I downloaded the full version of fantasy life from the eshop. 
I didnt turn off during loading or saving or anything. it just showed this screen when I tried to start the game after I played the game last night.
I tried to repair but it still isn't working. I have like 18 hours on the game so far... I'm going to be pissed off if I have to delete the game and restart. but as I said the repair didn't work so wtf.. I wonder if this will even make the game playable or will it happen again. I doubt my sd card is going bad, its brand new and
there hasn't been any other issue with games or save files on my 3ds or sd card. I removed it and reinserted it. it says there is no save file to back up when I tried that,i wish I would've before though...
any help or thoughts on this would be greatly appreciated. I just don't want to resort to deleting the software on the card and redownloading until the last resort. especially since I'm positive that will erase the save file if its still there and it definitely wont be recoverable :'(

**Comment by majinkakashi** [comment]
its just that I searched bing to try to troubleshoot this error when I saw the exact same error msg and screen. that's how I landed here.

**Comment by marcus565** [comment]
how do that ?

**Comment by Blankface345** [comment]
could you give a clear and defined explanation of how to fix this problem so that we may all be able to play this game?

**Comment by JayFoxRox** [comment]
(Reminder that this is not a forum. Useless questions deleted)
