### ISSUE TITLE
Generator Rex: Agent of Providence - Asserts at title screen

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1646]
![gener rex](https://cloud.githubusercontent.com/assets/11453507/14334321/e44c5f7e-fc53-11e5-8bcf-c0f54a094e71.JPG)

`[  86.995282] Debug <Critical> core\hw\y2r.cpp:HW::Y2R::PerformConversion::<lambda_47404b557f89d61b34df81a6e7ce6e72>::operator ():264: Assertion Failed!`

[LOG](http://pastebin.com/xa7r4AHD)

**Comment by JamePeng** [comment]
![qq 20160408123344](https://cloud.githubusercontent.com/assets/17095606/14374232/14f9d0b0-fd86-11e5-8c87-810cc95a8a89.png)
![qq 20160408123656](https://cloud.githubusercontent.com/assets/17095606/14374269/87847c34-fd86-11e5-8a2a-382d61b8f0f6.png)

The assertion failed was caused when the num_tiles was 128!
Otherwise the max_tiles is 1024/8==128, and the num_tile still in the valid range!

@JohnGodgames could you try to correct the judgement of this sentence and check it!
`ASSERT(num_tiles <= MAX_TILES);`
![qq 20160408124700](https://cloud.githubusercontent.com/assets/17095606/14374397/eda85c64-fd87-11e5-9f43-b11b25d6194f.png)
