### ISSUE TITLE
Games, which stop working on starting new game

### ISSUE THREAD

**Issue by mailwl** [citra-emu/citra#1712]
This issue for all games, which just show black screen after selecting New Game.
the reason - find the easiest game, which helps to locate the problem.

i don't want to post in in discuss of official Citra site, because of it for users, not developers

let's start with games, which doesn't help
All Nintendo animal games
Bravely Default/Second
Dragon Quest 7

i found a game. which demonstrates black screen almost at start - Medarot Girls Mission
need to find method to find the reason, why games hangs at start

**Comment by mailwl** [comment]
add the games with this problem.

I remember Yokai Watch. But AAA games hard to explore, need some indie games

**Comment by JayFoxRox** [comment]
I'm against these meta issues because they make it hard to find problems for new users (instead of just searching for their game they have to read a large amount of issues).
Most of these issues are also listed in the compatibility list.
I think it's a better idea to create one game per issue (as problems could always be different even with the same symptoms), we could theoreticly discuss meta issues but I'm not sure if github is the proper place for meta-issues either (you can still reference one of the issues and mention that symptoms are similar).

**Comment by mailwl** [comment]
i am not ageed! problem is not in used game engine, but on all system not realized thing.
now i am trying to realize IR/CirclePad Pro connection, and just signal needed event not enough. need to fill some data in shared memory, otherwize a game just close connection.
I mean, need to set one digit in rigth way, and voila - hundred game compatibility added.
but on some games (especially Nintendo animals) is hard to find, what the really game want, but on another, maybe indie, easier.
Anyway, it's just my guess, but i want to check it

**Comment by mailwl** [comment]
add here #1703

**Comment by lioncash** [comment]
FWIW I kind of agree with @JayFoxRox on this, having an issue that acts as a 'repository' for busted things isn't particularly a good idea, the reason of which Jay already pointed out (the underlying issues for a game not booting may not always be the same).

Whether or not a single change fixes multiple games is irrelevant, the issues can just be closed once they're fixed. It's essentially being lazy for the sake of not wanting to open the issues individually. Jay's argument where it's a pain to search issues is still valid as well. For example, if a dev stumbles on an issue, they'll likely check the issue list for that game to see if the undesirable behavior already has an issue created for it. Having to sift through a list of things to see if it actually reports the behavior they encountered, rather than having an entry pop up with an adequate title, will be annoying.

**Comment by mailwl** [comment]
it **may** look ridiculous, but i pretty sure i am right.
need to find place, where and why games stucks, and stuck reasons really similar

**Comment by lioncash** [comment]
I think you're missing the point of what I said (and your reply doesn't even acknowledge them).

**Comment by mailwl** [comment]
Citra has huge compatibility with roms, but after starting new game show just black screen. it's no good

**Comment by lioncash** [comment]
That's not particularly relevant with what I stated.

**Comment by JayFoxRox** [comment]
@mailwl: please create one issue per problem per game. We like you as a contributor but one issue per game makes it easier for others to see known problems. Even if each issue / game HAS the same problem I'll happily close all related issues once the bug is fixed.

You can then keep your own personal list of issues with that bug OR use the [github search with specific filters](https://github.com/citra-emu/citra/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+black+screen) OR [use pcmakers list to find specific games](http://tinyurl.com/citra-updated-compat) (which is filter-friendly: create a copy and then filter it).

If you discuss this with others it might be an option to create an issue like this ("meta-issue") and link to the other issues with the same problem. (I'll happily remove all posts in this issue so you can have a fresh start or close this one and start a fresh one)

I'd prefer discussing this elsewhere (via IRC?) if possible, to rescue this issue from becoming a worthless discussion.

**Comment by mailwl** [comment]
i am so sorry for my pure english, nowhere use it in Russia, thus i talk so odd

**Comment by mailwl** [comment]
@JayFoxRox i dont want to create hundred useless issues for black screen games, when i know all the games does not work for one reason (unknown so far)

**Comment by JayFoxRox** [comment]
Just go ahead and create one issue per game - they won't be useless. It will be easier for users who will only look for their specific game.
We had cases in the past where one issue was used for many games with the same symptoms and it turned out to be a different problem. Then we were unable to close those issues because they were only half-resolved. Even if it is the same problem it's no problem for us maintainers to close all issues seperately.
Thanks.

**Comment by mailwl** [comment]
did it for #1716

**Comment by mailwl** [comment]
looks like many games will work with MerryMage audio branch, so useless issue.
