### ISSUE TITLE
Dead or Alive Dimensions - Missing ground textures at HW Renderer

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1738]
It's dupe of https://github.com/citra-emu/citra/issues/1593 and crash at sw renderer too (ingame)

**HW:**
![dead or alive dim 1](https://cloud.githubusercontent.com/assets/11453507/14935301/84b63e50-0ecc-11e6-9882-875772590ab7.JPG)

![dead or alive dim 2](https://cloud.githubusercontent.com/assets/11453507/14935305/8c0ce1ae-0ecc-11e6-8c2a-4918845ff575.JPG)

**SW (menu):**
![dead or alive dim 3](https://cloud.githubusercontent.com/assets/11453507/14935307/9767ff16-0ecc-11e6-85ea-cd3f0f619e94.JPG)

**Comment by JayFoxRox** [comment]
The blackness are actually where shadows would be. I've taken [a couple of screenshots to show the issue](http://imgur.com/a/ZqjQ9) (I've hidden a shadow buffer in each images, enjoy finding them).

![Example then](http://i.imgur.com/ovPMD5G.png)

#1621 fixes broken depth clipping, #1690 fixes shadow positions.

[Now it looks like this](http://imgur.com/a/towYK):

![Example now](http://i.imgur.com/PIfc6Ra.png)

Problems remaining:

* The software rasterizer crashes because of texturs being 0x0 pixels. I'm not sure where this comes from yet.
* Regions not covered by the shadow buffer somehow seem to read back as 100% covered in shadow which is obviously wrong

I also suspect this is an "extension" to the #1593 bug (which already had proper shadow positions). I'll try to investigate that later, but I have plenty other issues to care about first

---

I won't assign this to myself yet because I have too many open PRs, but I'll still take a look at this later probably

**Comment by JayFoxRox** [comment]
Can be closed once #1740 and #1690 are merged.

#1621 is only a bonus and fixes other problems (not the "missing ground" though).
We'll need a new issue about this crashing in SW Rast which seems somewhat more serious to me.
