### ISSUE TITLE
Citra-qt : Failed to initialize Video Core!

### ISSUE THREAD

**Issue by roxxageek** [citra-emu/citra#1746]
When I try to launch as an administrator "Citra-qt.exe", I launch the Pokemon X rom, then a message box appears where there is "Failed to initialize video core ! Please ensure that your GPU support OpenGL 3.3 and that you have the latest graphics drivers" 
![image](https://cloud.githubusercontent.com/assets/18947767/14942902/475d391e-0fcb-11e6-8b89-673b4c9750bd.png)

**Comment by JayFoxRox** [comment]
In case you have OpenGL 3.3 installed: more details.
In case you don't have OpenGL 3.3 installed: Try updating your drivers, if you don't have a OpenGL 3.3 capable GPU you are out of luck.

**Comment by roxxageek** [comment]
How can I know if I have OpenGl 3.3 ?

**Comment by JayFoxRox** [comment]
Please ask for support at https://discuss.citra-emu.org/ instead.
Try installing the latest graphics drivers for your PC (which depends on the GPU model - most likely intel, nvidia or amd/ati) and check the readme of the driver. It's not a citra related problem.

I'll close this because it's not an actual issue which we can fix in Citra.
