### ISSUE TITLE
MH Diary doesn't ouput to higher resolution

### ISSUE THREAD

**Issue by mhvuze** [citra-emu/citra#1779]
Seems like "MonHun Diary DX" (title id 0004000000166E00) doesn't take advantage of texture forwarding or the higher resolution capabilities to be more precise.

![1ul23t9](https://cloud.githubusercontent.com/assets/4907001/15179661/8732bb54-177d-11e6-8a33-603f5e7d57f5.jpg)

**Comment by JayFoxRox** [comment]
Do you have scaled resolution turned on and use hardware rendering?

If so it's likely that the game renders to an internal buffer for post-effects. However: These are also scaled already.
\- If the game looks bad it's because it looks even worse on smaller resolutions probably.
This could theoreticly be a bug (where tex-forwarding isn't aware of the existing surface) but I doubt it for now.
@tfarley ?

**Comment by mhvuze** [comment]
Yes, both Scaled Resolution and Hardware Rendering are turned on.
HW on, Scaled Resolution off: http://i.imgur.com/iY1ODDw.jpg
HW on, Scaled Resolution on: http://i.imgur.com/Bk7sBM9.jpg

I'd say both look rather similar.

**Comment by JohnGodgames** [comment]
I mentined more games on irc channel earlier too.
- Fire Emblem games
- Final Fantasy Explorers (only half of screen is  scaled)
- Luigi's Mansion: Dark Moon

**Comment by Dragios** [comment]
Is this fixed?

**Comment by Dragios** [comment]
Again is this still an issue now?

**Comment by Bearborg** [comment]
Looks like it's fixed to me. 
![image](https://user-images.githubusercontent.com/3048890/80127881-f0b67500-8562-11ea-80ed-780791b5cba7.png)
