### ISSUE TITLE
When loading up a game, it dosnt load and "read:181 unmapped read8 @ 0x100000011" gets spammed in the console

### ISSUE THREAD

**Issue by BmanGames** [citra-emu/citra#1791]
Title says it all.

**Comment by JayFoxRox** [comment]
Closed as invalid because there is not enough information.
Please provide more details:
- Which game
- When does it happen
- Post a full log
- Does the game hang / freeze? does the screen stay black?
- What PC did you use?
...

Memory read/write errors are common, it's more important to figure out how serious they are and what they imply.

**Comment by KillzXGaming** [comment]
Dupe of mine #1790 anyways
