### ISSUE TITLE
Citra Crash when loaded rom

### ISSUE THREAD

**Issue by Razeram** [citra-emu/citra#1793]
I Loaded citra with a decrypted rom but it crash immediately
Problem Event Name:	APPCRASH
  Application Name:	citra-qt.exe
  Application Version:	0.0.0.0
  Application Timestamp:	57362e26
  Fault Module Name:	citra-qt.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	57362e26
  Exception Code:	c0000005
  Exception Offset:	00000000000d4537
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	9f94
  Additional Information 2:	9f94349997ccd59c7f7c95213d2a957e
  Additional Information 3:	d569
  Additional Information 4:	d569749d2ff463ac3ff1a08d9257eea3

This is an image on the error .
![fix](https://cloud.githubusercontent.com/assets/19361741/15268836/6668659a-1a16-11e6-9bfb-7bb29ad217ff.png)

**Comment by JayFoxRox** [comment]
Closed as invalid because there is not enough information.
Please provide more details:
- Which game
- Post a full log
- Does the game hang / freeze before? does the screen stay black?
- What PC did you use?
...

---

It looks like you are trying to run Pokemon ORAS (illegaly, as that filename has been seen a lot with piracy users..):

1. Don't download games
2. Don't ILLEGALY DOWNLOAD GAMES!
3. **DON'T** DOWNLOAD GAMES ILLEGALY
4. Pokemon ORAS doesn't work on Citra yet.

**Comment by Razeram** [comment]
oh i try to load with pokemon X but it didnt work (bad english sr)
what does u mean full log ?
3. I tried to open with old version of citra it turn to black (pokemon X not ORAS)
4 My Pc is : Intel Core i3 3210 3,2GHz
Ram 4Gb
window 7.64 bit and my card is nvdia gt 630 1gb

**Comment by JayFoxRox** [comment]
Pokemon X won't work yet either.

The log is the text in the black console window with yellow/red text. We would need ALL of the text from that window. However, Pokemon not working is a known issue and we are working on it.
- Don't expect it anytime soon either.

(If you see vids of other people running Pokemon on Citra that's because they use inoffical versions of Citra which we do not support)

**Comment by Razeram** [comment]
ok thank :dancer:
