### ISSUE TITLE
Sound Doesn't work 

### ISSUE THREAD

**Issue by Gamedev1909** [citra-emu/citra#1833]
so in os x Sound doesnt work even with the SDL2 framework inside cita-qt any fix for audio?

**Comment by JayFoxRox** [comment]
Are you really using the latest nightly build which even supports audio? (There was one version which has the menu but no actual audio)
Please consult [the forum for user questions](https://discuss.citra-emu.org/).

Closing as invalid because this is formulated as a question and no version information etc. was provided.
