### ISSUE TITLE
Combat of Giants: Dinosaurs 3D - Graphical issues (missing text)

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1858]
Tested also with GS https://github.com/JayFoxRox/citra/tree/gs-new-refactor and it's the same

[LOG](http://pasted.co/35382c33)

**3DS:**

![combat of giant dinosaur 3ds 1](https://cloud.githubusercontent.com/assets/11453507/15625425/baab63e2-24a6-11e6-9ba0-7408378d643f.JPG)

![combat of giant dinosaur 3ds 2](https://cloud.githubusercontent.com/assets/11453507/15625426/ce2ff234-24a6-11e6-8b4f-3bcfb6ffe628.JPG)

![combat of giant dinosaur 3ds 3](https://cloud.githubusercontent.com/assets/11453507/15625431/d41e7922-24a6-11e6-9012-5fc416dc3810.JPG)

![combat of giant dinosaur 3ds 4](https://cloud.githubusercontent.com/assets/11453507/15625433/d9e18836-24a6-11e6-8aca-c73d6205f548.JPG)

**Citra:**

![combat of giant dinosaur 1](https://cloud.githubusercontent.com/assets/11453507/15625436/e024639e-24a6-11e6-8d03-4ab3e37cb13c.JPG)

![combat of giant dinosaur 2](https://cloud.githubusercontent.com/assets/11453507/15625438/e4e7bd86-24a6-11e6-9fd0-776f3d4eecf9.JPG)

![combat of giant dinosaur 3](https://cloud.githubusercontent.com/assets/11453507/15625440/e96366f8-24a6-11e6-9368-76786580e78e.JPG)

![combat of giant dinosaur 4](https://cloud.githubusercontent.com/assets/11453507/15625441/edf8b182-24a6-11e6-8a35-9c3d33f5ccdc.JPG)

![combat of giant dinosaur 5](https://cloud.githubusercontent.com/assets/11453507/15625442/f2aeef66-24a6-11e6-965a-d0cabef2e2c8.JPG)

**Comment by JayFoxRox** [comment]
This is caused by `Source::Texture3` ("source op 6") not being implemented.
We return 0.0 as default, but that means the game will multiply away all color.

I propose we stub the `Source::Texture3` with another color. I noticed this just by messing with the Texture3 value. I'm not sure if the game actually uses Texture3 or wether this is a bug (accidentally using Texture3 or using it as some kind of "always-white-texture").

I've still tagged this proctex for now as it's clearly impacted by Texture3

**Comment by wwylele** [comment]
Is this fixed?

**Comment by JohnGodgames** [comment]
Yeah tested on https://github.com/citra-emu/citra/commit/bae3799bd5208d08bb52546ad0723103c94cada3
