### ISSUE TITLE
CFG service: Unimplemented config block entries

### ISSUE THREAD

**Issue by fox8091** [citra-emu/citra#1870]
The "Unknown" fields SOUND_OUTPUT_MODE and STEREO_CAMERA_SETTINGS correspond to sound output mode (Mono, Stereo, Surround), and Camera calibration respectively.

**Comment by wwylele** [comment]
Sound output mode selection is now implemented in system settings configuration. Note that CFG sound output mode doesn't has relationship with DSP sound output mode in 3DS system (i.e. citra) level.

For STEREO_CAMERA_SETTINGS, my 3DS has _exactly_ the same value as Normmatt's (which citra uses) in this block, so there is a less chance it is the calibration data. As an additional  evidence, the output of cam:GetStereoCameraCalibrationData from my 3DS is different with yuriks' (which citra uses). The relationship between STEREO_CAMERA_SETTINGS and calibration data is not clear.

**Comment by fox8091** [comment]
Could you try changing the data using Config and seeing if output changes?

**Comment by wwylele** [comment]
@fox8091 Will do it soon. However, before doing it, I did some disassembly work, and found this block is read by almost every games of mine, even for those don't use camera at all. So apparently this is not camera related.

An interesting finding is , I searched the config block reading code in _Inazuma Eleven 3_ (which uses CRO, which contains symbols information), and find it is under the namespace `StereoCamera`. From the comment in citra's code, and the fact other 0x0005000* config blocks are all GSP related, my guess is that the "stereo camera" here means the _virtual_ camera in game space, instead of the physical camera of 3DS. This config block actually contains the parameters of the stereo LCD screen

**Comment by Subv** [comment]
This is not really an issue report.

**Comment by fox8091** [comment]
Care to explain why?

**Comment by JayFoxRox** [comment]
Because issues should not be a way to document the 3DS. Documentation should be done on other platforms like 3dbrew / \#3dshacks.
We can then link to such (confirmed / verified) documentation when proposing new features or when bugs arise.

If this is indeed a mismatch between Citra source code and documentation you should provide line numbers for the Citra source + links to the doc. However, as work involved in fixing these kind of issues (once documentation exists) is minimal it's probably better to open a PR directly.
