### ISSUE TITLE
citra-qt.exe has stopped working

### ISSUE THREAD

**Issue by Pearnest** [citra-emu/citra#1909]
It works fine when i load .cci that's not that large. However, every time I try to load pokeMon.cci, which is about 2GB, it instantly crushes and shows a warning dialogue saying citra-qt.exe has stopped working. 

Warning message in the Console Says:
Service::Interface::SyncRequest:70: unknown / unimplemented function 'Subscribe': port=srv:, smd_buff[1]=0x209

I am not sure if there's something wrong with my hardware:
i7-4760HQ@2.1Hz
Intel(R) Iris(TM) Pro Graphics 5200.

Whatever, greatest gratitude to the coders.   :)

**Comment by Jobenblue** [comment]
oras/xy don't work

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game, pirated 3DS bios files, unofficial or old builds.

**Also note that we do not support Pokemon. Pokemon is NOT supported [and not working](https://github.com/citra-emu/citra/issues/1795); no version, not X, not Y, not ORAS, nothing. Come back in a couple of months but don't expect anything.**

---

Closed as invalid

**Comment by FGServers** [comment]
Citra is a pure lie smoke programmers not interested in Pokemon games also do not care about improving performance and sucks in amd bo Sorve is very slow tried it up with a r9 360 and did not know me answer and take months .de programming and nothing about pokemon and performance we eato and tired enough with what to expect me buy a 3DS and I'm from Argentina and things cost people stop deceiving not only seek money ..

**Comment by kreedz1** [comment]
@JayFoxRox I hope people like this guy ^ don't discourage you from the amazing work you guys are doing, just another entitled pokemon seeker.

**Comment by JayFoxRox** [comment]
@FGServers you've said it on the Forum, you've said it here. And both times it's worth absolutely nothing and makes you look like a prick.

I have no idea what you mean about AMD issues. There are [only 2 issues opened which even mention AMD](https://github.com/citra-emu/citra/search?utf8=%E2%9C%93&q=amd+is%3Aissue+is%3Aopen&type=Issues) but those are probably happening on Intel CPUs too. If your post was about GPU it's most likely a driver issue. Complain to AMD - not us. I've taken great care to fix fog after the first AMD issues surfaced, but there are no known problems with AMD drivers at this point and anything to be merged (especially fog) is also working on AMD.
If anything you can blame guys like yourself for not testing PRs properly as developers don't have the option to test on many systems beyond their own.

Your R9 360 is useless here because Citra is mostly CPU bound (as most other emulators). This will always be the case probably but the CPU requirements will reduce in the future. However, that requires a lot of work and all developers are volunteers. Also performance is not considered important at this point. It's way easier to fix the problems now, make Citra stable and once everything is well understood make it faster (which means more complicated code which is harder to debug).
If we'd optimize now we'd risk having to do everything again later when we see that there are design issues which make some things impossible.

Also there is no official support for Pokemon because it's only a handful of games and the 3DS has many more games to offer which are easier to support. Pokemon only needs one unsupported feature at the moment which is still not well understood, the existing implementation is not too good.
Also the attitude of Pokemon players like you is very demotivating so developers are not interested in having to deal with that either.

Yes, if you want to play Pokemon try an unofficial build. BUT: don't expect support from Citra developers anywhere as you are using work-in-progress stuff which makes debugging much harder + most issues are probably known anyway.
If that doesn't work for you (either because it's not stable or because it's slow) then you should indeed buy a 3DS.
\- Citra is much more important for preservation than your selfish goal of playing Pokemon.
We won't sacrifice code quality and the future of Citra for ignorant people like you.
(There are enough unofficial builds which do that, note that their code is still written by active Citra contributors in every instance I know - it's usually just an assembly of crashy and hacky work-in-progress stuff)


So **please** stop being ignorant. This is the last warning.
If you keep acting like this we'll have to ban you from the community.

**Comment by buster77fa** [comment]
@JayFoxRox good work on citra, random guy with free time on his hands here, wish you guys had more stuff on d-easy d-intermediate etc.. i have free time and nothing to do with it

**Comment by JayFoxRox** [comment]
Get on IRC (#citra or #citra-dev on freenode. [You can also use a webchat](http://webchat.freenode.net/?channels=citra)). We always have problems to solve. I don't really like the `d-easy` / `d-intermediate` tasks myself. They aren't very accurate sometimes and highly subjective.

I'll lock this now to avoid further offtopic talk.
