### ISSUE TITLE
Frameskip issue

### ISSUE THREAD

**Issue by teogorghin** [citra-emu/citra#1960]
Hello! When frameskip will be fixed? It helps you to speed up the game with 10 , 20 FPS.
Example of emulator with frameskip: Dolphin

**Comment by JayFoxRox** [comment]
Probably never?

I'm in favour of removing it entirely, it's my understanding that it's been "broken" for a long time.
Also, it's a dirty hack (by design) and the GPU probably won't be the bottleneck for a very long time.

It should only be kept if it was easy to maintain and didn't cause any problems.
I'd expect that the current (and most other!) implementation will break graphics, but also the games internal memory (due to the framebuffer readback and software rendering effects - pixel counting etc.).
\- We'll get a ton of bug reports because everybody will use "the magical frameskip-device" without understanding what it actually does.

**Comment by shinyquagsire23** [comment]
> I'd expect that the current (and most other!) implementation will break graphics, but also the games internal memory (due to the framebuffer readback and software rendering effects - pixel counting etc.).

(It does by the way, if I set frameskip above 0 it just displays nothing in most if not all games.)

**Comment by Subv** [comment]
> I'm in favour of removing it entirely
Agreed, it's been broken since it's inception.
