### ISSUE TITLE
Phoenix Wright Dual Destinies Not working

### ISSUE THREAD

**Issue by YisKudo** [citra-emu/citra#1961]
Phoenix wright dual destinies won't open it shows a black screen

**Comment by JayFoxRox** [comment]
Duplicate of https://github.com/citra-emu/citra/issues/1597

Closed.

**Comment by YisKudo** [comment]
But there is no solution on that thread

**Comment by JayFoxRox** [comment]
Because it's not a thread. This is a bug tracker for developers of Citra.
The game does not work yet, there is no solution for it yet either.

Also, please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.
