### ISSUE TITLE
Game Crash [Super smatch bross]

### ISSUE THREAD

**Issue by TamTahiti** [citra-emu/citra#1978]
Hello, I face a problem when launching the game.

I hope to help develop .
![run issue](https://cloud.githubusercontent.com/assets/20630502/17087425/2d0336ce-51a5-11e6-88c8-75e54f517731.png)

**Comment by JayFoxRox** [comment]
[This is a known issue](https://github.com/citra-emu/citra/issues/834)
Also [note this about title issues](https://github.com/citra-emu/citra/issues/1979#issuecomment-234884181) and check your spelling of the issue title before posting (because it adds a log entry if you change it later + it's confusing; so it's best to avoid renaming it).

Closed as duplicate.
