### ISSUE TITLE
Braindump CXI issue - Assertion Failed, Unexpected thread priority!

### ISSUE THREAD

**Issue by KillzXGaming** [citra-emu/citra#2013]
Launching the game (Dumped US copy via brain dump) and gives this error: 

![h](http://i.imgur.com/OcH51xn.png)

[Log](http://pastebin.com/8eqcpwQY)

Specs:
I5 4670K
8GB RAM
GTX 970

**Comment by legoj15** [comment]
Happens to me with _Iron Fall: Invasion_ and _Mii Maker_

**Comment by wwylele** [comment]
Could you check the actual value of the thread priority? (by using debugging tool or edit the source code)

**Comment by wwylele** [comment]
@legoj15 from which firmware version did you dump the mii maker? Because mine dumped from 9.2 works well.

**Comment by KillzXGaming** [comment]
I wanna point out. Seems to be a cxi file issue. Game boots as 3ds.
![Alt Text](http://i.imgur.com/ZruRRx2.png)

**Comment by legoj15** [comment]
@wwylele Dumped Mii Maker via braindump on firmware 10.7 U

**Comment by wwylele** [comment]
So probably this issue should go to braindump?

**Comment by poutros** [comment]
@legoj15 I dumped mii maker through manual means and, besides #2012, there isn't any other issue so it most likely is a braindump issue.

**Comment by wwylele** [comment]
Research result:
This is due to the fake exheader generated by braindump. More specifically, `exheader_header.arm11_system_local_caps.priority` (=main thread priority) is set as 0 by braindump(where it should be 0x30 or so). Games / apps sometimes calculate the priority of new-created thread relative to the main thread, thus make a out-of-bound priority since the main thread priority is already wrong.

Close as this is not an issue in citra.
