### ISSUE TITLE
I got a problem during the building of citra

### ISSUE THREAD

**Issue by Allanouille** [citra-emu/citra#2016]
Hi, i'm sorry but i don't understand why i have this error : CMake Error at CMakeLists.txt:144 (message):
  No bundled SDL2 binaries for your toolchain.  Disable
  CITRA_USE_BUNDLED_SDL2 and provide your own.
Is anyone can explain what i should do. Thank you

**Comment by jroweboy** [comment]
So first off, I think this is better suited to go on the forums. If my suggestion below doesn't work, reopen this on the forums and we can talk more about it there. https://discuss.citra-emu.org

It sounds like you aren't selecting "Visual Studio 14 2015 Win64" when choosing your compiler. It has to be exactly that in order to get cmake to download the externals. Delete your cache and select the Win64 version. If that doesn't work, bring it up on the forums and we can talk more about it.

**Comment by Allanouille** [comment]
Yes it's working but at the end of virtual studio. I can launch citra -qt and play? Because i tried with Bravely Second but it results critical error

**Comment by wwylele** [comment]
@Allanouille Please go to our [forum](discuss.citra-emu.org) for further support. This issue tracker is for development use.

Close as invalid.
