### ISSUE TITLE
Support multi-windows mode

### ISSUE THREAD

**Issue by linkmauve** [citra-emu/citra#204]
Some usecases would be top-bottom dual-screen setups, middle gap emulation…

**Comment by gab** [comment]
+1 Being able to have two windows you can just drag/resize/maximize would make all the difference in the world. I gave up playing games with Citra because on a standard widescreen monitor one of the DS screens is forced to be uncomfortably way smaller than the other, and none of the community tutorials (most of them outdated it seems) I followed to use two screens worked.

The option of using borderless windows (specifying which screen) would also be nice, but we can also force that with 3rd-party tools.

**Comment by JohelEGP** [comment]
See also #4780.

**Comment by SuperJumpBros** [comment]
+1. I'm wondering why this hasn't already existed!

Hope the developers create this feature, it would be great! For now, it's kinda tough using one monitor and needing to swap screens when I need to look at the other one. Luckily, I'm playing a game that is very intensive on the bottom screen and not much on the top one. I can just swap between them, but I still think this would be a major feature and would make 3DS gaming on computers so much better!

**Comment by dillon-hubble** [comment]
This would be useful for the very popular Steam Deck

**Comment by FearlessTobi** [comment]
Fixed by https://github.com/citra-emu/citra/pull/6177.
