### ISSUE TITLE
frameskip on jit cpu mode give much fps in varius games but  has glitches graphics

### ISSUE THREAD

**Issue by suelo50** [citra-emu/citra#2046]

**Comment by suelo50** [comment]
example projext x zone 1 and 2 on frameskip 2  has 60 fps on my pc

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

Also respect general etiquette, otherwise you'll be suspended from the forums too.

---

Closed as invalid
