### ISSUE TITLE
Pokemon X/Y Obtaining/Receiving Crash

### ISSUE THREAD

**Issue by dracobuonk** [citra-emu/citra#2062]
Maybe most of you noticed that too but game crashes right after whatever you obtain/receive. First i was trying to obtain my starter pokemon, It was crashing. Then i found a save file but it crashed again when i came back to home and received Town Map from Mom.

By the way it looks so playable! After taking care of these crashes we will be able to play thanks to you guys, good work!

**Comment by Daiana3390** [comment]
I have the same problem. Whenever I try catch a pokemon, receive an item, find an item on the ground or generally add something, the game stops at "You received ???". It doesn't freeze or crash! You can see that is running, but the text just stops there... Is  there a way around it? Are you looking into it? And yes the game is totally playable apart from this! :)

**Comment by dracobuonk** [comment]
Exactly same!

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

---

Closed as invalid. This issue is going nowhere if the discussion starts out like this.
