### ISSUE TITLE
Citra gives me an odd error message, so I must be doing something wrong ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by whysomanypilots** [citra-emu/citra#2089]
I seriously don't know anything about anything with Citra, I'm just trying to play this game and none of the things I'm trying are working?  Well, I mean, I'm probably not doing it right but I keep getting this error and I was trying to find it - but I couldn't.
the only good amount of information I could really bring forth is the error message I was getting.

[ 624.025272] HW.GPU <Error> video_core\shader\shader.cpp:WriteProgramCode:301: Invalid GS program offset 1024
[ 625.972274] HW.Memory <Error> core\memory.cpp:GetPointer:279: unknown GetPointer @ 0x1f600000

I was trying to open it on what I assume is called a "build", I think?  I tried on multiple ones and all I got was this message in a few seconds.  The game didn't even start up.  

Sorry this probably looks dumb to a lot of you but I have a small brain and cannot help my cognitive skills aren't fully developed enough to understand what's even going on

**Comment by wwylele** [comment]
Could you provide a full log? Also I suspect a buggy graphics driver, so try updating the driver?

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game, pirated 3DS bios files, unofficial or old builds.

This is an issue (dare I say: bug) which only exists in my geometry shader branch which is not included in official builds. It's not an error either - just a warning as the GS cursor starts out uninitialized.
Also that is only a warning - not an important error.

---

Closed as invalid

(Aside from that the whole style of this issue is horrible - do not use stupid ASCII art in your issue title and make the problem more clear, you didn't mention any factual information here)
