### ISSUE TITLE
Danball Senki Wars video load crash.

### ISSUE THREAD

**Issue by Salijour** [citra-emu/citra#2096]
After hitting A at the warning screen. The game crashes at the point where it would load a video that has logos and the anime opening. I think they are all one video instead two or three like it was common on the ds and psp.  ~~#2030 might be the same problem, since the games are made by the same company and there is a good chance they handled the opening videos the same.~~ 
**Log**:
![log](https://i.gyazo.com/90f6789a405b4fb7bd3bdff219ed8b83.png)

**Comment by wwylele** [comment]
Candidate:
> Newly created thread is allowed to be run in the SysCore

**Comment by Salijour** [comment]
Not fixed by #2154.

**Comment by JayFoxRox** [comment]
Could you be more precise please? Re-test on the latest master and tell us if it worked or not.
Just saying "Not fixed by XYZ" doesn't help because we don't know if you just used that branch (which could be a very old master + we don't even know at which point in time you used it)

Always provide a commit hash in all of your posts. Your original post was lacking such information too.
You should also provide a backtrace for *crashes* and check if it happens with / without shader jit / interrpeter, cpu jit / interpreter, hardware / software rendering.

**Comment by Subv** [comment]
Could someone please re-test this?

**Comment by Salijour** [comment]
Retested on b36677d 1/11/17 Nightly

This is an archive of what Subv wanted from me in the discord. Backtrace + other parts
![backtrace](https://i.gyazo.com/1ce39b202bfcd99fa99f7165fc9acb65.png)

![part](https://i.gyazo.com/b3125fb4bed9ad3ce950fb7def6c9855.png)
![buf](https://i.gyazo.com/6cb43ea9c0b4a5a643d6216d8681833b.png)

![other part](https://i.gyazo.com/077abdf4f86bb2e1fc026323c2cdc1b8.png)

**Comment by benderscruffy** [comment]
using the latest nightly it still crashes after you press the button A


[log.zip](https://github.com/citra-emu/citra/files/1503824/log.zip)
![danball](https://user-images.githubusercontent.com/2696404/33239390-43786294-d2dc-11e7-8edd-e0f6c8440379.PNG)

**Comment by benderscruffy** [comment]
still happens in the latest nightly
[citra_log.zip](https://github.com/citra-emu/citra/files/2722732/citra_log.zip)

**Comment by suelo50** [comment]
still does not work.

**Comment by FashGate** [comment]
The game test results are still crashing

**Comment by Chaitanya41** [comment]
Danball senki wars working on this emulator

Here's the link:https://stfly.io/xCPwk0H

**Comment by benderscruffy** [comment]
still an issue
