### ISSUE TITLE
The Legend of Zelda: Ocarina of Time - Frame skipping issue upon creating save file data

### ISSUE THREAD

**Issue by Dragios** [citra-emu/citra#2105]
This game suffer from frame skippping issue whenever it attempts to create a save file data for the 1st time. Even in actual gameplay itself, the animation will stay choppy. This effect is permanent until the game is reloaded. No clue why this is happening in the 1st place.
[Frame skipped](https://streamable.com/be9vw)

Although, subsequent reload of the game onwards will render everything smoothly ~~except in one particular scene whereby it will slowdown temporarily. (could be due to interpreter fallback)~~ No longer the case here.
[Normal](https://streamable.com/q4nss)

Notice the *Citra*'s internal FPS and frame time reporting are the same for both run.
This does not occur on real hardware.

Full log [before](https://pastebin.com/T1hqwqyD) and [after](https://pastebin.com/R6jjiBQi)

Tested based on latest nightly commit 30fabc41c60b08af20b6eaf719d012b7480d7123

_Note: The video is based on old commit but still relevant as of today (3rd Oct 2017)._

**Comment by ryanterry131** [comment]
Slowdowns in subsequent loads likely isn't due to interpreter fallback, since the amount of unimplemented instructions is few and they likely won't cause any notable lag at this point in the JIT's development, especially considering the odds that many of the unimplemented instructions would be stringed together in a large enough chunk of code that they could even cause slowdown (the interpreter is only really slow when it is the only thing being used, not when only one or two instructions are executed by the interpreter) - probably just due to normal lag from rendering, etc. remember this still a slowly progressing emulator.

**Comment by JayFoxRox** [comment]
Can you test this with JIT enabled / interpreter enabled? [so in total at least 4 runs: JIT+FirstRun, Interpreter+FirstRun, JIT+SecondRun, Interpreter+SecondRun]
Then we can see if the JIT / Interpreter has any influence on this.

Also what's in the log on the first run? Maybe it will throw weird errors all the time which slows emulation down?

Can we have this tested on hardware too? This might just be a stupid bug in the games code.

**Comment by Dragios** [comment]
JIT/Interpreter does not have any influence at all. Actually this has happen way before even JIT got implemented but I did not report it because I thought it will be fix in future but seems like not.

The game will slow down a bit due to this spamming
`Render.OpenGL <Warning> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:478: API OTHER 65536: Framebuffer unsupported. Framebuffer object 3 is unsupported because the depth and stencil attachments are mismatched.`

Performance of both 1st run and 2nd run are the same, it's just that the 1st run suffer from frame skipping despite running at the same performance as the 2nd run.

Below are the logs I find it unique.
_This log appear on both runs_
`Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:74: unknown / unimplemented function 'SetInternalPriorities': port=gsp::Gpu, cmd_buff[1]=0x19, cmd_buff[2]=0x1A`

_This log appear only on 1st run (could be the cause or not)_
`Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::OpenArchive:435: failed to get a handle for archive archive_id=0x00000004 archive_path=[Empty]`

**Comment by freiro** [comment]
Can you check if this issue still happens in the latest master?

**Comment by solarplexus6** [comment]
I'm experiencing the issue with warning spamming `API OTHER 65536: Framebuffer unsupported...` on nightly build ad4097e, with OoT, but the frame rate seems fine on my pc.

**Comment by Dragios** [comment]
Reuploaded a new video. Tested on the the latest nightly and issue still persist. Does not occur on real hardware.

**Comment by Forkinator** [comment]
Also experiencing this same issue on nightly ed17c54 and canary 5073c99.

[7166.927179] Render.OpenGL <Warning> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:472: API OTHER 65536: Framebuffer unsupported. Framebuffer object 3 is unsupported because the depth and stencil attachments are mismatched.

Also getting audio crackling after 20 minutes of play. Doubt that is related to the  previous issue though.

**Comment by Dragios** [comment]
Fixed by #3307
