### ISSUE TITLE
Dragon Ball Fusions - Black outlines remain

### ISSUE THREAD

**Issue by Atsuraelu** [citra-emu/citra#2135]
DBF suffers from similar black lines as mentioned in #2041:

![Image of black lines ingame](https://dl.dropboxusercontent.com/u/32279998/DBF_Black_Lines_1.PNG)
![Second image of black lines ingame](https://dl.dropboxusercontent.com/u/32279998/DBF_Black_Lines_2.PNG)

They appear in the "overworld" and indoors but will disappear once the game enters combat.

Citra version cc7f115. Issue only occurs with HW renderer, but independent of enabled shader JIT.

Small update: It appears they are only a problem indoors. In the "overworld, they just do not disappear like they do in battle, but neither are there any more created.

**Comment by JayFoxRox** [comment]
@Atsuraelu That vsync "issue" doesn't belong here - it's expected (Consult IRC / forums / discord for more info as to why this happens).

Please add the version number you have been using to the post too and add wether this is HW or SW rendering, shader jit or not etc.
- I'll remove this post once these points have been addressed

Also, renaming issues sucks because it adds a log entry. Next time choose a more descriptive observation such as: "Dragon Ball Fusions - Black outlines remain" or something like that - We'll then add tags later to show what kind of issue it is once we know the cause.

**Comment by Subv** [comment]
Please test with #2218

**Comment by Atsuraelu** [comment]
Tested with bleeding edge build number 70 (5759a30). Issue is fixed in that build.

**Comment by freiro** [comment]
we can close then 👍
