### ISSUE TITLE
Pre-commit hook does not check for clang-format

### ISSUE THREAD

**Issue by jphalimi** [citra-emu/citra#2155]
Commit Hash: 958e81404b85d60c71626796812be300a07cc41a
OS: Linux jphalimi-desktop 4.4.0-45-generic #66-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 16.04)

The git hook that is responsible to check code style does not check that clang-format is installed, although it is required.

Consequently, the hook will reject any commit, asking developers to remove the content of the files that were modified or added in the commit.

Here is an example:

```
.git/hooks/pre-commit: 35: .git/hooks/pre-commit: clang-format: not found
!!! src/video_core/shader/shader.cpp not compliant to coding style, here is the fix:
--- src/video_core/shader/shader.cpp	2016-11-02 15:45:55.592484422 -0700
+++ -	2016-11-02 16:05:29.050207149 -0700
@@ -1,160 +0,0 @@
-// Copyright 2015 Citra Emulator Project
-// Licensed under GPLv2 or any later version
-// Refer to the license.txt file included.
-
-#include <atomic>
-#include <cmath>
-#include <cstring>
-#include <unordered_map>
-#include <utility>
-#include <boost/range/algorithm/fill.hpp>
-#include "common/bit_field.h"
-#include "common/hash.h"
-#include "common/logging/log.h"
-#include "common/microprofile.h"
-#include "video_core/pica.h"
```

**Comment by jphalimi** [comment]
I have submitted a patch to fix this issue here: https://github.com/jphalimi/citra/commit/d03c1c6367338ec6708af920aa71dad0427ccd93

**Comment by JayFoxRox** [comment]
About your patch:
Are you planning to send a PR?
What needs to be done to complete this / current problems?

**Comment by wwylele** [comment]
I didn't know we have format check in the hook, for it doesn't work on my PC at all for some reason - it always passes the check even if there is a format error. I have clang-format installed on my computer.

Now I am for completely removing this check: the format check shouldn't be mandatory at pre-commit stage, because one can make temporary / testing / for-fun commits that doesn't strictly follow the  rule, and they just need to clang-format everything eventually when they think it is ready to push it to the master branch. After all, we have another format check in our CI, which is enough for a contributor to learn how to correct the code style.

**Comment by mailwl** [comment]
on MacOS X git checks stylem and do not allow to commit

**Comment by jphalimi** [comment]
Ok, so there's a bunch of things to say here:
@JayFoxRox:
**What needs to be done to complete this / current problems?**
The patch I submitted should be enough to solve the problem.

 **Are you planning to send a PR? (Why not?)**
I have to admit I am new to Github contributions, so I did not know what PR standed for, for a while. Let me create a PR for this now. :-)

@wwylele, I think this is a different problem, although if it does not work I agree it should, or should be removed. @jbeich, it seems you are the author of this pre-commit line (3925f4ff). Is there something that we don't understand with respect to how your code works?

**Comment by jbeich** [comment]
@wwylele wrote:
> the format check shouldn't be mandatory at pre-commit stage, because one can make temporary / testing / for-fun commits that doesn't strictly follow the rule

Why would one install the pre-commit hook then? It also nags about whitespace issues.

@jphalimi wrote:
> @jbeich, it seems you are the author of this pre-commit line (3925f4ff). Is there something
> that we don't understand with respect to how your code works?

Are you implying a regression? `clang-format` check was added by 491f5bab88b6 originating from dolphin-emu/dolphin@3af8f7147256.

Otherwise, jphalimi@d03c1c6 looks reasonable.

**Comment by wwylele** [comment]
Turns out that the problem of mine is just that I didn't update the hook (had to delete the hook in `.git/hooks` and run `cmake`)  so nvm about that. (but this can be another issue)

@jbeich : 
>Why one would install the pre-commit hook then? It also nags about whitespace issues.

I am ok with the whitespace check because it is easy to keep the rule when coding and to correct by editor/IDE.

**Comment by MerryMage** [comment]
pre-commit hook no longer runs clang-format locally as of #2579.
