### ISSUE TITLE
Move user folder on windows to the user's home folder

### ISSUE THREAD

**Issue by jroweboy** [citra-emu/citra#2177]
Currently on macOS and linux, the user directory for citra (which contains configuration and other things) is located in the current user's home directory/.local On windows, the directory is contained inside the current citra folder, which makes updating more painful than it needs to be. When a user downloads the new nightly build, they need to copy old information from their user folder over to the new download directory, something thats "Yet Another Thing To Train People To Do." I suggest moving the user directory to the home folder on windows as well, so that its unified across all platforms. Potentially we can move it to AppData/Local/citra where it should go, but that might make it more painful for people to find as windows hides the AppData folder.

**Comment by JayFoxRox** [comment]
How does other (recent) Windows software do it?
Is there a guide on the MSDN or something?

(I remember GTA3 and Vice City (15 years ago; feel the age!) storing all savegames etc. in a "My Documents" subfolder or something :P )

**Comment by SonofUgly** [comment]
>How does other (recent) Windows software do it?

Either in Appdata or My Documents. Appdata seems to be becoming the more popular option.

Either way I think there needs to be a way to keep it portable like it is now. Dolphin has it so that if you have a file called portable.txt in the same directory as dolphin.exe then it'll run as a portable install, otherwise it'll put everything in My Documents.

**Comment by linkmauve** [comment]
In Citra it’s the presence of a directory named “user” in the cwd that will trigger that portable mode.

**Comment by freiro** [comment]
> In Citra it’s the presence of a directory named “user” in the cwd that will trigger that portable mode, on every OS.
When Citra is in this non-portable mode, where should the user folder be located (on Windows)?
Because I am pretty sure that if there isn't one, Citra will create it (while not looking elsewhere).

I agree with the OP we should fix this somehow while keeping in consideration that using the same configuration file between git, nightly, bleeding edge might break something.

**Comment by mailwl** [comment]
`char* appdata = getenv("APPDATA");`
return something like "c:\Users\%username%\AppData\Roaming"
don't work on XP :)

**Comment by linkmauve** [comment]
We don’t support Windows XP, do we?  Even Microsoft doesn’t support it anymore.

**Comment by JayFoxRox** [comment]
@freiro we could simply have a citra folder for the main release and patch it for bleeding edge to use a citra-bleeding-edge folder if it ever became a problem

**Comment by freiro** [comment]
this can be closed 👍
