### ISSUE TITLE
Direct3D Support

### ISSUE THREAD

**Issue by devoche** [citra-emu/citra#2212]
Any hope for direct 3d support?

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

---

We don't want feature requests here.
Also: Yes if someone works on it.

However, there is absolutely no benefit, but a lot of drawbacks from a Direct3D backend (Feel free to name a single benefit of Direct3D over OpenGL). While there might be *some* reasons, most of them are not nearly important enough to warrant the amout of work to make this happen. And mostly people request Direct3D because they have been brainwashed by Microsoft marketing.
If anything we should fix the software rendering and work on a Vulkan backend - that's just my opinion though.

---

Closed as invalid

**Comment by mailwl** [comment]
adept of microsoft...
(sorry for comment closed issue)
