### ISSUE TITLE
Pokémon Omega Ruby/Alpha Saphire ‒ Objects close to camera block view

### ISSUE THREAD

**Issue by Dragios** [citra-emu/citra#2248]
Only when using *Hardware Rendering* displays the wrong behaviour

Left side is from **Nintendo 3DS** and right side is using the **Citra** emulator
![May's room](https://cloud.githubusercontent.com/assets/18496868/20776846/0a0e5efa-b79e-11e6-84f8-456a5a93b2d5.png)

![Professor Birch's Lab 1](https://cloud.githubusercontent.com/assets/18496868/20776848/0d34e18a-b79e-11e6-8271-3104c7c25bbe.png)

![Professor Birch's Lab 2](https://cloud.githubusercontent.com/assets/18496868/20776851/10c3b01a-b79e-11e6-9bf7-44ffdff68435.png)

Nothing useful in log (continuous spamming with this):
```
Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:SetAxiConfigQoSMode:349: (STUBBED) called mode=0x00000203
Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:SetAxiConfigQoSMode:349: (STUBBED) called mode=0x00000205
```

Switching to *Software Renderer* the view is corrected but the text is garbled somehow (that is another issue by the way).
![Correct view](https://cloud.githubusercontent.com/assets/18496868/20777248/b3459496-b7a0-11e6-8fa1-208d722e1827.png)

Again nothing useful in log for software renderer:
```
Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:SetAxiConfigQoSMode:349: (STUBBED) called mode=0x00000203
Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:SetAxiConfigQoSMode:349: (STUBBED) called mode=0x00000205
Render.OpenGL <Error> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:483: API ERROR 1282: GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL.
```
`Render.OpenGL` log shown 12 times before restart back to `Service.GSP`
Not sure if that is useful in any manner but I mention it anyway

Tested this on commit 3174bfd
**OS:** _Windows 10 build 14393.447 (codename Redstone 1)_
**GPU:** _nVidia GT 610 2GB DDR3 (Asus)_
**Driver:** _Version 375.95_
**OpenGL:** _Version 4.5_
_________
Save file included to reach the scene quickly
[Scene 1.zip](https://github.com/citra-emu/citra/files/1219365/Scene.1.zip) - *Just walk up the stairs to proceed*
[Scene 2.zip](https://github.com/citra-emu/citra/files/1219366/Scene.2.zip) - *Just enter the Professor's Lab to proceed*

**Comment by Subv** [comment]
I did a little digging on this, the problem seems to lie in the depth test, this is the depth buffer before the head is drawn: http://i.imgur.com/t4ezELa.png . Notice how none of the values are zero.
Then the head is drawn with depth_func = GreaterEqual, which should cause it to not draw stuff with zero depth, but this is the output depth buffer after the draw call: http://i.imgur.com/hhWXLVA.png

This could indicate a driver bug, but getting to that scene to test takes time

**Comment by Subv** [comment]
After some more digging, it turns out that the character's body is drawn with a negative depth value after our fragment shader runs, which causes the assignment to gl_FragDepth to be clamped to 0.

Discarding the fragments with negative depth "fixes" the issue but i don't know if that's ok.
The aforementioned change also fixes #2724

**Comment by Subv** [comment]
After performing a hwtest, it is verified that the 3DS also clamps negative depth values to 0 and does not discard them, so that's not the issue here.

I speculate the problem lies in this calculation https://github.com/citra-emu/citra/blob/master/src/video_core/renderer_opengl/gl_shader_gen.cpp#L1115

**Comment by wwylele** [comment]
I think I found the problem, or at least the cause of different behaviour between swrasterizer and gl renderer.

The difference is clipping. GL-spec clip primitives with z range of `-wc <= zc <= wc` (gl spec 4.3 core, 13.5), while our swrasterizer clip it with [`-wc <= zc <= 0`](https://github.com/citra-emu/citra/blob/21204ba488fd00be4cc6e44998c5d7c8bd0fec91/src/video_core/swrasterizer/clipper.cpp#L123-L124). The model near the camera gets clipped away in swrasterizer, while not in the gl one.

btw, the formula @Subv mentioned is indeed correct. It is just very hard to read. It performs the inverted operation of the gl coordinate transformation from device coordinates [-1, 1] to window coordinates [near, far] with default value near=0 and far=1. Note that the formula should be read together with the random negative sign here:
https://github.com/citra-emu/citra/blob/21204ba488fd00be4cc6e44998c5d7c8bd0fec91/src/video_core/renderer_opengl/gl_shader_gen.cpp#L1198

**Comment by wwylele** [comment]
Here is a program modified from devkitPro/3ds-examples/graphics/gpu/texture-cube showing the bug
```
--- a/home/wwylele/3ds-examples/graphics/gpu/textured_cube/source/main.c
+++ b/home/wwylele/3dsdev/textured_cube-clip/source/main.c
@@ -95,7 +95,7 @@ static C3D_Mtx material =
 
 static void* vbo_data;
 static C3D_Tex kitten_tex;
-static float angleX = 0.0, angleY = 0.0;
+static float angleX = 45.0f/180 * M_PI, angleY = 45.0f/180 * M_PI;
 
 static void sceneInit(void)
 {
@@ -121,7 +121,7 @@ static void sceneInit(void)
 	AttrInfo_AddLoader(attrInfo, 2, GPU_FLOAT, 3); // v2=normal
 
 	// Compute the projection matrix
-	Mtx_PerspTilt(&projection, C3D_AngleFromDegrees(80.0f), C3D_AspectRatioTop, 0.01f, 1000.0f, false);
+	Mtx_Ortho(&projection, -1.2, 1.2, -2, 2, 0.2, -0.2, false);
 
 	// Create the VBO (vertex buffer object)
 	vbo_data = linearAlloc(sizeof(vertex_list));
@@ -145,6 +145,8 @@ static void sceneInit(void)
 	C3D_TexEnvSrc(env, C3D_Both, GPU_TEXTURE0, GPU_PRIMARY_COLOR, 0);
 	C3D_TexEnvOp(env, C3D_Both, 0, 0, 0);
 	C3D_TexEnvFunc(env, C3D_Both, GPU_MODULATE);
+
+	C3D_DepthTest(true, GPU_GEQUAL, GPU_WRITE_ALL);
 }
 
 static void sceneRender(void)
@@ -152,14 +154,10 @@ static void sceneRender(void)
 	// Calculate the modelView matrix
 	C3D_Mtx modelView;
 	Mtx_Identity(&modelView);
-	Mtx_Translate(&modelView, 0.0, 0.0, -2.0 + 0.5*sinf(angleX), true);
+	Mtx_Translate(&modelView, 0.0, 0.0, 0, true);
 	Mtx_RotateX(&modelView, angleX, true);
 	Mtx_RotateY(&modelView, angleY, true);
 
-	// Rotate the cube each frame
-	angleX += M_PI / 180;
-	angleY += M_PI / 360;
-
 	// Update the uniforms
 	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, uLoc_projection, &projection);
 	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, uLoc_modelView,  &modelView);
```
The cube in this program is clipped by the front and back plane. It can be seen that one clipping plane position in this program differ in hw/swrenderer, and the sw one matches 3DS output.

The bug is hard to show in the default LESS depth test mode, because the extra part that doesn't get clipped will be clamped and fails the depth test. So it is better to use inverted depth like this program to test it.

**Comment by chris062689** [comment]
Fixed by  https://github.com/citra-emu/citra/pull/2884
