### ISSUE TITLE
Unfunctional animation in Pokemon Alpha Sapphire

### ISSUE THREAD

**Issue by volsansky** [citra-emu/citra#2379]
Hi there, I have a problem with Pokemon Alpha Sapphire. For some reason there is no animation of moves and attacks of any pokemon. There seems to be just some light stripes but nothing more. I am using the latest version of Citra Edge yet it doesn´t work (0.1.112) and yet I found out that on some older versions it does work. You have any idea what may be the cause of that?

**Comment by RavenHome1** [comment]
please use the forums for support, github is used to track bugs 

https://discuss.citra-emu.org/

to save you the trouble of posting there, these animations are gone because of removal of geometry shaders in recent builds due to a conflict issues expect them to be back at some point in the future, if you want them back then use older version of citra (somewhere before bleeding 90 or so i recall)
