### ISSUE TITLE
pokemon sun/moon broken particle effects.

### ISSUE THREAD

**Issue by RavenHome1** [citra-emu/citra#2419]
gives a glitchy squares where smoke effect should be present

![example 1](https://cloud.githubusercontent.com/assets/12820322/21754208/46353cf8-d604-11e6-99dc-8b2ecd226a22.PNG)

on 3ds hardware

https://www.youtube.com/watch?v=LQmtr505wTo

![example 2](https://cloud.githubusercontent.com/assets/12820322/21754210/6ba34e1c-d604-11e6-98fb-a0f5bcb7bd9c.PNG)

on 3ds hardware

https://www.youtube.com/watch?v=NfgWTjaB67Q

tried with

cpu jit on and off= same result

shader jit on and off= same result

scaled resolution on and off= same result

could not test with hardware render off  because the game refused to boot and crashes the emulator. 

tested on  nightly HEAD-74217f1 and bleeding 116  both had the same issue

**Comment by hyperdrive3** [comment]
This is because there aren't any geometry shaders in the current build. Basically any particle effects(smoke, sparks etc.) won't render at all or render incorrectly as above. 

Related to #2344

**Comment by RavenHome1** [comment]
@hyperdrive3 i tested with older bleeding which had GS and it works as intended, so yes this issue is GS related

**Comment by marienuac** [comment]
any fix ??

**Comment by hcorion** [comment]
@marienuac 
Patience is the solution.

**Comment by marienuac** [comment]
asking for update 6 months later is patience

**Comment by hcorion** [comment]
Not asking for an update and waiting for devs to fix geometry shaders, is patience.

**Comment by RavenHome1** [comment]
@marienuac you can always use bleeding edge 86 for GS shader but you will be losing a lot of performance, personally i never found the lack of GS in SM to be that experience breaking unlike in ORAS where the attack animations are completely missing.

also keep in mind that citra is an open source project that relies on contribution. there is no specific dev to ask for anything , people work on things when ever they want so implementation of GS can take from a very long time or maybe tmow you will get GS or maybe the maintainer of GS would stop contributing all together and GS would not be implemented at all until someone else picks it up.

**Comment by marienuac** [comment]
so doing nothing while those contributors as you say get stuff working on stuff as they have forgotton about gsicc25 is the solution. k

hurrdurr lets all sit here and wait instead of saying "any fix?" 6 months later to remind ppl heyyy this isnt workinnnng. but no mother FUKKR say no patience so cant even ASK "ANY FIX?" 

HAHAHAH UR PROB THE SAME FUKIN DWEEB THAT SITS ON HIS ASS FOR 2 YEARS WAITING FOR A PAYRAISE FROM HIS BOSS CAUSE "PATIENCE" WILL GET HIM THAT PAYRAISE WITHOUT ASKING OR POKING ALITTLE

R O F L

**Comment by jroweboy** [comment]
@marienuac This is an issue tracker for developers and not a place for users to ask for updates, hence the negative feedback. Ask on the forums for updates instead.

Additionally, your response is completely unacceptable. The fix is several thousands of lines of code that no one got paid to write and no one is getting paid to review it, but despite this, the initial support for the feature was recently added. The person who was working on it got seriously sick and can't finish it right now, so its on hold.

I'm locking this thread as nothing productive is going to happen here.

**Comment by wwylele** [comment]
Should be fixed by #2865. If there is still issue, feel free to comment here / open a new one.
