### ISSUE TITLE
Tomodachi Life hangs after creating savedata

### ISSUE THREAD

**Issue by MattKackles** [citra-emu/citra#2475]
Tested on 
https://github.com/citra-emu/citra/commit/f8523699864b6000572affaa0e36d9a4d89ffce6

Log:
http://pastebin.com/a5un6HsB

**Comment by mailwl** [comment]
here: https://github.com/mailwl/citra/tree/tomodachi
merged wwylele/cec and jroweboy/swkbd branches. After it game is playable

**Comment by acnleditor2** [comment]
@mailwl bugs found on citra for tomodachi life:
When the Miis speak, they do not say everything.
The game crashes when caring for babies.
You can not put most symbols on the keyboard.

**Comment by acnleditor2** [comment]
@mailwl @MattKackles new citra: acnleditor2/citra

**Comment by benderscruffy** [comment]
still happens in the latest nightly and canary
[log.zip](https://github.com/citra-emu/citra/files/1490272/log.zip)
![tom](https://user-images.githubusercontent.com/2696404/33058367-4c51185e-ceca-11e7-93eb-f9f8e43d1493.PNG)

**Comment by acnleditor2** [comment]
@benderscruffy needs cecd

**Comment by acnleditor2** [comment]
@benderscruffy needs cecd and software keyboard

**Comment by valentinvanelslande** [comment]
@MerryMage this issue does not happen because swkbd is not implemented, but there are more issues with this game

This happens because total bytes read is the title ID, this can be fixed by changing all normal params to 0 in unimplemented functions/stubbing OpenAndRead.

Issues that happen because the game uses a custom DSP firmware:
- Lip Syncing Glitchy when Singing/Talking
- The Miis do not finish talking (fix: change ticks to 570 [here](https://github.com/citra-emu/citra/blob/master/src/core/arm/dynarmic/arm_dynarmic.cpp#L98))
- The game freezes when trying to take care of a baby

Issues that happen because swkbd is  not implemented:
- The game freezes when you put the name of the island

**Comment by FearlessTobi** [comment]
This is fixed by #4005.
