### ISSUE TITLE
Lighting issues with ACNL, Smash Bros. 4, and ACHHD

### ISSUE THREAD

**Issue by KillzXGaming** [citra-emu/citra#2477]
This has been around since fragment lighting was first implemented, where you get shiny or over bright lighting on certain models or characters. I have no idea if this is something unimplemented so please correct me if this is the case on what causes this. I've tried searching issues and couldn't find any related issues on this , no idea if this is related to LUT lighting or anything or even just some mip map or rim lighting thing. These are currently the only titles i have so i do not currently know which other titles are affected by this. 

Here are Citra screenshots:
![Alt Text](http://i.imgur.com/3yxSWnY.png)

![Alt Text](http://i.imgur.com/GR4q8n7.png )

 ![Alt Text](http://i.imgur.com/Mbh5C6J.png )

In Game
 ![Alt Text](http://i.imgur.com/Uyk3o4Z.png)

 ![Alt Text](http://i.imgur.com/s8RYmjw.png)  

![Alt Text](http://i.imgur.com/0QqHmZp.png )

Screenshots taken from an older master build from a few weeks ago but i can assure you i tested again just now on this one here:
https://github.com/citra-emu/citra/commit/bf14f4be2263b4769e97800b35951717192c2d1c

PC Specs:
i5 4670k
gtx 970
8gb RAM
Win 10

**Comment by khang06** [comment]
Also happens on some Sun/Moon NPCs.

**Comment by wwylele** [comment]
For Smash Bros 4, it is likely caused by unimplemented geometric factor (see [here](http://mathb.in/64694) for G0 and G1). When rendering characters, the game have the geometric factor register bit enabled. I tried plugging in some geometric factor formula got from google, and the characters do look much more better

![screenshot from 2017-06-07 23-03-01](https://user-images.githubusercontent.com/4592895/26898852-f51e55be-4bd5-11e7-9b92-d9472650b1ed.png)
![screenshot from 2017-06-07 22-58-09](https://user-images.githubusercontent.com/4592895/26898857-f8c8b5c4-4bd5-11e7-95ed-f4fdfd4cc7b1.png)

**Comment by KillzXGaming** [comment]
All games now have proper lighting!
![2](https://user-images.githubusercontent.com/13475262/27265706-562a4518-5467-11e7-86e6-c16896d911de.jpg)

![1](https://user-images.githubusercontent.com/13475262/27265713-6ab49222-5467-11e7-9648-f192da6ccf0a.png)
