### ISSUE TITLE
Pokemon Sun/Moon crashes at intro with Shader JIT on

### ISSUE THREAD

**Issue by wwylele** [citra-emu/citra#2498]
![screenshot from 2017-01-30 15-27-49](https://cloud.githubusercontent.com/assets/4592895/22424851/1aa6910a-e701-11e6-977b-31b46a7628d2.png)

^ Exactly at this point

OS: Ubuntu 16.04
version: master-ff28080

This should be a regression because IIRC I passed this point with shader JIT on. I am going to bisect it.

Log is just StoreDataCache spam and is useless

**Comment by RavenHome1** [comment]
another linux only issue, i tried with the latest nightly and things worked fine

**Comment by LASTWINDOW** [comment]
Working fine for me as well.
Windows 10, Citra | HEAD-ff28080.

**Comment by wwylele** [comment]
Bisected, it is #2346 (cc @yuriks)

**Comment by yuriks** [comment]
Current situation: @wwylele already found what's causing the crash and how to work around it:

Execution reaches a potential subroutine return point, where the JIT inserts a check for a return. This check peeks the value on the stack and compares it to the current IP, and if it matches, does a return. In this case, a value left on the stack by the caller of the JIT happens to match the IP, causing the code to execute a return from subroutine even though there had been no corresponding call in the shader. The solution is to push a dummy value (such as 0xFFFFFFFF) on the stack at the start of the execution of the JIT.

I wanted to investigate why this situation was even happening in the first place: why is execution reaching a potential return point without a call? It's possible the shader code was devious and re-using bits of regular code as a subroutine but I found that unlikely. Looking at the code, there is one call instruction with a return matching the crashing position, but that call instruction can't be reached in any possible execution of the code. In fact, there is a fair amount of unused code at the end of the shader. Near as I can tell, this game does not fill unused portions of the shader memory with 0, and this code is actually a left over from a previously loaded shader. Since the current JIT does no control flow analysis or compiles based on the entry point, these garbage instructions are still compiled and affect the valid code.

Short term, the solution is as @wwylele identified, but I also want to try a change where the shader buffer is cleared when a new upload begins, to see if that confirms my theory. Long term a new shader JIT based on control flow analysis should also fix this in a more proper way.
