### ISSUE TITLE
Phoenix Wright - Dual Destinies: Framebuffer unsupported

### ISSUE THREAD

**Issue by Barlowe11** [citra-emu/citra#2505]
Tested on d0bf7df. After intro movie game stuck on the black screen with flashing lines.
CPU JIT, shader JIT and hardware render enabled.
![citra](https://cloud.githubusercontent.com/assets/25078501/22464892/186de68a-e7ca-11e6-8574-8f88136a9c2e.png)

Render.OpenGL <Warning> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:483: API OTHER 65536: Framebuffer unsupported. Framebuffer object 3 is unsupported because the depth and stencil attachments are mismatched.

EDIT from xfix comment: It takes a very long time to progress from anime cutscene to seeing anything, due to game emulator failing to render anything 2D in Dual Destinies (lack of support for geoshaders). If you wait a bit (a long time), you will see destroyed courtroom (in 3D), but that takes minutes (due to how slow Dual Destinies emulation is). On console, the period of time where only 2D stuff is rendered is half a minute, which interpolating from 7~10 FPS is 4 minutes.

**Comment by xfix** [comment]
The game is not stuck, it just cannot render the title screen. If you press "New game", intro FMV will appear. And then you will have cutscene without text.

That said, the problem I believe are related to lack of support for geoshaders.

**Comment by Hexagon12** [comment]
Same problem here, running newest nightly build d0bf7df. At the anime cutscene, it repeatedly spammed with Shader JIT errors, but disabling that fix'd it. Now, after the cutscene, only black screen and pressing any buttons or pressing the touch screen won't do anything. The game didn't crash, because the FPS is jumping from 7 to 10. I think that this error is connected to the lack of GS refactoring somehow.

**Comment by xfix** [comment]
It takes a very long time to progress from anime cutscene to seeing anything, due to game emulator failing to render anything 2D in Dual Destinies (lack of support for geoshaders). If you wait a bit (a long time), you will see destroyed courtroom (in 3D), but that takes minutes (due to how slow Dual Destinies emulation is). On console, the period of time where only 2D stuff is rendered is half a minute, which interpolating from 7~10 FPS is 4 minutes.

That said, if you want to play the game, emulator is not yet ready for that, as you won't see any text.

**Comment by FernandoS27** [comment]
Could you post the log please?

This does not seem to be a geoshaders problem. (actualy missing geoshaders does nothing alike tbh).

**Comment by Hexagon12** [comment]
Here you go (waited 1 min into the black screen, too): https://1drv.ms/t/s!AoHubDOu-cNohhSB4oEy80MhFLUA

**Comment by FernandoS27** [comment]
hmn, it seems to be a problem with one of the depth texture formats. Thankfully I saw that game used for cheap on EBGames. I'll try to check it up, if I decide to get a copy.

**Comment by Subv** [comment]
Does this still happen?

**Comment by Dragios** [comment]
It displays the main menu now (no longer black screen) but flashing lines still occur though.
![Main menu](https://user-images.githubusercontent.com/18496868/30780556-1d0d78d8-a140-11e7-9a6f-47a3e386b280.png)

**Comment by wwylele** [comment]
Fixed by #3281
