### ISSUE TITLE
[RFC] Crypto library

### ISSUE THREAD

**Issue by Subv** [citra-emu/citra#254]
A crypto library will be needed for AES support, I propose PolarSSL because it is modular and somewhat lightweight, we could only import the Cipher-AES module.

Requesting suggestions. Please keep in mind that the AES library needs to support 128-bit keys, along with CBC mode and CTR mode. Other key sizes and modes might be needed in the future but for now these are the requirements.

**Comment by vgturtle127** [comment]
There is also OpenAES, Crypto++, GnuTLS, WolfSSL, and obviously OpenSSL.

PolarSSL seems good though. I have heard good things.

I have personally used OpenSSL and GnuTLS and they are pretty good. Obviously everybody remembers Heartbleed, and thinks that automatically means everybody should avoid OpenSSL. The bug is fixed now though, so I see no issues for using it. Some people might be against it though.

Not sure about WolfSSL and OpenAES.

SSLeay is still used by many applications, but I think it is really old and outdated.

**Comment by Subv** [comment]
Resolved as of #2412
