### ISSUE TITLE
citra initialization fail

### ISSUE THREAD

**Issue by gon1313** [citra-emu/citra#2541]
![image](https://cloud.githubusercontent.com/assets/25591610/22658724/733df58c-ecde-11e6-9000-689071985d91.png)

please help me! i tried to open pokemon moon 3ds rom, but doesn't work.

**Comment by RavenHome1** [comment]
open gl 1.1, citra needs at least opengl 3.3, try updating your driver (or maybe even install one since not having aero theme usually means that there is no driver  installed)  and see if that will fix it, other than that you are out of luck, you will need a gpu upgrade.

also next time please use the forums for support, github is for development use only 

https://community.citra-emu.org/

**Comment by mailwl** [comment]
just to mention, some old Intel video cards just don't have drivers for 3.3. hardware just not support it. there is workaround for this, but plaing such old cards is kind of PITA

**Comment by MerryMage** [comment]
This issue tracker is not a help forum. Please post to [the Citra forums](https://community.citra-emu.org/) in the future.
