### ISSUE TITLE
dragon quest 8 glitch on cleared data

### ISSUE THREAD

**Issue by asbel123** [citra-emu/citra#2588]
i load my cleared save data there is a glitch i cant do zoom and godbird its say mysterios force in my way how to go to dragovian path i am stuck i just finsh the game first playthrough i am trying do secert ending.

i am using latest verison citra.

**Comment by wwylele** [comment]
Please provide:
 - a full log
 - a detailed explanation about how to play the game, what is the expected behaviour and the difference from the actual behaviour in citra, so that others that don't play the game can understand the issue. Screenshots and videos are appreciated. 
 - A save file for testing 

Also, please test with CPU JIT on/off and Shader JIT on/off, to see if anything changes

**Comment by asbel123** [comment]
![20170222_204020](https://cloud.githubusercontent.com/assets/4496487/23205890/a85e10c2-f93f-11e6-945b-dbc3e64ff0c8.jpg)

![20170222_203920](https://cloud.githubusercontent.com/assets/4496487/23205930/dea4e48a-f93f-11e6-8f5c-14f733a0d98e.jpg)

i just upload the pitcures now see it for ur self

**Comment by wwylele** [comment]
From [this](https://www.gamefaqs.com/boards/583527-dragon-quest-viii-journey-of-the-cursed-king/65471857) I assume this is how the game works. So this is not an issue in citra.
