### ISSUE TITLE
its impossible to even load the citra application 

### ISSUE THREAD

**Issue by abh6007** [citra-emu/citra#2657]
guys help me please when i try to open citra its says "msvcp140" is missing 
![17795913_1476105822422239_3799764173593604169_n](https://cloud.githubusercontent.com/assets/27020749/24811220/b799a4c8-1be2-11e7-975e-8ac937a5006c.jpg)

then when i downloaded it online the dll file , it says vcruntime140 is missing
![17795913_1476105822422239_3799764173593604169_n1](https://cloud.githubusercontent.com/assets/27020749/24811221/b79aaeb8-1be2-11e7-8ca9-62fd5e55f907.jpg)

later when i added both the files it says the program cant start because api-ms-win-crt-runtime-|1-1-0.dll is missing from your computer.
![17795913_1476105822422239_3799764173593604169_n2](https://cloud.githubusercontent.com/assets/27020749/24811222/b79dbd6a-1be2-11e7-90cf-28c91c03de6a.jpg)
its constantly asking me to reinstall the program 
can anyone please help me ?

**Comment by RavenHome1** [comment]
this is a bug tracker, use forums for support

https://community.citra-emu.org/

to save you the trouble you must download the redistributable package from microsoft.

https://www.microsoft.com/en-us/download/details.aspx?id=48145

also you should never download lone DLL files since they can never be trusted and will most likely never work.
