### ISSUE TITLE
Small enhancement for 60 fps gaming

### ISSUE THREAD

**Issue by ZoraEggs** [citra-emu/citra#2663]
I know this isn't "urgent" but the community for making 60 fps hacks for older games is quite big now. I propose 2 tiny new features which would allow the community to expand to 3ds games too.

1. Limit framerate in options can be selected for 30 or 60 frames. This will change the functionality in: "void FrameLimiter::DoFrameLimiting(u64 current_system_time_us)".

2. Audio tickrate can be assigned a multiplier in the options like so: "static constexpr u64 audio_frame_ticks = 1310252ull * Multiplier; ///< Units: ARM11 cycles".

These two changes alone would let people run their games at 60 game fps, thing's will still move fast in the game, so in the future when there's 'gameshark' code support people could make adjustments to the game itself.

Example of me running oot3D with these edits: https://www.youtube.com/watch?v=WynR7LR2CaM

**Comment by Hexagon12** [comment]
This is a bug tracker, use the forums for support:

https://community.citra-emu.org/

PR's are also welcome, but we avoid hacks.

**Comment by wwylele** [comment]
1. You can always disable the frame limiter to maximize the speed. Note that many games run at 30 fps on real hardware, and tweaking them to 60 fps means that you actually double the running speed. Probably the actual feature you want is a custom speed controller, which is probably not a bad idea, but it shouldn't be discussed from "FPS" view.

2. You will desync the audio, which can potentially cause many issues that we can't (and are not supposed to) fix.

> These two changes alone would let people run their games at 60 game fps, thing's will still move fast in the game, so in the future when there's 'gameshark' code support people could make adjustments to the game itself.

You do realize you are piling up hacks and hacks, which will be an endless nightmare? Not to mention if it is even possible for such cheat code to exist. 

------

I am closing this because this is a wrong starting point to discuss, where the spirit of emulation is not respected. Feel free to propose a new issue/pr about the speed controller in the correct way.
