### ISSUE TITLE
Minimum window size is always 400x480 regardless of layout

### ISSUE THREAD

**Issue by SonofUgly** [citra-emu/citra#2675]
When using the Single Screen or Large Screen layout the minimum window size should change to fit native resolution of those screens. Also should take Swap Screens option into consideration for those layouts. Minimum window sizes for those layouts should be:
Single Screen - 400x240 (320x240 swapped)
Large Screen - 480x240 (420x240 swapped)

Where minimum window size is currently set: https://github.com/citra-emu/citra/blob/master/src/core/frontend/emu_window.h#L185

**Comment by JayFoxRox** [comment]
I don't think there should even be any minimum size.. I've had lots of trouble in the past fitting the graphics debuggers on my display simply because the original rendering window can't be smaller than native resolution.

The rendering resolution should probably be capped to the native resolution to avoid more serious rendering or possibly gameplay affecting issues, but the displayed window size in the layout should be freely changeabgle (but probably we should magnet it to native resolution or add some sort of "Reset size to 3DS resolution" menu button for rendering pixel-perfect)

**Comment by emmauss** [comment]
what about setting the default display screen size for each layout to be what @SonofUgly stated above, as that seems to give optimal view. a reset option will set the display size to the defaults. users can resize it to any size they want (no min size).
