### ISSUE TITLE
GPU_BLEND_MAX behaves differently than hardware

### ISSUE THREAD

**Issue by zetaPRIME** [citra-emu/citra#2684]
Versions tested: Nightly HEAD-06d4654, Edge HEAD-e0968c0

In updating libstarlight to citro3d-next, I came across a bug where rendertargets weren't properly clearing before the first time they were drawn to; as a workaround, I have it draw a quad of the clear color (transparent by default) on first bind in a flat replace/knockout blend mode. This works exactly as it should on hardware, but on Citra it has no visible effect. Suspect that perhaps it doesn't like the blend mode?

Where this draw is triggered: https://github.com/zetaPRIME/libstarlight/blob/5577b5a6a83c57fac2a88a9ba8e107f1ba8674ee/libstarlight/source/starlight/gfx/RenderCore.cpp#L321

Where the blend mode in question is defined: https://github.com/zetaPRIME/libstarlight/blob/5577b5a6a83c57fac2a88a9ba8e107f1ba8674ee/libstarlight/source/starlight/gfx/RenderCore.cpp#L162

3DSX demonstrating issue: [starlight-testbed.zip](https://github.com/citra-emu/citra/files/972821/starlight-testbed.zip) (first screen doesn't have a visible anomaly due to memory starting clear; click the button to see issue)

**Comment by yuriks** [comment]
Issue is most likely [this](https://www.khronos.org/opengl/wiki/Blending#Blend_Equations):

> `GL_MAX`: The output color is the component-wise maximum value of the source and dest colors. The parameters s and d are ignored for this equation.

The application sets a blend mode of MAX with src factor ONE and dst factor ZERO. Since GL ignores the factors this turns into `max(src, dst)` instead of `max(1 * src, 0)` as intended. Presumably the PICA actually respects those factors, but this will need testing. (Will be a real fun one to emulate in the GL backend if that's the case...)

In the meantime you can fix the demo in Citra by using `GPU_BLEND_ADD` instead of `GPU_BLEND_MAX`, or by disabling blending and using `GPU_LOGICOP_SET`.

**Comment by Subv** [comment]
As per [this test](https://gist.github.com/Subv/a22bf6f9796e7e1c967c14c2c365f3b4), the PICA does indeed respect the blend factors with both MIN and MAX
