### ISSUE TITLE
ERROR PLEASE HELP

### ISSUE THREAD

**Issue by davidmx28** [citra-emu/citra#2685]
i can play super mario maker on mac

The Screen of Citra Emulator
![captura de pantalla 2017-05-03 a la s 13 27 56](https://cloud.githubusercontent.com/assets/28356520/25670783/2c908c6c-3004-11e7-94cf-7fee176dae1f.png)

The Terminal
![captura de pantalla 2017-05-03 a la s 13 28 08](https://cloud.githubusercontent.com/assets/28356520/25670797/3b505f7a-3004-11e7-8d9b-0673996c4826.png)

**Comment by wwylele** [comment]
Mostly like lack of mii or system archive
Note that Mario maker is still not playable even if mii is provided. (This issue is already filed)

----

This is the bug tracker for developers of Citra. 

Please Use our [Citra Forum](https://community.citra-emu.org/) for questions and support instead. Note that you won't get any support if you
 - use any kinds of non-official build, or
 - use pirated copies of the games, 3DS BIOS files or any copyrighted content.

If you really want to report an issue which is not your personal problem but bugs in Citra, please review [guidelines for contributing](https://github.com/citra-emu/citra/blob/master/CONTRIBUTING.md) carefully, and follow the instructions there.

Closed as invalid
