### ISSUE TITLE
LOG_TRACE statements should be verified during CI builds

### ISSUE THREAD

**Issue by yuriks** [citra-emu/citra#2698]
Right now it happens semi-often that a LOG_TRACE statement has its parameters broken somehow and this gets checked in because they're not built in Release builds. Since developers rarely use Debug builds due to how slow they are, we should check this in CI somehow. There are several approaches to this:

1. Make Travis CI Linux (which is generally the fastest to build) also do Debug builds, using Travis' matrix feature. I'm not sure how easy this is to implement but I don't imagine it's very hard. It might potentially increase the flakiness of the builds or make them take more time, decreasing agility.

2. Remove LOG_TRACE from very hot loops, and then enable it as a regular conditional statement. This decreases the amount of magic in the build and makes these problems be detected during regular development. However, the LOG_TRACE statements are occasionally useful for debugging issues or collecting data for simulations/benchmarks.

3. Add a dedicated defined symbols to enable LOG_TRACE, and enable it for CI builds. This could be a good option since afaik we don't currently distribute the presubmit builds anyway, so their runtime performance doesn't matter.

Does the new logging framework (#2646) offer anything to address this that we might be able to simply wait for, @jroweboy?

Personally, alternative 3 seems like the best for me.

**Comment by jroweboy** [comment]
RE option 1: Both travis and appveyor support matrix builds, and both of them only build one at a time for open source applications. So if we use that feature, then it will increase build time.

RE option 3: CI environments (both travis and appveyor) have a different flag for push to master and pull request. We can use this enable `LOG_TRACE` for builds that are checking pull requests while still keeping them out of release builds.

I'm fine for both option 1 and 3. I like option 1 because it seems weird to have an option to build debug builds, without actually testing the build. But I also like option 3 because it won't increase build times while still testing LOG_TRACE statements. If I had to choose, I'd probably go with option 1 and just deal with the increased build times.

If we come to a consensus about which option to choose, I can add it to the logging rewrite task

**Comment by vvanelslande** [comment]
Fixed by #4602
