### ISSUE TITLE
Graphical glitch artifact appear during loading the next rom

### ISSUE THREAD

**Issue by Dragios** [citra-emu/citra#2715]
![Glitchy Artifact](https://cloud.githubusercontent.com/assets/18496868/26280232/143213c8-3dfd-11e7-8731-8a797f131a13.png)
This happens when you try to load a game when the previous one is still running. Before this it just shows a blank screen. With #2687 merged, you can see a flashback of previous game artifact (various graphical glitches depending on the currently loaded rom) shown upon loading the next rom.

This commit changes the behavior f18d454eb6a6912b93664ee43b7f377a9ddd0215.

*Note: It does not affect the actual gameplay*

**Comment by yuriks** [comment]
I noticed this while doing the change and thought it was a neat "easter egg" of sorts. The same thing happens on the 3DS, but it's hidden by either disabling the LCD output or by the APT handshake ("Nintendo 3DS" splash).

I don't think there's anything to be done here but the fix is to clear https://github.com/citra-emu/citra/blob/master/src/core/hle/kernel/memory.cpp#L98 during startup.

**Comment by Dragios** [comment]
I do not see this issue present in recent Citra version. I guess this can be close?
