### ISSUE TITLE
2 Service.FS Error at the first ConfigDialog launch

### ISSUE THREAD

**Issue by BastienIstil** [citra-emu/citra#2759]
Tested on windows 
Tested on Version https://github.com/citra-emu/citra/commit/160df440bcf4783059e1e6ea375b81d6d25aa448

When the folder %APPDATA%\Citra is empty, there are 2 errors at the first ConfigDialog launch.

This issue is produced by LoadConfigNANDSaveFile() in cfg.cpp at line 534.

The first error is triggered because we try to open an non-existent config file.
After that we launch the function FormatConfig() which try to delete the file before generating it and raise the second error.

It would be good to implement functions which check if the file exist before anything else.

**Comment by wwylele** [comment]
> It would be good to implement functions which check if the file exist before anything else.

We already implement file/directory state check in FS implementation, which is also the reason we just do direct open/delete outside, because we know all error state is properly handled inside. 

The error log doesn't necessarily means something goes wrong, it just reports an uncommon state, helping us understanding what happens every time, which _potentially_ indicates a bug (which doesn't apply to this case because we know where it comes). We might lower the log level of these FS logs in the future when we are much confident with the implementation

**Comment by BastienIstil** [comment]
Ah okay, I found that strange that nobody has made that issue ! 
I close it.
