### ISSUE TITLE
Bad performance in Float<M,E> multiplication

### ISSUE THREAD

**Issue by huwpascoe** [citra-emu/citra#2939]
This is used all over the place, especially with vector math.

https://godbolt.org/g/WjPcor

Control (float * float):
```mulss xmm0, xmm1```

Amended (return Float<M, E>::FromFloat32(ToFloat32() * flt.ToFloat32())):
```mulss xmm0, xmm1```

Implementation (// PICA gives 0 instead of NaN when multiplying by inf):
```
        ucomiss xmm1, xmm1
        jp      .L9
        pxor    xmm2, xmm2
        mov     edx, 1
        ucomiss xmm0, xmm2
        setp    al
        cmovne  eax, edx
        test    al, al
        jne     .L9
.L3:
        movaps  xmm0, xmm2
        ret
.L9:
        ucomiss xmm0, xmm0
        jp      .L10
        pxor    xmm2, xmm2
        mov     edx, 1
        ucomiss xmm1, xmm2
        setp    al
        cmovne  eax, edx
        test    al, al
        je      .L3
.L10:
        mulss   xmm1, xmm0
        movaps  xmm2, xmm1
        movaps  xmm0, xmm2
        ret
```

**Comment by Subv** [comment]
This version uses (almost) the same code as the MUL instruction in our shader jit, and the generated code looks much better: https://godbolt.org/g/RTv3fn

```cpp
Float<M, E> operator*(const Float<M, E>& flt) const {
		float result = value * flt.ToFloat32();

        if (!std::isnan(value) && !std::isnan(flt.ToFloat32()))
			if (std::isnan(result))
	        	result = 0.f;

        return Float<M, E>::FromFloat32(result);
	}
````

**Comment by Subv** [comment]
I wrote a little program in Z3 to prove that the proposed code is functionally equivalent to the old one for the desired cases:

https://gist.github.com/Subv/1cbab099c017df47e635112e26cadee9

This is the result:

```
Previous result: NaN
New result: +0.0
unsat
```

These results show that with the constraints used (no -0.0f in the inputs and no -0.0f in the outputs), the new code behaves the same as the old one.

If we relax the constraints a little, we see that the old code was actually giving NaN instead of 0 for the `-0.0f * +inf` case, whereas the proposed one doesn't exhibit this behavior.

Relaxing the output constraints, we get that for `[y = +0.0, x = -0.000244140625*(2**-126)]`, the old output is `+0.0` and the new output is `-0.0`. Should we account for this, and sanitize all zeros to positive zero? (this would come as a performance penalty).

**Comment by RavenHome1** [comment]
close this?
