### ISSUE TITLE
Citra crashes when loading updated roms.

### ISSUE THREAD

**Issue by Soban44444** [citra-emu/citra#2956]
On Citra Head-d881dee updated roms don't work.

**Comment by B3n30** [comment]
Can you please add more information: How did you acquire the updated rom? Full log? Explain what "Doesn't work" mean...

**Comment by Soban44444** [comment]
I dumped the rom my self.but when i install the updates in them its says the rom is encrypted.

**Comment by Soban44444** [comment]
it worked on previous builds

**Comment by wwylele** [comment]
This is caused by #2927. The essential change is that now we check `exheader_header.system_info.jump_id != ncch_header.program_id` for ROM encryption instead of `exheader_header.arm11_system_local_caps.program_id != ncch_header.program_id`.

Here is a simple summary about what values are in these fields for all kinds of ROMs:

|ROM type| `ncch_header.program_id` | `exheader_header.arm11_system_local_caps.program_id` | `exheader_header.system_info.jump_id`| 
|---|---|---|---|
|Main Game ROM|Main ID|Main ID|Main ID|
|Update ROM|Update ID|Main ID|Update ID|
|"Patched" Game ROM|Main ID|Main ID|Update ID|

As can be seen, the patched ROM fails the new encryption checker.

However, this is due to the fact that the patched ROM itself is reconstructed. It contains an exheader inherited from the update ROM, which doesn't match the hash and signature and isn't supposed to be in the main ROM. We have never formally supported patched ROM, and with the recent update ROM support added, we will likely never supports it. So the solution is to use the original main ROM and the original update ROM separately and put the update ROM to the required location (wiki coming soon!).
