### ISSUE TITLE
Pokemon X and Y is not working 

### ISSUE THREAD

**Issue by BarrelFrog** [citra-emu/citra#2957]
So I've been trying for ages now to get my Pokemon X work on my citra emulator but it's not working properly. As soon as I'm done creating my guy I just get black screened. I'm using the Wii U usb helper as well. It's nothing wrong on the emulator or anything because I can play Pokemon Alpha Sapphire. Please fix this

**Comment by jroweboy** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/

Also there is no support for pirated games at all. Don't bother asking on the forum for help since you'll just get your post removed there as well. Pokemon X/Y don't work anyway.

**Comment by BarrelFrog** [comment]
aight thanks :(
