### ISSUE TITLE
Fatal Error in Super Street Fighter IV 3D Edition 

### ISSUE THREAD

**Issue by Luffykun007** [citra-emu/citra#2959]
I'm having a fatal error while trying to start the Super Street Fighter IV 3D Edition game on Citra, attached error log.

![capturar](https://user-images.githubusercontent.com/26087621/30840444-afbeaa90-a24d-11e7-95ba-4c0b9b09c427.JPG)

[Super Street Fighter IV 3D Edition.zip](https://github.com/citra-emu/citra/files/1331730/Super.Street.Fighter.IV.3D.Edition.zip)

**Comment by Subv** [comment]
That log is pretty much useless, please enable the logging and upload a more complete log.

**Comment by Luffykun007** [comment]
and how do I do this to have the complete register?

**Comment by Leo626** [comment]
You've set your log filter to `Critical`. Change it back to `Info` so the log will be more complete.

**Comment by Luffykun007** [comment]
@Subv new Log 

[Super Street Fighter IV 3D Edition.zip](https://github.com/citra-emu/citra/files/1331693/Super.Street.Fighter.IV.3D.Edition.zip)

**Comment by Luffykun007** [comment]
@Leo626 but where I change this option of Log?

**Comment by Leo626** [comment]
Open Run (Windows key + R) and enter `%appdata%/citra/config/qt-config.ini`. Change the log filer and save.

**Comment by Luffykun007** [comment]
Yes I did but what do I need to change in the log file now?

**Comment by Luffykun007** [comment]
@Subv i have a new log now I hope it's correct ,thanks for help @Leo626

[Super Street Fighter IV 3D Edition.zip](https://github.com/citra-emu/citra/files/1331775/Super.Street.Fighter.IV.3D.Edition.zip)

**Comment by Subv** [comment]
This game is calling the old nwm::UDS Initialize function with command header `0x000102C2`, whereas 3dbrew lists that command as `0x00010442`, I suppose 3dbrew is wrong, then.

That's the cause of the crash, Initialize is supposed to return an event handle, but the application is receiving garbage instead.

**Comment by TylerBarkley** [comment]
I'll handle this.

**Comment by Luffykun007** [comment]
yet I have the same error.

![capturar](https://user-images.githubusercontent.com/26087621/31325164-7a30c640-ac90-11e7-9872-9e8e344ef1e7.JPG)

New Log: [Super Street Fighter IV 3D Edition.zip](https://github.com/citra-emu/citra/files/1367503/Super.Street.Fighter.IV.3D.Edition.zip)

**Comment by Dragios** [comment]
Before:
`Service <Error> core/hle/service/service.cpp:HandleSyncRequest:95: unknown / unimplemented function `'**0x000102C2**'`: port=nwm::UDS, cmd_buff[1]=0x14000, cmd_buff[2]=0x22F3AD7, cmd_buff[3]=0x6FF40000, `**cmd_buff[4]=0x6F0052**, **cmd_buff[5]=0x61006E**, **cmd_buff[6]=0x64006C**, **cmd_buff[7]=0x6F**, `cmd_buff[8]=0x0, cmd_buff[9]=0x0, cmd_buff[10]=0x82067F0, cmd_buff[11]=0x3D9DCC, cmd_buff[12]=0x0, `**cmd_buff[13]=0x150049**

After:
`Service <Error> core/hle/service/service.cpp:HandleSyncRequest:95: unknown / unimplemented function `'**Initialize (deprecated)**'`: port=nwm::UDS, cmd_buff[1]=0x14000, cmd_buff[2]=0x22F3AD7, cmd_buff[3]=0x6FF40000, `**cmd_buff[4]=0x690043**, **cmd_buff[5]=0x720074**, **cmd_buff[6]=0x61**, **cmd_buff[7]=0x0**, `cmd_buff[8]=0x0, cmd_buff[9]=0x0, cmd_buff[10]=0x82067F0, cmd_buff[11]=0x3D9DCC, cmd_buff[12]=0x0, `**cmd_buff[13]=0x15006B**

I'm not sure if these change of addresses affects the outcome but I have highlighted it for easier comparison. Regarding the crash, it might be due to the function is not implemented yet.
To implement or stubbed those function is out of my PR scope.

Ping @Subv for further investigation.

**Comment by wwylele** [comment]
Just want to clarify, #3002 is not expected to "fix" this at all, because, as you can see, the function is not linked to any handler but `nullptr`. A proper fix would be to implement the function, or to link it to an existing function.

**Comment by Luffykun007** [comment]
but the PR clearly says fix issue # 2959

**Comment by Dragios** [comment]
That was what I thought initially. I will change the PR description.

**Comment by adityaruplaha** [comment]
#2957

**Comment by benderscruffy** [comment]
nightly HEAD-a66e458
still happens
[Debug log.zip](https://github.com/citra-emu/citra/files/1605856/Debug.log.zip)

**Comment by adityaruplaha** [comment]
Any new stuff on this?

**Comment by Luffykun007** [comment]
Everything in the same here last tested on canary 347

New Log: [Super Street Figther IV 3D Edition.zip](https://github.com/citra-emu/citra/files/1692340/Super.Street.Figther.IV.3D.Edition.zip)

**Comment by ivanmestre** [comment]
As a workaround you can disable Fight Requests when selecting Arcade and it will work.

**Comment by benderscruffy** [comment]
still happens in the latest nightly
[citra_log.zip](https://github.com/citra-emu/citra/files/2729303/citra_log.zip)

and here is a log with disable fight requests so that it can go in game
![super](https://user-images.githubusercontent.com/2696404/50721940-9c377e00-1102-11e9-8859-f6826d191c31.PNG)
[citra_log.zip](https://github.com/citra-emu/citra/files/2729312/citra_log.zip)

Render.OpenGL <Critical> video_core/renderer_opengl/gl_shader_gen.cpp:GenerateFragmentShader:1550: Unimplemented gas mode

**Comment by brujo5** [comment]
still crashes after the VS screen.

**Comment by benderscruffy** [comment]
using the latest nightly goes ingame
no problems so far
can be closed
