### ISSUE TITLE
Harvest Moon 3ds: A New Beginning Panic/Break

### ISSUE THREAD

**Issue by Jelledot** [citra-emu/citra#2995]
Froze during character name selection.

https://prnt.sc/gu1il0

http://prntscr.com/gu2op5

http://prntscr.com/gu2r28

Build: latest nightly.

Anyone perhaps knowing a way on how to fix this issue?

**Comment by esQmo** [comment]
Seems like an old version and why did you download from a third-party hosting site?

**Comment by einstein95** [comment]
Unnoficial builds are not supported. Try on latest nightly.

**Comment by Jelledot** [comment]
On latest nightly it doesn't work - reason why I used the version that I send is because if you regularly try to enter a name with this game, it doesn't work at all, this being a workaround and shown it has worked for other people, I'd think it'd work for me too. If I do it on Nightly version I get this: http://prntscr.com/gu2op5

**Comment by einstein95** [comment]
Have you tried dumping a save from a 3DS?

**Comment by B3n30** [comment]
Since this is an issue tracker and not a support forum, please ask for support in our [forums](https://community.citra-emu.org/) or on [discord](https://discord.gg/9jgD2y4). For a real issue please follow the guides on how to fill the issue report (full log, steps on how to reproduce, version ...).

But also consider that we can't give support for unoffical builds, since we don't know the code, compiler settings, and other conditions. We can only give support and track issues related to our official releases
