### ISSUE TITLE
Change links color in the Web tab while using Dark Theme

### ISSUE THREAD

**Issue by esQmo** [citra-emu/citra#2999]
As you can see in the screenshot below, the blue color for links makes it harder to read what link it is. Please change the color to something, say white may be?

![screenshot_1](https://user-images.githubusercontent.com/10319812/31320409-fe24d330-ac6b-11e7-8162-fbd68516ba1d.png)

**Comment by jroweboy** [comment]
This can be fixed by changing the palette in https://github.com/citra-emu/citra/blob/master/dist/qt_themes/qdarkstyle/style.qss

http://doc.qt.io/qt-5/qpalette.html#ColorRole-enum

http://doc.qt.io/qt-5/stylesheet-reference.html

**Comment by ncbaihly** [comment]
So I started looking at this issue for doing a potential first time PR. I don't have much experience with Qt. I was mostly trying things like the following in the style.qss file:

`QLabel:link { color: white; }`

[According to this page](https://doc.qt.io/qt-5/stylesheet-syntax.html#select) on Qt stylesheets in the selector section it says it should support all the selectors defined in CSS2, which would include the link selector. But for some reason that doesn't seem to work, I also tried changing the text color without the selector. 

In addition to that it seems like their might be some issue with trying to set link text color from stylesheets at least according to this [Stackoverflow post.](https://stackoverflow.com/questions/13416183/qt-stylesheet-how-to-set-color-of-qpalettelink-and-qplattelinkvisited#13418805)

I looked into the suggestions by @jroweboy , but I couldn't get anything to work after looking some stuff up. Could just be my lack of experience with Qt. 

I did find a solution that worked but I'm not sure if it's very good practice since it's in-line styling in the configure_web.cpp file.  

`ui->web_signup_link->setText(tr("<a style=\"color:white;\" href='https://services.citra-emu.org/'>Sign up</a>"));`

Attached is the result. (Also the learn more link isn't underlined even with my changes, I'm running Ubuntu 16.04 LTS, not sure if that might be an issue). 
![citra_web_config](https://user-images.githubusercontent.com/3604022/31514972-986684f0-af61-11e7-8c30-cd0f7988c4bc.png)

On another note, maybe links should be a light blue or something to differentiate it from other text on the screen?

**Comment by danzel** [comment]
I'm not sure if your css is right (I've never done css in QT before).
Maybe try these:
`QLabel a { color: white; }`
`a { color: white; }`
`QLabel { color: white }`

Although from the link you found, it might need to be done inline as you say.
Hope that helps :)

**Comment by ncbaihly** [comment]
@danzel Those are good suggestions!

Unfortunately, I tried all of those and none of them worked. :( Only thing I've found to work so far is the inline. 

Thanks for the input!

**Comment by adityaruplaha** [comment]
Changed this in #3014 commit 2 to golden.

**Comment by adityaruplaha** [comment]
The only way to do this is inline. If the pallets are changed, the hyperlinks' default color will simply override it. I tried in #3014, but it wasn't accepted.

**Comment by adityaruplaha** [comment]
This will have to wait until a style handler is implemented.

**Comment by BynariStar** [comment]
Fixed by #3769
