### ISSUE TITLE
Poochy & Yoshi's Wooly World - Crash with Intel GPU

### ISSUE THREAD

**Issue by valentinvanelslande** [citra-emu/citra#3055]
Commit: edfc8d1
Start the game, configure the game and on the yoshis scene citra crashes.
Specs: i5-7200U, Intel HD Graphics 620, Windows 10 15063
[Log](https://raw.githubusercontent.com/acnleditor2/citra-logs/master/Poochy%20%26%20Yoshi's%20Wooly%20World.txt)

**Comment by acnleditor2** [comment]
workaround: disable hw renderer in level selection screen.

**Comment by RavenHome1** [comment]
what is up with this massive regression, most of these games worked greatly for so long

**Comment by Hexagon12** [comment]
People on the Discord reported that this game worked before just fine, so this issue is a regression.

Could you please find out on what version it first started to crash?

**Comment by Schplee** [comment]
In Nightly - `79852d3`, the game doesn't crash. Followed your steps: Created new save, configured the settings, and successfully finished the intro cut scene and started a level.

**Comment by wwylele** [comment]
System: Ubuntu
Commit: 79852d3 (compiled myself using GCC 7.2)
Game: Poochy & Yoshi's Wooly World (JAP) (00040000 001a3200)
Result: Failed to reproduce

More specifically, I can go in game with hw renderer without any issue. In the log, I don't get those craze log entries that indicates broken gpu command list such as
 - `Invalid VS program offset 512`, 
 - `Unhandled instruction: 0x20 (0x80000000)`,
 - `Unknown source op 8`, 
 - `Commandlist tried to write to invalid register`

Here are some possibilities I came up with:
 - Your ROM is somehow broken, or at least we are not using the same version of the game
 - A log entry that can be seen in both of your and my log: `Emulated program broke execution! Break reason: PANIC`, which might be caused by unimplemented cecd functions, probably leads the program execution into undefined state and results in inconsistent behaviour

**Comment by acnleditor2** [comment]
using jpn version. log updated.

**Comment by acnleditor2** [comment]
@wwylele no broken graphics in my fork... and with your cec branch not fixed

**Comment by acnleditor2** [comment]
@Schplee crash.

**Comment by acnleditor2** [comment]
in eur version broken graphics on all citras

**Comment by Jhon591** [comment]
You're braking your own build by adding to much at once.

**Comment by wwylele** [comment]
> and with your cec branch not fixed

Just for others seeing this, my cec branch is still WIP and I don't expect it to fix anything

**Comment by mailwl** [comment]
it fix some games, so it's good enough

**Comment by acnleditor2** [comment]
@wwylele tomodachi life

**Comment by acnleditor2** [comment]
`[  33.260669] Render.OpenGL <Error> video_core/renderer_opengl/gl_shader_gen.cpp:SampleTexture:221: Using Texture3 without enabling it`

**Comment by acnleditor2** [comment]
intel gpu issue?

**Comment by valentinvanelslande** [comment]
redumped (eur) and now crashes here: 
![crash](https://user-images.githubusercontent.com/22228082/34214489-41f0b70c-e568-11e7-8f63-27d72ef55c74.PNG)

**Comment by valentinvanelslande** [comment]
works in canary
![works](https://user-images.githubusercontent.com/22228082/34214547-723464ea-e568-11e7-869a-174611f97a41.PNG)

**Comment by benderscruffy** [comment]
using the latest nightly it goes ingame for myself
no problems so far
![poochy](https://user-images.githubusercontent.com/2696404/34293023-0749a974-e73e-11e7-9030-65d23998ae03.PNG)

**Comment by valentinvanelslande** [comment]
@benderscruffy what, try with igpu

**Comment by benderscruffy** [comment]
dont have an Intel GPU
might be a problem with your drivers

**Comment by valentinvanelslande** [comment]
a friend with Intel and Nvidia tried the game and crashed with Intel and not with Nvidia

**Comment by wwylele** [comment]
Though I don't really believe that #3281 fixes this, but close anyway as the issue is suspicious from the beginning.

**Comment by Mohamed-Slimane** [comment]
4-7 crash fix
https://youtu.be/4-Hvvtr3YbE
