### ISSUE TITLE
multiplayer fix

### ISSUE THREAD

**Issue by malikkhan8121** [citra-emu/citra#3142]
please fix multiplayer when i type my user name and token it give invaliid

**Comment by jroweboy** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/

Also, you don't need a username and token for anything but hosting a public room. you can still join an existing room and host an unlisted room without a username and token. And the issue should be fixed with #3141

**Comment by malikkhan8121** [comment]
i need your help what should i do help me please

**Comment by gusbemacbe** [comment]
@malikkhan8121, do not you read attentively the advice of jroweboy that Github is for developers, or are you a child?
