### ISSUE TITLE
Change Internal Resolution to 0.5x or Custom

### ISSUE THREAD

**Issue by Wiifan** [citra-emu/citra#3282]
Hi, Citra runs a little slow when plays 3d games, by my pc Specs ...
exist a way to include in the engine the 0.5x internal resolution or User Custom?

this may be useful for users with a lower pc
thanks!

**Comment by BreadFish64** [comment]
I'm afraid .5x internal resolution would not make your games any faster. Citra is severely CPU limited so resolution has little effect on performance. In fact, due to some technicalities it may even be slower than native. Side note, #3281 locks all resolutions to whole numbers because non-integer resolutions cause problems anyway.

**Comment by jroweboy** [comment]
Yes you can edit the number in the ini to change it to whatever arbitrary resolution that you want, but as @BreadFish64 mentioned, it probably won't speed up your game, and fractional resolutions will be removed after #3281

**Comment by Wiifan** [comment]
thanks guy's for the answers ;)
