### ISSUE TITLE
MSI Afterburner FPS Drop

### ISSUE THREAD

**Issue by Nandale** [citra-emu/citra#3300]
Hey all, **Citra doesn't seem to work with MSI Afterburner** running. I only tested it for Runes Factory 4, but should be the same for others as well. **Just close MSI A and fps goes up from unbelievable 5 fps to fucking 312 fps**... please at least mention this bug somewhere, I literally went an hour looking the first cutscene on 5 fps. Not funny, guys, not funny.

**Comment by RavenHome1** [comment]
the issue is not caused by the afterburner but the Rivatuner Statistics Server that is a part of MSI and causes the weird openGL hookups. afterburner by itself is just ah ardware monitor and overclocking utility.

issue about it is already included in the [FAQ](https://citra-emu.org/wiki/faq/)on the forums and many other countless threads that was opened up on the forums,  take the time to search the threads and read the FAQ before posting anything next time.

Github is for developers use and bug tracking, post any further questions on the forums 
https://community.citra-emu.org/

**Comment by Hexagon12** [comment]
This is a bug tracker and not a support forum. In addition, this issue has nothing to do with Citra.

Requesting to close.
