### ISSUE TITLE
Pokemon Omega Ruby And Alpha Sapphire USA region problem

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3356]
using HEAD-8002579
if you choose the region auto select the language comes up japanese
if you choose usa the language comes up properly
[Debug log.zip](https://github.com/citra-emu/citra/files/1614029/Debug.log.zip)

**Comment by wwylele** [comment]
I am afraid this is almost impossible to fix.  IIRC As last time I checked, all eshop version of Pokemon AS, despite in different regions, has exactly the same content and are region-free. There is no way for citra to tell whether the ROM was originally dumped from japanese region or USA region. Currently the auto region selector default to japanese just because it is the first code (0) in the region list. We can change the default to USA, but the other day a Japanses will come to report the same problem.

**Comment by benderscruffy** [comment]
ok no problem
should i close this ???
