### ISSUE TITLE
Hermes (homebrew) fails to boot

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3386]
http://www.retroguru.com/hermes/
download
http://www.retroguru.com/hermes/hermes-v.latest-nintendo3ds.zip

**Comment by FearlessTobi** [comment]
Log: https://pastebin.com/AviicK0T 

The application tries to close itself.

**Comment by wwylele** [comment]
```
Non-existing file C:\Users\Tobias\AppData\Roaming/Citra/sdmc/3ds/dspfirm.cdc can't be open without mode create.
```
you need to place a DSP firm in the path. This is also a requirement on real 3DS, however it is usually already there because in the 3ds hacking guide it is a required setup step. Note that since Citra does DSP HLE doesn't actually use the firm, one can just place an empty file in this path to make it work.

Please test it again with the file.

**Comment by FearlessTobi** [comment]
It works now, with an empty file in place. This can be closed too.

**Comment by Fewnity** [comment]
Can we add to citra the possibility to create dspfirm.cdc at the installation?
