### ISSUE TITLE
Project X Zone crashes on canary 303 and higher

### ISSUE THREAD

**Issue by YabenoHkmr** [citra-emu/citra#3390]
Crashes happens when using some skills, attacks or items. Tested on Nightly 521 and the game can play fine without crashing but suffer severe FPS drop during attack animations. Canary 302 can play the game without any crash and rarely have slight FPS drop.
![2018-01-15_232504](https://user-images.githubusercontent.com/35461490/34952261-b9f5e28e-fa4b-11e7-94c1-9b3b1cd1caa8.jpg)

**Comment by MerryMage** [comment]
#3281.

**Comment by YabenoHkmr** [comment]
Just gonna report that Canary 326 no longer crash but face the same severe FPS drop with Nightly. I guess you guys reverted the change? Well, if anyone want to play this game, the best build is Canary 302 for now.

**Comment by jroweboy** [comment]
No, the change hasn't been reverted, 326 is just a bugged release since we are migrating to a new build infrastructure for canary, the change for #3281 isn't on that release at all. 326 is the same as the latest nightly. Try testing 325 to see if it has the issue, and if its broken in 325, paste a screen shot of the crash (like you did earlier) in #3281 instead so we can get it fixed.

**Comment by benderscruffy** [comment]
this can be closed  ???
