### ISSUE TITLE
Poor audio quality when time stretching audio

### ISSUE THREAD

**Issue by SonofUgly** [citra-emu/citra#3416]
This isn't game dependent, or only happens with certain audio AFAIK.
Using Windows 8.1 and Realtek HD audio drivers with onboard audio.

Here's a comparison of OoT3D's title screen running fullspeed, the audio is very choppy with stretching on:
[Audio stretching off](https://my.mixtape.moe/vbffnm.mp3)
[Audio stretching on](https://my.mixtape.moe/ceyxjt.mp3)

And while stretching is an improvement over no stretching while running below fullspeed, it could be better:
[OoT3D's title running at 50% speed with audio stretching](https://my.mixtape.moe/ggkvul.mp3)
['Audio stretching off' sample from above ran through Audacity's Time Scale effect at 50% speed](https://my.mixtape.moe/vzywsb.mp3)

**Comment by MerryMage** [comment]
Audacity uses [subband sinusoidal modeling synthesis](http://sbsms.sourceforge.net/) (basically a fancy vocoder) for it's time scale effect. 

The advantages of such a system are:

1. Sounds nicer when you have a known **fixed** stretching ratio.

The disadvantages of using such a system are:

1. Much more computationally expensive.
2. Sounds absolutely terrible when the ratio is adjusted frame-by-frame in real time.

Therefore the choice was to go with Soundtouch because it sounds better.

**Comment by danilaml** [comment]
Hm, doesn't explain why it sounds so bat when the game runs 100% with stretching enabled. I've noticed it too in professor layton vs. phoenix wright, title screen (even the intro logo movies). The audio is "trembling" with stretching enabled even if the game is 100% speed 99% of the time. It feels like once the audio is "stretched" for whatever reason (dropped frame on a scene change), it never fully recovers. Disabled stretching and it sounds normal, although there is an occasional artifact every minute or so.

**Comment by GPUCode** [comment]
Fixed by https://github.com/citra-emu/citra/pull/7081
