### ISSUE TITLE
[Feature request] Hold down a key to remove speed limit.

### ISSUE THREAD

**Issue by EddyHg80** [citra-emu/citra#3417]
Hi, has the title says, add a key that when pressed sets the speed limit from 100% to the limit you set in the config.
Pretty much like the GBA emulators with the space bar. 
I don't know if this is possible, but I thought it could be a handy thing to add :)

EDIT:
This is what I have in mind

![image](https://user-images.githubusercontent.com/9092453/36535787-18a80e82-17cb-11e8-8ece-e7b569e66a4a.png)

-if the first limiter is unchecked, the second option is disabled.
-if the second limiter is unchecked, the boost button simply unlimits the framerate

EDIT: design by B3n30 and jroweboy
Have a default speed limit of 100%. No checkbox to disable/enable that limit
Then have a speed modifier value in the config that you can set to values like 0.5, 1.5, 2, 2.5, 3, and unlimited. My suggestion would be to have that as a combo box in the ui but still have the ability to edit the value to any thing you want in the ini.

**Comment by adityaruplaha** [comment]
I'll try to implement this sometime (maybe).

**Comment by adityaruplaha** [comment]
Update: I'm working on this. See adityaruplaha:disable-frame-limit-hotkey

**Comment by dolent** [comment]
I made a few minor modifications to add a hotkey called remove speed limit to do this. Would this work for you @EddyHg80

**Comment by EddyHg80** [comment]
@dolent Yeah I think this is great! 
You can already set the maximum speed in the settings, so it would make sense if the emulator wouldn't go further that when the button is pushed ;)

**Comment by MerryMage** [comment]
> You can already set the maximum speed in the settings, so it would make sense if the emulator wouldn't exceed that limit even when the button is pushed ;)

That doesn't really make sense, since the emulator is already not exceeding that limit normally.

**Comment by EddyHg80** [comment]
@MerryMage oh right, sorry I didn't remember correctly.
Let's stick to what I sain in the OP, 100% all the time, when you press the button go up the speed limit you set in the config.
And maybe add an option to have the system as is right now, where you just set the limit.

**Comment by EddyHg80** [comment]
So, in order to avoid any misunderstandings, this is what I have in mind

![image](https://user-images.githubusercontent.com/9092453/36535673-bdabc53c-17ca-11e8-8e34-bcab7c48da5a.png)

-if the first limiter is unchecked, the second option is disabled.
-if the second limiter is unchecked, the boost button simply unlimits the framerate

I'm sorry for the confusion I made yesterday.

**Comment by adityaruplaha** [comment]
You mean 2 separate frame limits? One normal, & another while a button is pressed?

**Comment by EddyHg80** [comment]
Yeah, pretty much. On other emulators you can have a limit even when you press the speed button (you can set x2, x3 ecc) which is basically a higher limit for the framerate.

**Comment by kirbyblox** [comment]
Is anyone working on this? I might give it a go.

**Comment by adityaruplaha** [comment]
Nope. Good luck. Shouldn't be too hard, as the speed limit percentage is already in place.

**Comment by adityaruplaha** [comment]
Also @EddyHg80 change the title to "change/remove speed limit".

**Comment by BreadFish64** [comment]
@adityaruplaha the title is fine as is

**Comment by Eduard-Dumitrescu** [comment]
Is anyone still working at this/ has a functional build? With the new gpu update this feature would be really awesome to have! And can there be an option for button press not hold, just like @dolent initially suggested?

**Comment by adityaruplaha** [comment]
I don't think anyone is working on this. But I'll try doing it.

**Comment by adityaruplaha** [comment]
I've nearly completed it @EddyHg80 @Eduard-Dumitrescu, but which key should be the "Boost" button?

**Comment by Eduard-Dumitrescu** [comment]
Well on the old emulators i think it was space, but if it's not to hard/ time consuming can the button also be edited in the config file(i don't remember if that's how it's called) so we can also map it to a controller button?

**Comment by adityaruplaha** [comment]
No, coz it's a hotkey, and I don't know if one can map hotkeys to a controller in the current state of Citra. I may try though.

Space is 👍

**Comment by jroweboy** [comment]
Still don't like this idea. Or at least I don't like any of the designs presented here. Adding a second set of "Boost" options greatly complicates the settings without providing much benefit. We have a hard enough time with users that don't understand the existing "Limit Speed" dialog, so how are you expecting users to understand two options and the different ways they interact?

I'd much rather see a design thats simple than a design that covers every possible theoretical usecase that we can imagine. 

Heres an example of something that I think would be much better. You are welcome to iterate on this as I didn't put too much effort into this design. The goal is to reduce the number of options while still meeting the goal for having a "Press tab to speed up"

```
[ ] Enable Frame Limit               Speed Unlock Limit [ 200%  ^v ]
```

Then add a hotkey for `Speed Unlock` to whatever you want (space or tab or whatever. we need more work done on a ui for remapping hotkeys). I chose the name Speed Unlock as its more descriptive than Boost because boost implies we are enhancing something like a clock rate, when in reality we are just reducing the wait time in between frames.

With this design we still can

* turn off frame limit for a max speed test
* configure how fast the boost key goes

and we lose the ability to 

* run at a non 100% speed and then boost to a different speed (something i consider as a less common usecase)
* use the boost key to directly turn off the frame limiter (but you can still *effectively* do this by setting it to a large number)

I don't see those two as show stoppers. Here are the things i actually consider as issues with this new proposed design:

* Its not clear what speed boost is. We don't have tool tips to explain it, and our hotkeys are a mess right now so we can't put (Hotkey: <Tab>) in the description either. Its not exactly a discoverable feature without a way to show the use how this is used
* Toggle versus Hold cannot be set. This is perhaps something that should be addressed with a full rework of the hotkey system instead of here.

I hope this helps someone to take the time to make a good design.

**Comment by adityaruplaha** [comment]
Thanks for the review @jroweboy . I'll change the name. I'm ready to do stuff on the UI, as I don't like the names given either (is it ok if I don't change the names inside the code? I will if I have to) . I also don't like the present design much & will definitely work on it. It seemed a little, cumbersome. I just wanted to follow the design by Eddy in his comment to get the stuff working first.

**Comment by B3n30** [comment]
@adityaruplaha I discussed that topic with @jroweboy and a probably even cleaner approach is:
Have a default speed limit of 100%. No checkbox to disable/enable that limit
Then have a speed modifier value in the config that you can set to values like 0.5, 1.5, 2, 2.5, 3, and unlimited. My suggestion would be to have that as a combo box in the ui but still have the ability to edit the value to any thing you want in the ini.
Finally have a hotkey to toggle the speed modifier. That way we still keep the current implementation plus adding your suggestion of a boost hotkey while in the ui there is just one setting, which is very clean and simple for the user.

If you are going to implement that please consider the following: We have to frontend so it is required for both. We have telemetry for the frame limit stuff, those should probably be reworked for the new implementation too. For that you have probably to coordinate with @chris062689 

If you have further questions, please feel free to contact me in discord.

**Comment by adityaruplaha** [comment]
I'm quite familiar with the telemetry backend, thanks to the search
function. But for some reason, Flamesage is not replying to my PMs on the
forum. But I'll contact him.

I like this design, but there's a problem. If we press a hot key, it'll
straight go to unlimited. We can't set specifically what limit it should do
to. But I'll keep the percentage sign. Combo boxes are cake for me as I
already used them in quite a few .NET programs. I'll do it today (Maybe
around 1100 IST).
Might take some time though, as I have to rewrite a lot of code. And the
hotkeys REALLY need rewriting (took me ages to finally get it).

Adityarup Laha

**Comment by Eduard-Dumitrescu** [comment]
Is anyone still working on this/ can it actually be done?A toggle for just the Limit speed percent would also be fantastic...

**Comment by Tim3W4rp** [comment]
Hey, is there a build this would be implemented in? This issue seems to still be open and is not in the latest nightly-729 cf9bfe0 release.

**Comment by EddyHg80** [comment]
Now that #3786 is merged into the canary build can we close this issue?

Although that pull is missing 2 things:
-the ability to map the hotkey to an external controller
-the ability to choose between "hold down" and "press to toggle"
but those are general "missing feature", not specific to this issue.
