### ISSUE TITLE
Fire Emblem: Fates - Unimplemented Pipe 3

### ISSUE THREAD

**Issue by Ulinsky** [citra-emu/citra#3442]

**Comment by MerryMage** [comment]
Related issue: #2565

**Summary:**

Long standing issue due to unimplemented features in DSP HLE.

**Versions affected:**

Last tested version was 775fb388c29530a9e552da83b7f2ab75e9227e28, issue affects all versions before this.

**Steps to Reproduce:**

Entering your private quarters during the game would result in the background music will stopping, and the following line in the logs:

```
Audio.DSP <Critical> audio_core/hle/hle.cpp:PipeWrite:181: pipe_number = 3 unimplemented
```

**What should occur:**

What should occur is demonstrated in this video: https://www.youtube.com/watch?v=xWC4T1Mt2T4

Freeze would occur on Citra at 0:09 in the video.

**Comment by MerryMage** [comment]
Superseeded by `#3443`.
