### ISSUE TITLE
Can we just use System Username instead of hardcoded string?

### ISSUE THREAD

**Issue by mattatobin** [citra-emu/citra#3477]
Basically, couldn't you just use the System Username set in configuration instead of `Citra` that is hardcoded in https://github.com/citra-emu/citra/blob/master/src/core/hle/applets/swkbd.cpp#L80 ?

You know, until the new software keyboard is ready?

**Comment by adityaruplaha** [comment]
Hey, I was thinking about the same thing! Please add E-easy label, as this will be straightforward to implement. I'll try to work upon it.

**Comment by jroweboy** [comment]
The reason it hasn't been done is because that code was written long before the software keyboard was reverse engineered. Now that we have more information about how the software keyboard works, this code is woefully in need of a complete overhaul. Most of the code thats there is just barely functional as is, and it'd be much better for someone to write an actual software keyboard implementation instead of piling another hack on which would just make people less anxious to actually fix the issue.

Putting a workaround in place instead of a proper fix leads people to just leave it alone because its "good enough" Because of that, I'm opposed to making this change. We need a real fix that fixes the other games that are broken and not just a one off hot patch.

In other news, there is a developer working on getting both the official system keyboard working, and a FOSS keyboard that we can ship with citra. currently they work, but crashes citra when you try to close citra. it'll take a bit before this is fixed as its an issue with changing the texture cache to support multiprocesses.

I'm open to other devs opinions about this, so I'm not closing this right now.

**Comment by mattatobin** [comment]
I totally understand the issue but a solution beyond modifying the hardcoded string and compiling my self is better than no solution at all. Of course, people would want full keyboard support so I don't see how a minor hack to give casual users SOMETHING to tide them over would hurt the development of a proper software keyboard or why it would be an all or nothing situation.

Frankly, I was a bit turned off by this not being a thing especially when it sure looks like the system username would work. Of course, I am no stranger to software development and could just compile my own private build to get what I wanted but seriously who else is gonna do that?

I still think it is a good enhancement to have something rather than nothing.

**Comment by mattatobin** [comment]
May I have a patch file or a link to your repo commit for private use by chance?

**Comment by adityaruplaha** [comment]
Of course. I'll comment it here when it's ready.

**Comment by adityaruplaha** [comment]
@mattatobin See this. I'll do the UI later.
#3488
