### ISSUE TITLE
TwoSideDiffuse seems to have an issue on Citra

### ISSUE THREAD

**Issue by DiscostewSM** [citra-emu/citra#3482]
Testing on Citra Nightly | HEAD-1a2f29a (757)

Based on the work of StapleButter, I've been working with luminous textures to form a kind of indexed texture with up to 255 adjustable colors through the use of Reflective LUTs (one entry remains black because the normal for that entry equals zero), but results on Citra differ from what is displayed on hardware. Left is the result on hardware, right is the result on current Nightly Citra, regardless of Citra's hardware renderer being enabled or not.
![citra](https://user-images.githubusercontent.com/10163038/37057420-1d6fb706-213c-11e8-8ec5-8c431604dca8.png)

I provided a test case (3dsx with source) so you can take a look at how it is set up. Near the end of the sceneInit() function is the line for TwoSideDiffuse. If you set that to false, then the result on hardware will match what is shown in Citra. From what I understand, the input range is from -1.0 to 1.0 when TwoSideDiffuse is enabled. When disabled, the negative values are clamped to 0 so the range becomes 0.0 to 1.0. The texel values range from 0x00 to 0xFF (equivalent to -1.0 to 1.0?), with 0x80 being equivalent to 0.0. The top-left block ranges from 0x80 to 0xBF (cascade from top-left to bottom-right of block). Top-right block from 0xC0 to 0xFF. Bottom-left from 0x00 to 0x3F. Bottom-right from 0x40 to 0x7F. Disabling TwoSideDiffuse would make values from 0x00 to 0x7F to be clamped to 0x80. Enabling should not clamp, but this example on Citra doesn't have an effect.

https://www.dropbox.com/s/tb6jf0trubzc6jn/indexed_texture.zip?dl=0

Compiling requires the latest devkitpro and citro3D library.

**Comment by wwylele** [comment]
Did a little experiment, and it turned out that the dark color isn't caused by TwoSideDiffuse calculation (which is correctly implemented), but from the clamp_highlights factor. Take the software renderer for example, if one comments out this block https://github.com/citra-emu/citra/blob/1a2f29aad0e5de3079a5038721ba92a933f51644/src/video_core/swrasterizer/lighting.cpp#L260-L268, I would get four colors on the screen. There is equivalent code in the hw renderer, where highlight clamping is tested against pre-abs product. So now there is a possibility that real hardware does highlight clamping test after the two-sided-diffuse pass. This needs more hwtest, and if it turns out so, should be easy to fix.

**Comment by DiscostewSM** [comment]
Thank you. From my perspective without digging into the Citra source, I just assumed it was the TwoSideDiffuse since enabling/disabling changed things on hardware but not Citra. Glad to see you have some insight to the problem and a possible fix.
