### ISSUE TITLE
Mario & Luigi : Paper Jam Bros. shared_font fatal error

### ISSUE THREAD

**Issue by greggameplayer** [citra-emu/citra#3707]
## Hardware Specs :
- Nvidia GeForce GTX 960
- Intel I7-7700k @ 4.5Ghz
- 8 GB Of Ram 3200Mhz
- Windows 10 Pro
 
## Citra Tested Build Version :
HEAD-9c65a45

## The issue :
when you launch the game a window pop up in order to say there is a fatal error and in the console we can see fatal error on shared_font reading, on others citra versions this game worked normally, so can you correct this issue ?

## The Log :
[→ Click Here ←](https://gist.github.com/greggameplayer/a4997fa946d8c158f8784b69743331a2)

**Comment by chris062689** [comment]
I found some issues in that log that need resolving: 
   - The ROM you are attempting to run is encrypted. Look here for instructions on how to properly dump ROMs from your 3DS. https://citra-emu.org/wiki/dumping-installed-titles/

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum. Please use the [forums](https://community.citra-emu.org/) for support requests.

Requesting to close.

**Comment by greggameplayer** [comment]
@FearlessTobi this is an issue not a support request.

**Comment by wwylele** [comment]
I failed to reproduce the issue on the same citra version with EUR version of the game. Based on game ID, yours looks like also the EUR version. However, in the log the region selector says `Preferred region code set to 0` (automatically selects JPN region). Could you please test to see if manually selecting EUR region works? If this does work, this indicates your ROM has a modified region lock info, which is out of the scope citra can support. Please close this issue if it turns out to be the case.

**Comment by greggameplayer** [comment]
@wwylele yes it's work when you select eu region, thanks you for the help

**Comment by greggameplayer** [comment]
So i close the issue like you are requesting.
