### ISSUE TITLE
AR Games - Green Screen with System Camera (qt)

### ISSUE THREAD

**Issue by Leo626** [citra-emu/citra#3797]
Reporting what was posted in the [forum](https://community.citra-emu.org/t/system-camera-qt-shows-green-screen-on-ar-games/23507). This used to work in previous Canary builds. The last one I could find before this happened was Canary-450 (b40c597) though the image is flipped upside down. Note that I had to copy the mediaservice folder with a DLL file from a newer build for this to work since it was missing.

Tested with Nightly-705 (72f9142)
[Log](https://pastebin.com/nNfPRM6a)

![citra-qt_2018-05-31_16-01-11](https://user-images.githubusercontent.com/17358613/40806437-d23d50d6-64f7-11e8-9f7e-2bb83265f865.png)
![citra-qt_2018-05-31_16-28-18](https://user-images.githubusercontent.com/17358613/40806496-1320e14e-64f8-11e8-9694-639cdd363424.png)

**Comment by zhaowenlan1779** [comment]
OK. I will look into it..

**Comment by zhaowenlan1779** [comment]
I've tested my self.
Here is my result:
### AR Games app:
System Camera: not working
Still Image: working
### Pokemon UM
System Camera: working
Still Image: working

Which is certainly not expected, as the system camera and still image are just different implementations and should work the same.
#3739 also reported some other games, and in those games neither system camera or still image is working.

Well, sound like this is really a complicated problem

**Comment by zhaowenlan1779** [comment]
Got important clue
My log includes this:
`failed to start`
which is definitely printed by `QCamera` (because it is not in Citra's log format).

**Comment by zhaowenlan1779** [comment]
Fine.
This is an issue which I ignored when making camera.
*AR Games uses 3D effect for camera*, but you can't load two QCamera s of the same system camera. So one replied with green screen (the other works properly though).
So when you change Rear config to 3D and only uses system camera on one of the sides, it will work.
I will work on a fix to actually implement `Single` and `Double` instead of just duplicating the config.
