### ISSUE TITLE
Shared Font: loading opensource one even having the original

### ISSUE THREAD

**Issue by Colmines92** [citra-emu/citra#3993]
From a time ago citra is using the newly included open source font even when I have the dumped "shared_font.bin" placed under <citra_path>"\user\sysdata"

I have screenshots and backlogs. They are from valentinvanelslande's builds, but it happens with nightly too:

https://user-images.githubusercontent.com/25232329/43092360-fcdc8bac-8e7a-11e8-98fb-01ba4c3e535f.png

https://user-images.githubusercontent.com/25232329/43092398-1590ddc4-8e7b-11e8-86a0-4a5739d88af9.png

Logs:
https://github.com/valentinvanelslande/citra/files/2220376/citra_log_244.txt
https://github.com/valentinvanelslande/citra/files/2220377/citra_log_285.txt

**Comment by jroweboy** [comment]
The shared_font.bin file has been deprecated for quite some time and is was removed when we added the open source replacement. This was because of technical reasons on how we had to hack the loader in order to load the bin version. You either need to update to use the new dumping method, or just use the open source one.

**Comment by chris062689** [comment]
Please refer to our system dumping guide. https://citra-emu.org/wiki/dumping-system-archives-and-the-shared-fonts-from-a-3ds-console/
