### ISSUE TITLE
[Rune Factory 4] Issue with text after Nightly update

### ISSUE THREAD

**Issue by Bass-Ocelot** [citra-emu/citra#4009]
**Issue**
Text glitches and is shown incorrectly after nightly update

**Comparison:**

Citra Version: ``Nightly HEAD ``9bd3986``
![image](https://user-images.githubusercontent.com/26095543/43296400-b7bc9aec-9110-11e8-83c5-2a78ddd2172d.png)

Citra Version: ``Nightly HEAD ``7868506``
![image](https://user-images.githubusercontent.com/26095543/43296473-29eb9528-9111-11e8-8848-f5ac214c2d3a.png)

As you can see the update changed the "font" of text in the entire game. From what I've seen it looks like it only affects numbers displayed in dialogue or decision boxes.

**Comment by Dragios** [comment]
This report is not valid. You're using a very old build from 2017 which uses the legacy `shard_font.bin` to display the text. The current nightly build does not support the legacy method anymore. Reason for the text glitched is due to Citra resort to using the open source shared font (see here for more details PR #3881).

Please dump the latest system archive using this [tool](https://cdn.discordapp.com/attachments/242442830486700045/357712552999911424/3dsutils-master-f73f28f.3dsx) to solve the text glitch issue.

**Comment by Bass-Ocelot** [comment]
@Dragios The old build was simply to show how it used to look like up until the 9bd3986 update but dropping support for the legacy method explains it.

**Comment by Dragios** [comment]
Actually you don't need that old build to showcase that different. [Nightly-806](https://github.com/citra-emu/citra-nightly/releases/tag/nightly-806) will produce the same result. This is just fyi.
Please don't comment any further unless it is related to the issue itself.

For support request I suggest use the [forum](https://community.citra-emu.org/) or even better use our official [Discord](https://citra-emu.org/discord/)

**Comment by wwylele** [comment]
Please redump your system archive as we removed shared_font.bin support, thanks!

**Comment by Dragios** [comment]
@Bass-Ocelot Can you upload a save file for me so that I can try to fix the open source font unreadable text?

**Comment by Bass-Ocelot** [comment]
@Dragios just saw this, here's a save file.

[rf4a.zip](https://github.com/citra-emu/citra/files/2251855/rf4a.zip)

**Comment by GamerzHell9137** [comment]
The issue still persists with the latest builds.

**Comment by marlonxb** [comment]
https://www.youtube.com/watch?v=SJJheC_mGNA this video help me solve this problem
