### ISSUE TITLE
Black/missing textures in Starfox 64 3DS

### ISSUE THREAD

**Issue by mrbluru** [citra-emu/citra#4039]
Some textures seemingly don’t load making the game very difficult to play, both in menus and in game

System Information

Operating System: Windows 10 Home 64 Bit

CPU: Intel Core m3-7Y30 CPU @ 1.00GHz

GPU: Intel HD Graphics 615

Citra Version (found in title bar): Nightly 847

Game: Starfox 64 3DS

[citra_log.txt](https://github.com/citra-emu/citra/files/2242905/citra_log.txt)

![sf screen](https://user-images.githubusercontent.com/41925197/43423663-e73a8f2c-9444-11e8-8384-c1a0db451bdf.png)

It may be worth noting that disabling the Hardware Renderer fixes the graphics issue, although makes the game unplayabley slow

**Comment by Dragios** [comment]
Should be related to #3940

**Comment by benderscruffy** [comment]
must be an  Intel HD Graphics problem as it show properly on my amd
![starfox](https://user-images.githubusercontent.com/2696404/50721839-0b13d780-1101-11e9-838d-6a30ebf156a8.PNG)

**Comment by Wolfy963** [comment]
If you have a not powerfull computer the game is unplayable in the two case (With Hardware Shaders. Because all is black. Without Hardware Shaders. The game is very slow.) And install the latest nigthly build (1315) There is two screenshots of the game.
![With Hardware Shaders](https://user-images.githubusercontent.com/53375119/61996376-b9617900-b061-11e9-9f9b-c66ed5589cae.png)
![Without Hardware Shaders](https://user-images.githubusercontent.com/53375119/61996377-b9617900-b061-11e9-9559-1bf82cf6f61e.png)

**Comment by benderscruffy** [comment]
using Canary 2615
has been fixed
can be closed
