### ISSUE TITLE
Pokémon Omega Ruby broken with a Intel HD Graphics GPU

### ISSUE THREAD

**Issue by LOuroboros** [citra-emu/citra#4092]
I haven't updated Citra in a while, so yesterday, I downloaded the latest Canary build (3e71454).
I noticed right away that Pokémon Omega Ruby wasn't working, so I slowly went back in the /releases page and tried different builds until I was able to pinpoint where did the compatibility broke.

Apparently, the game broke in Canary 708 _(54437f6)_, because in Canary 707 _(210a928)_ it was still working correctly.

Here's a comparison pic that I made:
![citra-qt-2018-08-12_01-21-06](https://user-images.githubusercontent.com/4485172/44003464-5d6cb290-9e29-11e8-8ee8-a3c0a349ab21.png)

I also booted the game for a few minutes in Canary 708 to make a log, I don't know if it'll be useful, but here it is:
https://pastebin.com/SDJKTLDF

**CPU**: Intel Celeron N2840
**GPU**: Intel HD Graphics
**OS**: Windows 8.1 x64

**Comment by Jules-A** [comment]
Probably [PR 4042](https://github.com/citra-emu/citra-canary/commit/3fa1b071995f2dba8aaaec6f6cce475062a550a0)

**Comment by greasythemattis** [comment]
I wasn't able to recreate this using the latest Canary.
![1](https://user-images.githubusercontent.com/7724121/44026077-531452ea-9ec8-11e8-882b-fcc6751a6202.png)

CPU: i5-6200u
GPU: HD 520
Driver Version: 24.20.100.6194
GPU Driver: OS: Windows* 10 Home Single Language (10.0.17134)

**Comment by LOuroboros** [comment]
Before making this issue, the last build I've tried was Canary 754. Sadly, the issue is still present in Canary 762.
![citra-qt-2018-08-13_12-11-40](https://user-images.githubusercontent.com/4485172/44040653-351ed61e-9ef2-11e8-99c3-ce21e575ebe3.png)

Disabling Hardware Shader fixes it, but the performance suffers a serious hit.

**Comment by greasythemattis** [comment]
That's odd. When I took that pic I had HW Shader On. Mind telling us your driver version?

**Comment by LOuroboros** [comment]
10.18.10.3540, the last driver available for my CPU on Intel's website.
It might be a hardware-specific problem, considering your iGPU is way newer than mine, @greasythemattis.

**Comment by jroweboy** [comment]
@LOuroboros that version introduced the "apply amd workaround only for amd" because the amd work around hack seems to cause issues for intel cards. But apparently it also causes an issue when removed for your specific card and driver. its a frustrating case of hack-a-mole tbh

**Comment by Dragios** [comment]
Issue #4068 is also break by PR #4042 although it yield different result than this.

**Comment by jroweboy** [comment]
i'm starting to think we just need to throw away separate shader objects entirely. this is getting really dumb....

@LOuroboros since you left a "confused" emoji. lemme explain it a bit more clearly (this time at a pc instead of using my phone)

We use an OpenGL extension called "separate shader objects" which lets us compile individual gpu shaders instead of an entire program which includes vertex shaders, (geometry shaders if enabled), and fragment shaders. If a GPU supports this feature, we will use it, otherwise we have a fallback path that doesn't use it. With the extension enabled, we drastically cut down shader compilation stutter, as we can reuse already compiled shaders, we only need to link the full program instead of compile and link for every combination of shaders. On my machines, without the extension, pokemon moon would pause for a good 10 seconds when loading something for the first time (after which it was cached, and it wouldn't pause anymore) and with the extension it only takes 2 or 3 seconds.

But, it turns out AMD and Intel drivers have some issues with this extension. Even though they claim to support it, it often results in broken graphics when we use it. A while ago, we found that explicitly rebinding the pipeline to nothing, then rebinding it to the correct pipeline fixed some crashes and missing graphics for AMD cards. But recently we found that it also *caused* new issues for some newer Intel cards. So we changed it to basically say "if AMD { apply hack to fix broken graphics }". And now, according to this report, you are saying "but wait! its also still broken on some older Intel cards as well!" so what are we going to do? We can't just say "If AMD or Intel" because it *broke* some Intel having it on, and now we see it breaks some Intel having it off...

Maybe the real solution is to just remove the extension entirely, and finish async shader compilation and disk cached shaders so we can load them on startup. I don't know yet. Clearly trying to add a driver black list is just going to be a big headache...

**Comment by Jules-A** [comment]
@jroweboy what about making it a UI toggle for now until such features are implemented? I'd assume the extension only works on 5/6th gen Intel graphics and maybe it does work on some AMD cards/drivers also?

**Comment by jroweboy** [comment]
@Jules-A in my opinion, we've already hit the limit of too many confusing options, and we are probably about to add another with https://github.com/citra-emu/citra/pull/4089 coming up soon. Thats not to say we won't add this as an option, but its really annoying when a GPU "supports" something but their support is broken. But without removing it entirely, we are kinda stuck between a rock and a hard place

According to this list, https://opengl.gpuinfo.org/gl_listreports.php?listreportsbyextension=GL_ARB_separate_shader_objects the extension has roughly 80% support across gpus that submitted reports to that site. only major ones missing it are intel hd4k series and an assortment of amd cards.

**Comment by LOuroboros** [comment]
> too many confusing options
I mean, wouldn't it be a matter of stating in the option's title, who it is supposed to target?
Like, for example, "Disable AMD Workaround [INTEL HD GPU 4XXX FIX]".
With a name like that, people using Intel GPUs would know right away that they need to have that option checked.

Or maybe have a brief description pop-up when the user hovers his mouse over the option like other options such as Hardware Shader already have, stating the type of user who needs to keep it checked.
![citra-qt-2018-08-14_13-16-49](https://user-images.githubusercontent.com/4485172/44104106-5586b2b4-9fc4-11e8-9e42-f8afba870fc8.png)

**Comment by Jules-A** [comment]
@jroweboy I'm not sure why you would want to remove the extension entirely when it does this 
> without the extension, pokemon moon would pause for a good 10 seconds when loading something for the first time (after which it was cached, and it wouldn't pause anymore) and with the extension it only takes 2 or 3 seconds.
on working machines.
At least a hidden config entry or listing in debug maybe?

@LOuroboros Since it also affects Intel it would make more sense with something like "Disable AMD/Old Intel Graphics Workaround"

**Comment by jroweboy** [comment]
@Jules-A My reason for dropping it is because the suggestions that I proposed would be ever better for users. All shaders would be stored on disk and loaded on an async background thread when you load the game. While we are compiling and linking all shaders, we can fallback to our CPU JIT shader implementation which would be *almost* full speed for most people. (And I'm going to be bringing back the multithreaded cpu jit shaders, which would make it even faster while the gpu shaders are loading) Since the game is loading, most people would only have *maybe* a few seconds of slower than fullspeed gameplay after which all shaders are loaded and they don't have any more freezes or slowdowns. This is similar to what dolphin and rpcs3 does, except citra has a fast cpu shader implementation that we can fall back to, so we shouldn't have to have "graphics pop-ins" since we will always run all shaders.

**Comment by Jules-A** [comment]
> My reason for dropping it is because the suggestions that I proposed would be ever better for users.

@jroweboy Well I was only suggesting to have a toggle until such solution is implemented. I was assuming something like this could take months before it's complete.

**Comment by greasythemattis** [comment]
I found out something interesting while playing Etrian Odyssey V. While Pokémon Omega Ruby was fine for me using Canary-708 I didn't have this much luck in Etrian Odyssey V.

![comparison2](https://user-images.githubusercontent.com/7724121/44514667-1bb63a80-a697-11e8-940f-08fcf4d0006c.jpg)
_(Left Screen is actually the top 3DS one)_

What you're seeing is both Canary-708 and Canary-707 with Hardware Shader enabled. And just like @LOuroboros, disabling Hardware Shader renders accordingly.

**Comment by Degerz** [comment]
@jroweboy I don't know if this still applies but it sounds like AMD might have released a driver fix for the issues you guys were encountering with separate shader objects below:

https://community.amd.com/thread/194895

**Comment by Jules-A** [comment]
>it sounds like AMD might have released a driver fix for the issues you guys were encountering with separate shader objects below:
> https://community.amd.com/thread/194895

According to one of the PCSX2 devs it was fixed in 18.10.2 but that driver is still pretty recent and there would be a lot of people still on older drivers so either you would have to change the AMD check to a driver check or just leave it as it is for now.

**Comment by Degerz** [comment]
Might as well just capitalize on it since AMD already stopped sending their Windows 7 implementation of OpenGL ICDs to Khronos Group for conformance testing which means in the not too distant future AMD only build drivers for WDDM 2.x (Windows 10 and up) ... 

Basically, if developers want to work with approved OpenGL implementations beyond version 4.5 such as version 4.6 then it is only guaranteed conformant for the 64-bit version of Windows 10 ...

**Comment by Tabish4675** [comment]
@LOuroboros Are you still having the issue?

**Comment by LOuroboros** [comment]
Yes @Tabish4675, sadly.
![citra-qt-2019-01-14_20-00-48](https://user-images.githubusercontent.com/4485172/51146994-6a779300-1837-11e9-912e-4780b47186a5.png)

**Comment by greasythemattis** [comment]
The very same for me playing Etrian Odyssey 5 while using the latest canary build.

**Comment by Tabish4675** [comment]
@LOuroboros I have a Intel HD Graphics 510 and the game works totally fine on my side. Which Intel HD Graphics do u have? And... do disabling Hardware Shaders still hit the performance?

**Comment by LOuroboros** [comment]
As I mentioned in the original post, I have an Intel Celeron N2840 as my CPU ans I'm using its Integrated GPU, @Tabish4675.

And, as I also said up there, disabling Hardware Shader fixes it the visual issues, but it causes a big performance hit too.

**Comment by LOuroboros** [comment]
So, remember how I said that the Graphics Driver v10.18.10.3540 was the latest one available for my CPU on Intel's website?
Turns out there was a newer version available for me to try out, the v10.18.10.4176 which for some reason is not available in Intel's page. I found out about by looking at the website Guru3D pretty randomly.
I took the plunge, made a System Recovery point, uninstalled my driver and installed this new version.
The result? Ta-da!
![2019-02-14_00-06-56](https://user-images.githubusercontent.com/4485172/52760198-62a13f00-2fed-11e9-8a5f-457e3a0c914c.png)

So yeah, as far as I'm concerned, this might have been an outdated driver issue this whole time, but do keep in mind that there was no proper way for me to found this out, as again, the driver in question was not available from Intel's page. It's pretty weird too, I mean, the driver IS for an Intel HD Graphics GPU after all. Maybe it was made by a 3rd party like ASUS or DELL for their low-end laptops...?
This CPU was often seen in low-end laptops back in 2014-2015, so maybe that was it. I honestly don't know.
