### ISSUE TITLE
libzmq-external: Linker debug linked release static lib

### ISSUE THREAD

**Issue by namkazt** [citra-emu/citra#4205]
Img: 
![qdwdqdqw](https://user-images.githubusercontent.com/6035916/45424955-368e3480-b6c2-11e8-8c5c-6d589082d5cd.png)

it should be like: 
`..\..\externals\libzmq-external-prefix\src\libzmq-external-build\lib\Debug\libzmq-v141-mt-sgd-4_2_5.lib`

case build failed: 
```
error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in aboutdialog.obj
... more
```

**Comment by EverOddish** [comment]
![libzmq_screenshot](https://user-images.githubusercontent.com/16278121/45442927-55c09e00-b691-11e8-87be-a61d6eb8cc4b.PNG)

![libzmq_screenshot_2](https://user-images.githubusercontent.com/16278121/45443068-b354ea80-b691-11e8-9232-22a7bb48cb7c.PNG)

I seem to have a slightly different build error, where libzmq is built as Debug, and the generated project files are configured for Debug, but the output filename still doesn't match ("-s-" instead of "-sgd-")

**Comment by EverOddish** [comment]
It seems that it's not possible to support two different configurations when using ExternalProject and imported targets. The solution seems to be the use of add_subdirectory, according to this StackOverflow question: https://stackoverflow.com/questions/43692976/compile-boost-with-multi-configuration-with-cmake However, libzmq's clang-format target conflicts with that of Citra with the same name. @wwylele Do you have any thoughts on how to proceed?

**Comment by wwylele** [comment]
@EverOddish I provided some idea on discord. You can try `add_subdirectory` with `EXCLUDE_FROM_ALL`. Or you can go to convince libzmq to change their target name...

In the worst case where nothing works, or you just don't have time to try them, simply rename our clang-format target.

**Comment by zhaowenlan1779** [comment]
libzmq has been removed for a long time now
