### ISSUE TITLE
[Request] Asynchronous shader compilation and save the shaders cache for low spec systems

### ISSUE THREAD

**Issue by beatlep** [citra-emu/citra#4357]
I have a system with an Intel Core m3 7Y30 and Intel HD Graphics 615 and in games with many shaders the shader compilation stutter a lot making some games almost unplayable.

I think that with Asynchronous shader compilation like in RPCS3 or Dolphin these games would run a lot better.

Saving the shaders cache on a folder would be good too to skip the shader compilation every time we start a game.

**Comment by LuigiBlood** [comment]
I have a system with AMD FX-4300 and Nvidia GeForce GTX 1050Ti and I have the same results: disabling Shader JIT actually makes games stutter less so clearly, the feature that's meant to be more efficient somehow isn't.

**Comment by jroweboy** [comment]
@LuigiBlood if you have hardware shaders enabled, shader jit does absolutely nothing. it sounds more likely that you are conflating some settings here.

**Comment by LuigiBlood** [comment]
Well I still reliably get more or less stutters depending on this setting so if it does absolutely nothing I'd wonder how.

**Comment by jroweboy** [comment]
As i stated, the setting only matters if you have hardware shader setting *disabled* as hardware shaders cover the entire usage of cpu shader jit. If you can reliably recreate the issue on a certain game and take a video of increased stutter while hardware shader on/shader jit on compared to hardware shader on/shader jit off, then this is something that should be mentioned in a new issue.

Otherwise, shader jit talk doesn't belong in this issue at all, as its talking about disk caching for hardware shaders.

**Comment by jroweboy** [comment]
This is partially addressed with #4923 I've already started work on Asynchronous shader loading, but its going to take more work than I initially thought due to how citra's shader cache currently works

**Comment by GPUCode** [comment]
Has been implemented in vulkan renderer
