### ISSUE TITLE
StreetPass Mii Plaza - Update not working

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#4401]
Tested with USA Mii Plaza with update and DLC (dumped with latest GM9) installed.
[citra_log.txt](https://github.com/citra-emu/citra/files/2545543/citra_log.txt)
![screenshot](https://user-images.githubusercontent.com/22228082/47959709-f1e39300-dfb8-11e8-8122-cb705af1dc11.png)

**Comment by Dragios** [comment]
What kind of update that is not working here? Description too vague. Can launch Puzzle Swap and Find Mii without any problem. I guess this can be close.

**Comment by vvanelslande** [comment]
@Dragios DLC

**Comment by Dragios** [comment]
You meant ext data? There is no DLC available for this title as far as I know. Please change the title to better describe the issue.

**Comment by vvanelslande** [comment]
@Dragios https://en.wikipedia.org/wiki/StreetPass_Mii_Plaza#Paid_games_(DLC)

**Comment by vvanelslande** [comment]
and I deleted the account that opened the issue

**Comment by Dragios** [comment]
@FearlessTobi Could you update the issue title and the description to better describe the issue as you sees fit? It seems that Citra cannot detect any extdata installed therefore DLC is not detected due to the aformentioned issue.

Right clicking only shows "Open Application Location" unlike other normal 3DS games that shows bunch of options.

**Comment by vvanelslande** [comment]
fixed by using LLE CECD and launching the update (not the base game) from FBI (I didn't try with File -> Load File)
