### ISSUE TITLE
mac os error

### ISSUE THREAD

**Issue by gs456456456** [citra-emu/citra#4446]
when I run make -j4,I face this question

../3ds/citra/externals/dynarmic/src/backend/x64/emit_x64_vector.cpp:3814:34: fatal error:
      unknown warning group '-Wunused-lambda-capture', ignored
      [-Wunknown-warning-option]
#pragma clang diagnostic ignored "-Wunused-lambda-capture"

**Comment by evayde** [comment]
I have just built it without any problems whatsoever, could you share your systems' specs? 

what is the output of `gcc --version`?

**Comment by zhaowenlan1779** [comment]
The CI builds fine. This is likely because your clang is outdated. Please update to the proper versions.
You can learn about how to build Citra for macos by reading our [guide](https://github.com/citra-emu/citra/wiki/Building-for-macOS).

If you need any further help, feel free to ask for support in our [discord](https://citra-emu.org/discord).

**Comment by androidfans** [comment]
i meet this problem also

gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by androidfans** [comment]
i have updated every build tool

**Comment by evayde** [comment]
@androidfans You have LLVM 9.0.0 and clang-900.x my working system has LLVM 10 and hence clang Version clang-1000.x

as @zhaowenlan1779 indicated: this might be a problem of an outdated clang version. Try to update accordingly.
