### ISSUE TITLE
Save States

### ISSUE THREAD

**Issue by ReclaimerShawn** [citra-emu/citra#4467]
Could we get the ability to take a snapshot of our gameplay and then be able to reload our gameplay from that snapshot (without actual saving)? For instance, let's say you're in the middle of a boss fight. The boss is at 50% health. With save states, you could save that state and go back to that point with the boss having 50% health at any time.

**Comment by zhaowenlan1779** [comment]
Hmm that's weird. I thought we have an issue open for this, but looks like not. 
Just saying, this feature will likely need a lot of work to complete, and it may not be there for a long time. We definitely want this feature though, so it may be implemented in the distant future :p

**Comment by Johngew** [comment]
is it possible make the save states in pause mode [more accurate is like virtual box snap short ?]
then save states will work each game / title unique (snap short) ?

like I play PKM i click save states . I off.
later I open DQMJ3P I load save states before PKM does .

each game has own tilte snap short or null .. ?
and load it when load a game after ?
a pause mode and click continue??

I just show my feeling about that.
because virtual box does not care what is os inside doing just large size of pack it and hold in pause mode.

**Comment by Johngew** [comment]
forget >> each title game only a single save states file <<
or a command clear all save states.

I think save states only work in special case like PKM catching or DQM catching .

the rest normal save will do much all game.
so ...

^^ never fail in boss if save states out. keep saving XD

**Comment by Dragios** [comment]
This is implemented in PR #4908. Can be close.

**Comment by rlpowell** [comment]
0_o  WOW!  Thank you!
