### ISSUE TITLE
Rare threading-related crashes on graphics breakpoints

### ISSUE THREAD

**Issue by emmauss** [citra-emu/citra#447]
want to ask this: is there support for qt5.4.0?I have installed qt5.4.0 on windows 8.1 x64.i have set path variable for qt and it is properly configured in cmake. I can also build the qt debug version successfully, but when i run, i get this error
![screenshot 5](https://cloud.githubusercontent.com/assets/5307160/5671436/cb9829a2-977f-11e4-9067-ab14f8212c56.png)
![screenshot 6](https://cloud.githubusercontent.com/assets/5307160/5671456/00828acc-9780-11e4-80b9-bdada67ffd11.png)

**Comment by Apology11** [comment]
this also happened on qt5.3 for me, I reported it to @yuriks on the irc and send him a stack trace

**Comment by neobrain** [comment]
Hi,

No offense - but please don't submit support requests or questions like yours via the issue tracker currently, because it's not intended for that at the current development stage.

Meanwhile, feel free to ask on our IRC channel.

Regards,
neobrain

**Comment by yuriks** [comment]
@Apology11 Is this your stack trace? I thought this would be fixed by some other stuff but forgot to follow up. Apparently it's still an issue.

 	Qt5Cored.dll!qt_message_fatal(QtMsgType __formal, const QMessageLogContext & context, const QString & message) Line 1357	C++
 	Qt5Cored.dll!QMessageLogger::fatal(const char * msg, ...) Line 669	C++
 	Qt5Cored.dll!qt_assert_x(const char * where, const char * what, const char * file, int line) Line 2136	C++
	>Qt5Guid.dll!QVarLengthArray<QScriptAnalysis,4096>::QVarLengthArray<QScriptAnalysis,4096>(int asize) Line 211	C++
 	Qt5Guid.dll!QTextEngine::itemize() Line 1484	C++
 	Qt5Guid.dll!QTextLayout::beginLayout() Line 600	C++
 	Qt5Widgetsd.dll!viewItemTextLayout(QTextLayout & textLayout, int lineWidth) Line 803	C++
 	Qt5Widgetsd.dll!QCommonStylePrivate::viewItemSize(const QStyleOptionViewItem * option, int role) Line 852	C++
 	Qt5Widgetsd.dll!QCommonStylePrivate::viewItemLayout(const QStyleOptionViewItem * opt, QRect * checkRect, QRect * pixmapRect, QRect * textRect, bool sizehint) Line 948	C++
 	Qt5Widgetsd.dll!QCommonStyle::sizeFromContents(QStyle::ContentsType ct, const QStyleOption * opt, const QSize & csz, const QWidget * widget) Line 4829	C++
 	Qt5Widgetsd.dll!QWindowsStyle::sizeFromContents(QStyle::ContentsType ct, const QStyleOption * opt, const QSize & csz, const QWidget * widget) Line 2362	C++
 	Qt5Widgetsd.dll!QWindowsXPStyle::sizeFromContents(QStyle::ContentsType ct, const QStyleOption * option, const QSize & contentsSize, const QWidget * widget) Line 3818	C++
 	Qt5Widgetsd.dll!QWindowsVistaStyle::sizeFromContents(QStyle::ContentsType type, const QStyleOption * option, const QSize & size, const QWidget * widget) Line 1962	C++
 	Qt5Widgetsd.dll!QStyledItemDelegate::sizeHint(const QStyleOptionViewItem & option, const QModelIndex & index) Line 474	C++
 	Qt5Widgetsd.dll!QTreeView::indexRowSizeHint(const QModelIndex & index) Line 2983	C++
 	Qt5Widgetsd.dll!QTreeViewPrivate::itemHeight(int item) Line 3424	C++
 	Qt5Widgetsd.dll!QTreeViewPrivate::updateScrollBars() Line 3663	C++
 	Qt5Widgetsd.dll!QTreeView::updateGeometries() Line 2823	C++
 	Qt5Widgetsd.dll!QAbstractItemView::qt_static_metacall(QObject * _o, QMetaObject::Call _c, int _id, void * * _a) Line 391	C++
 	Qt5Cored.dll!QMetaObject::activate(QObject * sender, int signalOffset, int local_signal_index, void * * argv) Line 3683	C++
 	Qt5Cored.dll!QMetaObject::activate(QObject * sender, const QMetaObject * m, int local_signal_index, void * * argv) Line 3548	C++
 	Qt5Widgetsd.dll!QHeaderView::geometriesChanged() Line 431	C++
 	Qt5Widgetsd.dll!QHeaderView::viewportEvent(QEvent * e) Line 2607	C++
 	Qt5Widgetsd.dll!QAbstractScrollAreaPrivate::viewportEvent(QEvent * event) Line 110	C++
 	Qt5Widgetsd.dll!QAbstractScrollAreaFilter::eventFilter(QObject * o, QEvent * e) Line 126	C++
 	Qt5Cored.dll!QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject * receiver, QEvent * event) Line 1031	C++
 	Qt5Widgetsd.dll!QApplicationPrivate::notify_helper(QObject * receiver, QEvent * e) Line 3495	C++
 	Qt5Widgetsd.dll!QApplication::notify(QObject * receiver, QEvent * e) Line 3464	C++
 	Qt5Cored.dll!QCoreApplication::notifyInternal(QObject * receiver, QEvent * event) Line 935	C++
 	Qt5Cored.dll!QCoreApplication::sendEvent(QObject * receiver, QEvent * event) Line 237	C++
 	Qt5Widgetsd.dll!QWidgetPrivate::updateFont(const QFont & font) Line 4485	C++
 	Qt5Widgetsd.dll!QWidgetPrivate::setFont_helper(const QFont & font) Line 371	C++
 	Qt5Widgetsd.dll!QWidgetPrivate::resolveFont() Line 4422	C++
 	Qt5Widgetsd.dll!QWidgetPrivate::updateFont(const QFont & font) Line 4475	C++
 	Qt5Widgetsd.dll!QWidgetPrivate::setFont_helper(const QFont & font) Line 371	C++
 	Qt5Widgetsd.dll!QWidgetPrivate::resolveFont() Line 4422	C++
 	Qt5Widgetsd.dll!QWidgetPrivate::updateFont(const QFont & font) Line 4475	C++
 	Qt5Widgetsd.dll!QWidgetPrivate::setFont_helper(const QFont & font) Line 371	C++
 	Qt5Widgetsd.dll!QWidgetPrivate::resolveFont() Line 4422	C++
 	Qt5Widgetsd.dll!QWidget::setParent(QWidget * parent, QFlags<enum Qt::WindowType> f) Line 9691	C++
 	Qt5Widgetsd.dll!QWidget::setParent(QWidget * parent) Line 9594	C++
 	Qt5Widgetsd.dll!QLayoutPrivate::reparentChildWidgets(QWidget * mw) Line 852	C++
 	Qt5Widgetsd.dll!QWidget::setLayout(QLayout * l) Line 9274	C++
 	citra-qt.exe!GraphicsBreakPointsWidget::GraphicsBreakPointsWidget(std::shared_ptr<Pica::DebugContext> debug_context, QWidget * parent) Line 202	C++
 	citra-qt.exe!GMainWindow::GMainWindow() Line 75	C++
 	citra-qt.exe!main(int argc, char * * argv) Line 280	C++
 	[External Code]

**Comment by neobrain** [comment]
Apparently we lowered the bar for "valid" issue reports meanwhile. Reopening.

**Comment by Apology11** [comment]
@yuriks as far as I recall yes. I also thought this was fixed as I have no problems running it on my laptop with qt 5.4, but I just got home and I checked on my pc and the error still occurs with qt 5.3 there

**Comment by yuriks** [comment]
The title of this issue is wrong, it should be changed to "Rare threading-related crashes on graphics breakpoints". It's not related to Qt 5.4.

**Comment by emmauss** [comment]
if that is the real issue , i will change the title.

**Comment by JayFoxRox** [comment]
I'll close this now. If the issue comes up again create a new issue please.
