### ISSUE TITLE
Error compiling Citra

### ISSUE THREAD

**Issue by MurilloTavares** [citra-emu/citra#4470]
I got this error while trying to compile citra with `make` : 
```
Building CXX object externals/dynarmic/src/CMakeFiles/dynarmic.dir/common/crypto/aes.cpp.o
In file included from /home/murillo/Apps/citra/externals/dynarmic/src/common/crypto/aes.cpp:10:0:
/home/murillo/Apps/citra/externals/dynarmic/src/./common/crypto/aes.h:12:19: error: expected ‘{’ before ‘::’ token
 namespace Dynarmic::Common::Crypto::AES {
                   ^
```
Ps.: I used cmake version 3.13.0
and make GNU Make 4.1
on Ubuntu 16.04

**Comment by zhaowenlan1779** [comment]
That is likely because you are using an older version of GCC that does not support C++17. Please refer to [this guide](https://github.com/citra-emu/citra/wiki/Building-for-Linux) on how to compile Citra.

You are welcome to join our [Discord](https://citra-emu.org/discord) if you need any further support.

**Comment by jasonNodeX** [comment]
I just solve this by installing gcc 7 and g++-8; and symbolic linking them correctly:
sudo apt install gcc-7 g++-8
sudo rm /usr/bin/gcc
sudo ln -sr /usr/bin/gcc-7 /usr/bin/gcc
sudo rm /usr/bin/g++
sudo ln -sr /usr/bin/g++-8 /usr/bin/g++
