### ISSUE TITLE
Mario and Donkey Kong - Minis on the Move (USA) puzzle palace glitch

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#4550]
using the latest nightly 
on puzzle 9 the blue coin is only half shown
![mario1](https://user-images.githubusercontent.com/2696404/50679617-29b19a00-103f-11e9-9792-2606bbeca0b6.PNG)
[citra_log.zip](https://github.com/citra-emu/citra/files/2726346/citra_log.zip)

**Comment by benderscruffy** [comment]
it is still an issue

**Comment by benderscruffy** [comment]
still an issue

**Comment by benderscruffy** [comment]
using canary 2602
still an issue

**Comment by Dragios** [comment]
Check if PR #6945 fixes this issue

**Comment by Dragios** [comment]
![image](https://github.com/citra-emu/citra/assets/18496868/ef22acc1-1a2a-4366-acb6-072283ceb862)

The blue coin appears to be halved because the hazard block in front is supposed to partially obstruct the view, but in your case, the hazard block is entirely missing.

Have you checked whether your game ROM is a healthy dump? It appears to be functioning properly on my end. Please consider re-dumping the game and testing it once more.

**Comment by benderscruffy** [comment]
@GPUCode 
has been fixed in opengl and software 
still not fixed in Vulkan

**Comment by benderscruffy** [comment]
disable spirv shader generation in vulkan and it works properly
