### ISSUE TITLE
WWE All Stars (USA) (En,Fr,Es) stuck on loading screen

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#4580]
using the latest nightly
after the save game reminder screen it is stuck on the loading screen with the little symbol spinning
Service.FS <Error> core/hle/service/fs/file.cpp:Read:56: Reading from out of bounds offset=0x200 length=0x00000200 file_size=0x200
[citra_log.zip](https://github.com/citra-emu/citra/files/2775105/citra_log.zip)

**Comment by benderscruffy** [comment]
still happens in the latest nightly and canary
[citra_log.txt](https://github.com/citra-emu/citra/files/4269808/citra_log.txt)

**Comment by zhaowenlan1779** [comment]
Please check if this is fixed by #5120 (i.e. on latest canary), thanks

**Comment by benderscruffy** [comment]
comes up with fatal error now
![wwe](https://user-images.githubusercontent.com/2696404/76205728-cd936880-6235-11ea-8953-3363331c8d4a.PNG)

**Comment by B3n30** [comment]
The save file might be corrupt. Did you try to remove the current savefile and test it again?

Also a complete log of the new crash might be helpful

**Comment by benderscruffy** [comment]
yep sorry i deleted the save file and tested it but it came up with the fatal error

**Comment by wwylele** [comment]
Full log please

**Comment by benderscruffy** [comment]
[citra_log.zip](https://github.com/citra-emu/citra/files/4323325/citra_log.zip)

**Comment by benderscruffy** [comment]
log from canary
[citra_log.zip](https://github.com/citra-emu/citra/files/4333672/citra_log.zip)

**Comment by B3n30** [comment]
According to the canary log it searches for a file in sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/00052400/data/00000001/AWEE2011.BIN.

**Comment by B3n30** [comment]
Since the game was installed as a cia I wonder if that file was missing in the cia. But it is loaded as a savegame, so I'm not sure about this

**Comment by Dragios** [comment]
> log from canary
> [citra_log.zip](https://github.com/citra-emu/citra/files/4333672/citra_log.zip)

More like he did not delete the saves properly. He have deleted the internal game save (in this case AWEE2011.bin) but not the actual root game save folder (00052400). Which triggers fatal error.
So this is user error part. But this does look like the same problem as *Fractured Souls* in this case with failed to open without mode create.

But that is not important. The game boots just fine on my side.
![WWE All Stars](https://user-images.githubusercontent.com/18496868/80105246-def8c000-85aa-11ea-95e4-0f16e976e5e6.png)

This is definitely fixed by #5120. Can be close.
