### ISSUE TITLE
[Feature Request] Microphone support

### ISSUE THREAD

**Issue by Amnesia1000** [citra-emu/citra#4623]
Many games need emulation (either through an audio file or a real microphone) of a microphone. 
I recently finished Captain Toad's game in Citra, the one I was reluctant to finish, as I had to use the microphone and wanted to finish it entirely in Citra, which I couldn't do. 
To pass the save to the console, to pass that level, to return to place the save in the emulator, "a lot" of work for the user.
I don't know if there are more games that require a microphone, but I doubt if there are any.

**Comment by T3CHNOLOG1C** [comment]
I believe that Mario & Luigi Bowser's Inside Story + Bowser Jr.'s Journey requires the microphone as well during some of Bowser's boss fights.

**Comment by MojoJojoDojo** [comment]
> I believe that Mario & Luigi Bowser's Inside Story + Bowser Jr.'s Journey requires the microphone as well during some of Bowser's boss fights.

No its no longer required - you can use the touchscreen now.

**Comment by slashiee** [comment]
fixed as of #4671

**Comment by legend800** [comment]
Can it be mapped to a button yet or just always on or always off?

**Comment by jroweboy** [comment]
@legend800 not at this time. very much agree that citra should have this feature, but I didn't want to bloat the initial microphone support with features that aren't strictly required.

I just created another issue for it here https://github.com/citra-emu/citra/issues/4720 in case anyone has anything to add to the discussion. 👍 I'll be closing this issue now since citra has mic support.
