### ISSUE TITLE
Icon problem

### ISSUE THREAD

**Issue by Amnesia1000** [citra-emu/citra#4685]
Clicking on the names column, the icons are cut off (only in descending alphabetical order) when clicking again (ascending alphabetical order) the icons look good again, as shown in the following video

![20190310235952](https://user-images.githubusercontent.com/45115804/54098161-164de280-4392-11e9-8d2b-94dda6701629.gif)

**Comment by vitor-k** [comment]
This might have been fixed by #4896 and #4956, can you confirm if the issue persists?
From the information present here, it seems like the problem was that "add game directory" was sorted to become the first item on the list, and that would make all rows have the same height as it, because the treeview set uniformRowHeights to true.
As we no longer set uniformRowHeights to true, and "add game directory" can no longer become the first item on the list, this issue should be fixed now.

**Comment by CaptV0rt3x** [comment]
If the issue still persists, please comment below to reopen the issue.
