### ISSUE TITLE
TLOZ A link between the worlds: video freezes in a dungeon after Nightly #833

### ISSUE THREAD

**Issue by sanjab1** [citra-emu/citra#4701]
In all Citra builds after  Nightly #833 when playing TLOZ: A link between the worlds EU decrypted, when entering a dungeun picture freezes. The sound goes on., if I turn right back out of the dungeon, I hear like I exited it but the picture stays frozen, like Link had just entered the dungeon. It has happened the first time entering the Ice Palace so I downloaded older build (#833). Today I've tried with the newest build and the pictures freezes immediately after entering the Lorule Castle. I am attaching the log file.

[citra_log.txt](https://github.com/citra-emu/citra/files/2975164/citra_log.txt)

**Comment by wwylele** [comment]
Please use our [forum](https://community.citra-emu.org/) for support instead. This issue tracker is for tracking real bugs only

---

I am redirecting this issue to forum because it looks like graphics driver issue, and the nightly version bisect result makes no sense. Feel free to inform me to reopen this if it is shown this is likely a real bug.
