### ISSUE TITLE
graphic glitches in animal crossing

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#4706]
Hello everyone,

some parts (beach, buildings & city concrete) of animal crossing nl-wa have some graphic glitches when the hardware renderer is active. 

On the attached screenshot you can see on the left side the renderer is on, on the right side it’s turned off. when it’s turned off it’s unplayable for me since it runs on around 3fps. with the renderer on it runs smooth but this time with glitches.

(here is the [original issue](https://community.citra-emu.org/t/graphic-glitches-in-animal-crossing-nlwa/93538))

thank you for your time!

Operating System: macOS Mojave 10.14.3
CPU: 3,1 GHz Intel Core i5 7267U
GPU: Intel Iris Plus Graphics 650 1536 MB
Citra Version (found in title bar): Nightly 1228 
Game: Animal Crossing New Leaf - Welcome 

![Artboard](https://user-images.githubusercontent.com/31579271/54674433-b5927880-4afc-11e9-9334-12e86f3b534f.png)
[citra_log.txt](https://github.com/citra-emu/citra/files/2987462/citra_log.txt)

**Comment by khang06** [comment]
i've played acnl for a while on some recent builds on the hw renderer and it seems perfectly fine to me. maybe this is another case of macos opengl being incredibly broken?

**Comment by SmiVan** [comment]
Experiencing an identical shading issue in Tomodachi Life, and I'm on Mac as well, so yeah, this is likely macOS OpenGL being broken.

**Comment by SmiVan** [comment]
Also I think this issue can be safely renamed to "Graphical glitches on MacOS", or something more general than just animal crossing.

**Comment by SmiVan** [comment]
As of master-4efb9c6d (2019-12-03) this is no longer an issue!

Examples on Tomodachi Life (The colours are a bit different because the game changes with seasons):
![Map Overhead](https://user-images.githubusercontent.com/7703934/70098160-25ad4400-1623-11ea-9a23-55d57e4f8601.png)
![Park 1](https://user-images.githubusercontent.com/7703934/70098013-b172a080-1622-11ea-98e8-03e3dc7227ff.png)
![Park 2](https://user-images.githubusercontent.com/7703934/70098014-b3d4fa80-1622-11ea-8904-af20cfccc6c8.png)
(all of the examples above used to be plagued with pure white regions in HW) 

There is a new bug with occasional black blinking on some models, but it is different in nature, so this issue can probably be closed.

Can anyone confirm this with Animal Crossing?

**Comment by SleepingSnakezzz** [comment]
This did not appear to be an issue in the last supported Citra macOS OpenGL build. Regardless, as OpenGL for macOS builds has been dropped, this issue is no longer relevant anyways. Closing.
