### ISSUE TITLE
Nearest Neighbor Up-scaling (Specifically Text in USUM)

### ISSUE THREAD

**Issue by GameboyLuke** [citra-emu/citra#4707]
I was wondering if it would be possible to implement a feature that would upscale text in Citra (and potentially other elements) with the Nearest Neighbor upscaling method. As seen in a screenshot below, the font for the pokemon names and the dialogue is blurry since the game is upscaled but with a bicubic resizer creating a blurry product. I feel if the correct rescale method was used it would make it look more visually appealing and closer to the original.

Thanks :D

![download (24)](https://user-images.githubusercontent.com/48414726/54721057-e902f080-4b58-11e9-8b2a-b42354079dae.png)

**Comment by BrysonHowell** [comment]
If this were to be implemented, would it be better for nearest neighbor up-scaling be applied to all images or just text/pixel art? I've looked into this a bit, and there are advantages and disadvantages to both methods. Maybe it would be best to introduce a setting that allow users to pick the up-scaling method they prefer.

**Comment by legoj15** [comment]
Selecting specific textures for nearest neighbor/no filter scaling is something that would require a non-trivial amount of effort. Dolphin has a setting to force filtering for all textures (and on the other hand, Ishiruka has a setting to force nearest neighbor for all textures). If those settings could be incorporated in a way that makes sense, I feel that that would be enough (since pokemon games are already "pixelated", having everything use nearest-neighbor wouldn't look too bad IMO)

**Comment by gameboycjp** [comment]
Having a drop-down with different texture filtering options would be really cool.

**Comment by poesdelal** [comment]
Even with "Enable linear filtering" option unchecked only part of textures and text looks sharp but others still looks blurry (like text in Pokemon on that screenshot)

**Comment by wwylele** [comment]
The recently added "Enable linear filtering" option is for post-processing part of the renderer where the final screen content is blit to the window. It has nothing to do with the internal texture filtering.
