### ISSUE TITLE
SBS 3D Does Not Properly Show 3D Effect in 2D Games

### ISSUE THREAD

**Issue by shinra358** [citra-emu/citra#4711]
SBS 3D works but for 2D games, 3D does not work. Games like Streets of Rage 3D and Altered Beast 3D and sprite games of the like are flat. They have no 3D effect.

**Comment by wwylele** [comment]
Do they have 3D effect on real 3DS?

**Comment by shinra358** [comment]
yes. thats why they are call SoR3D and Altered beast 3D 😋.  I believe
citra uses it's own doubled image instead of using the doubled image that
the 3ds actually uses. that's why majora's mask's 3d looks better on citra
than on the real 3ds. I believe this is also why the 3d classic games dont
show properly in 3d.

**Comment by wwylele** [comment]
No, citra doesn't generate it's own double image (because it can't magically do that). Citra do use the double image in the same way as 3DS (or at least is supposed to). I want more info about these games. For example, do they have continuous depth change depending on the 3D slider, or they can be only turning on or off, where there is a threshold to the 3D slider?

**Comment by shinra358** [comment]
yes, the 3d is dependent on the slider just like the rest of the other
polygonial type games. It's not just on and off.

**Comment by wwylele** [comment]
Could you provide log?

**Comment by shinra358** [comment]
Had more time to test out a few games. Seems like i was mistaking. The couple games I tried the first time don't work properly in 3d because it seems that the emulation isnt perfect. Particular game has a few missing sprites. Most of the other 2D 3D games work fine in 3D. So I;ll just close.
