### ISSUE TITLE
[Feature Request] render each screen at a different internal resolution

### ISSUE THREAD

**Issue by nathanhitch** [citra-emu/citra#4745]
there should be an option to change what resolution the primary and secondary screen are rendering at with an option to disable rendering on the secondary screen.

**Comment by wwylele** [comment]
This is almost technically impossible. Before the final buffer swap (when all screen contents are already drawn), citra has no idea what the game is drawing on, because drawing on any buffer is in the same form of commands. Sure you can argue that citra can learn some patterns after some buffer swapping, but this start to become applying an AI solution to an inessential problem, whose cost and complexity introduced don't worth it.

**Comment by nathanhitch** [comment]
damn oh well
