### ISSUE TITLE
flatpak build failing on citra-nightly

### ISSUE THREAD

**Issue by abrielparyunu** [citra-emu/citra#4784]
The Flatpak build of citra-nighlty has not been working for about a month.

https://travis-ci.org/citra-emu/citra-nightly/builds

The build always last 50 minutes and the error reported is:
```
The job exceeded the maximum time limit for jobs, and has been terminated.
```

The last successful build nightly-1255 lasted about 42 minutes.

nightly-1256 (the first that fails from this error) has the following text:
```
nightly-1256 Merge pull request #4755 from B3n30/revert_erase_erase_me
linux-flatpak: revert use precompiled cache 
```

Also the travis badges on citra-nightly and citra-canary README.md are not pointing to the correct travis page.
Also where is the job for the citra-canary flatpak build mentionned in https://flatpak.citra-emu.org/ ?

**Comment by IceWreck** [comment]
Yes. The Linux builds are stuck on 1255. I can't update to a newer nightly.

**Comment by abderrahim** [comment]
The problem is that the flatpak runtimes that are used in the [docker images](https://github.com/citra-emu/build-environments) are from April. There was a bug in the flatpak runtimes that led to the compilers being unoptimized, and that's why builds take so long.

This has since been fixed, so regenerating the docker image should fix this issue.

@chris062689 You seem to be the one responsible for that citra-emu/build-environments, can you trigger a rebuild of the linux-flatpak image?

**Comment by SleepingSnakezzz** [comment]
Whilst this is ironically an issue at the moment with the flatpak builds. This specific issue has long since been fixed.
