### ISSUE TITLE
[RetroArch Core] [iOS] With OpenGL 3.3 available, is an iOS RetroArch Core still buildable?

### ISSUE THREAD

**Issue by appleguy** [citra-emu/citra#4843]
_I'm willing to poke around some sharp edges if this path is slightly bit-rotted. If there is a technical section of the community forum I should be asking this in, feel free to close and send me there._

I have a full-source build of RetroArch and ~50 cores running on my iOS devices, and my understanding is that Citra has been built on this platform at some time in the past.

Is it still possible to do such a build manually, or is there an archived version of the official / mainline Citra iOS .dylib before the Darwin / OS X support was formally dropped? I can absolutely understand the frustration with OpenGL being deprecated on OS X (an insane decision IMO, even as an ex-employee). Are there also OpenGL features lacking on iOS that are core to Citra's renderer?

Motivation: the A12X is a technically killer CPU, and RetroArch runs well on both an AppleTV 4K (A10X) and an iPad Pro (A12X). These would be insanely good Citra machines if it were possible to get the build working.

Imagine the sheer delight to see Citra in this list, on a pretty sizable range of mobile and living room devices! Of course, open to learning that this is technically impractical, though I couldn't find that info in the FAQ / forums. 

![image](https://user-images.githubusercontent.com/565251/61359027-6fda8800-a830-11e9-8a2f-bd7cb5500378.png)

**Comment by wwylele** [comment]
First of all, the citra libretro core is not maintained officially here, and I haven't heard of core on iOS. Please reach out to the libretro team about the core. If anything were planned here, it would be a standalone iOS app.

OpenGL is probably not the biggest technical issue (in the worst case, people rewrite the renderer in a  new engine). The hard part is iOS restriction on JIT, which contributed a lot to achieve the good performance on PC.

Citra android is still on its way. We might want to get some mobile app development experience there first, before considering iOS.

**Comment by appleguy** [comment]
Got it, thanks! I hadn't realized the libretro core was owned separately — that's a bummer, I hope it's not an "unwelcome fork" situation (mad props to Citra for remaining open and principled despite that).

Android sounds great too, and it's good to hear that is an active area.

Regarding JIT, I've had the lacking JIT entitlement in mind as a definite restriction for any version that might run on iOS. I think it would require a high-end SoC to be reasonable to run in interpreted mode, but it seems plausible (IMO, could be wrong) that an A12X would handle this quite effectively. Definitely not efficient, but I think there's a good chance it would be fast enough.

Feel free to close this if no one else has similarly-helpful comments or references; I'm satisfied with this answer and appreciate that you took the time. That said, I'm definitely interested in learning more about the Citra engineering community and plans, especially Android / iOS, if anyone wants to share.

**Comment by 7androidlinuxhg** [comment]
please do not support iOS. Apple platform is not good.

I found this. https://github.com/weihuoya/citra/pull/1#issuecomment-544917226

`

    Create Citra iOS plss and thank you. I have an iPhone 11 and iPad Pro 2018.

    Maybe on iOS better performance?

No thanks.

iOS is very limited for users. And generally you as a user does not own the iPhone.

Because the software is bound to Apple. Here iPhone users have discovered the limitation of iOS.
https://forums.macrumors.com/threads/ios-is-terrible-about-privacy.2205813/

You can't set up and use iPhone offline. You always have to do an internet activation in the setup window first. If you reset the software, internet activation is required again. This also applies to the iPad, iPod touch, Apple TV and Apple Watch.

Also when installing apps (locally installed by PC) you have to connect to the App Store the first time you start it. You are completely bound to Apple. Offline use is not possible.

-- my $150 or High-End Android device does not have this limitation. Can always set up and use offline.

The worst thing is if Apple shuts down the servers then you will never be able to use the iOS devices again.

Not to forget, iOS has a built-in remote keylogger from Apple. Every keypass is sent to Apple server (so the users say in the forum).

In general, developers for emulator don't like iOS. It is extremely limited and always set against the user. Example see iNDS. An emulator on iOS for DS games, very bad performance and many bugs. no updates since years.

Best Citra iOS will never appear, because iOS is a harmful platform for developers and users. not worth any support.

It is better to support Android or Android without google service than iOS. Users always benefit first and it is the most sustainable solution.
`

**Comment by CaptV0rt3x** [comment]
Closing, as it is far out of scope.

**Comment by cccRaim** [comment]
Any plan for Citra iOS?
iOS 14.2 is support JIT now. [link](https://9to5mac.com/2020/11/06/ios-14-2-brings-jit-compilation-support-which-enables-emulation-apps-at-full-performance/)
And `Altstore` is easy to install ipk file.

**Comment by OhNoImBroken** [comment]
if anyone is still interested in this, citra  can be built for ios. i've done it. but i cannot get opengl to work
@cccRaim @appleguy

**Comment by OhNoImBroken** [comment]
there are  ways to do this, we need to find a group of people who aren't elitists and hate apple for the sake of hating apple
