### ISSUE TITLE
Android: Implementing JIT compiler/assembler

### ISSUE THREAD

**Issue by bamsbamx** [citra-emu/citra#4909]
The currently extisting Citra for Android repositories make use of `dyncom ` interpreter. Seems like this is happening due to lack of `dynarmic and xbyak` support for ARM64.

Just wanted to discuss with you before I start working on implementing an ARM64 JIT compiler/assembler, to know your opinion, or to know where should I start from.

1. It seems to be an already working JIT compiler developed by ARM and called `VIXL` (see here: [https://git.linaro.org/arm/vixl.git/tree/](url)) which supports both `aarch32 and aarch64`

2.  The other option is to fork `xbyak` and implement aarch64 support

Which option you think is easier/more appropriate? Any other way?

**Comment by bunnei** [comment]
Hi @bamsbamx - Thanks for your interest here. We actually have plans to release an ARM64 backend for Dynarmic sometime in the coming months. I'd suggest that you discuss with us on [Discord](https://citra-emu.org/discord/) if you are interesting in helping out.

**Comment by jroweboy** [comment]
A few things to note: VIXL is not a JIT compiler, its an ARM emitter, which is only one piece of a full JIT. Second: dynarmic already has an aarch64 emitter on a feature branch, so thats not the issue at all. Writing a full ARM backend for dynarmic just takes time and someone skilled enough to do it, and we ask you to be patient until we are ready to release it. As bunnei said, theres plenty of places to help out in otherwise, and we'd love to have you contribute <3
