### ISSUE TITLE
Almost ALL the Sega Ages games like "Thunderblade" and "Outrun" crash upon start. Please fix?

### ISSUE THREAD

**Issue by retr0man** [citra-emu/citra#5081]
Sadly, the Sega Ages games like Sega Ages Thunder Blade and Outrun will crash when trying to start the game. Basically, the games will let you get into the menus but that's it.
For collectors, these games are a real find as they are enhanced/extended version of the original games faithful to the original. Alas, almost ALL of them fail to proper load.

Could someone look into this?

**Comment by jroweboy** [comment]
Hello there! Just to be sure, I think you are referring to Sega 3D Classics Collection, right? I did a little investigation into the game, and found the cause of the crash is a recent regression from a change of mine, and I've fixed that first crash. The second problem seems to be a little more complicated though, the 3D classics collection is actually a collection of 3ds "exe"s and when you launch a game, the game menu will tell the home menu that it should load one of the subgames and exit. The problem is unless you install the game as a CIA file, none of those sub games will come along with it, so it won't relaunch correctly and it just reloads the menu again. I'm not sure yet what to do about this, or if its possible to somehow load the subgames inside of the other container formats that aren't installed.

**Comment by retr0man** [comment]
> Hello there! Just to be sure, I think you are referring to Sega 3D Classics Collection, right? I did a little investigation into the game, and found the cause of the crash is a recent regression from a change of mine, and I've fixed that first crash. The second problem seems to be a little more complicated though, the 3D classics collection is actually a collection of 3ds "exe"s and when you launch a game, the game menu will tell the home menu that it should load one of the subgames and exit. The problem is unless you install the game as a CIA file, none of those sub games will come along with it, so it won't relaunch correctly and it just reloads the menu again. I'm not sure yet what to do about this, or if its possible to somehow load the subgames inside of the other container formats that aren't installed.

Thank you for looking into this!

To answer your question: the games I am referring to are BOTH in ONE collection and exist as separate stand-alone games. With what you revealed in your inquiry, though, I wonder if BOTH the collection you cited AND the stand-alone games use that same annoying game menu interface to access the exe files you mentioned.

**But you are saying I can install the game as a CIA file? Guess I can try that.**

P.S. Still hoping there is a fix somewhere here that can make the game work.

**Comment by M2GameDeveloper** [comment]
Most Sega Ages Games like Sega Ages Thunderblade crash AFTER the intro menu loads. Start Button triggers crash after games hangs for a few seconds. Unable to progress past the Start Screen.

System Information
Windows 10 Pro
Intel i7-4790k 4 cores
NVIDIA GeForce RTX 2070
Citra Nightly 1629
3D Thunder Blade

Here is the latest citra_log file:
[citra_log.txt](https://github.com/citra-emu/citra/files/5412350/citra_log.txt)

**Comment by M2GameDeveloper** [comment]
Could someone please look into this? I've been asking for help for two years now, no fooling. It's Sega's 60th Anniversary and I was hoping to preserve these games I helped programmed for consumers on my hard drive for preservation purposes, to go into a museum of sorts. Any help would be appreciated. Thank you!

**Comment by Dragios** [comment]
You better just chimed into the Discord #development chat for any enquiries. As far as I know, most of the core developer is currently in hiatus mode for Citra development.

https://discord.gg/FAXfZV9
