### ISSUE TITLE
(Puzzle & dragons Z - Super Mario Edition) - Grey health bars on ennemies

### ISSUE THREAD

**Issue by Pwalafrir** [citra-emu/citra#5139]
![issueGreyBar](https://user-images.githubusercontent.com/62569752/77357249-1e33b700-6d48-11ea-9e86-25249168845e.png)

Citra Nightly 1444 (also tested on Canary 1607 FYI)
i5-7300HQ
GeForce GTX 1050
8Go RAM
[citra_log.txt](https://github.com/citra-emu/citra/files/4371623/citra_log.txt)

Ennemies health bar stay completely grey instead of a green bar decreasing as they take damage. Found out that issue is resolved when Hardware Renderer isn't enabled, but it makes the game unplayable as it then runs at like 2FPS.

**Comment by Schplee** [comment]
PR #3910 seems to have caused a regression. Health bars are now black. Screenshot and log from "RetroGameReaper" on Discord:

![image](https://user-images.githubusercontent.com/24275329/102323412-4f3ac400-3f35-11eb-8183-f0f758457923.png)
[citra_log.txt](https://github.com/citra-emu/citra/files/5701286/citra_log.txt)

Issue #5563 shows a similar problem

**Comment by vitor-k** [comment]
@Schplee I think you misunderstood "RetroGameReaper" on the black bars, that screenshot is probably from nightly 1249

> No health bars in this one. It's actually black unlike the grey in the current build.

On the current build health bars should be grey, the color of the background of the health bar. That is because the texture errors and becomes null and the current behaviour for it is to use a clear texture as of #4844, previously it was black.

As for why it stopped working after #3910: the texture size is smaller than 8x8, and the special case that handled these (7f1aec8fbb96b5c29c91332250eef60dff4c8f12) was removed in that PR.
According to wwylele:
> The original code that deals with texture with unaligned size is removed because PICA simply doesn't support this.

The same explanation should apply to #5563. Here, the textures are 8x4, while there the textures are 4x4, but the problem should be the same.
Also kudos to RetroGameReaper for the more complete log file, it helps to pinpoint the problem and may help someone investigating in the future.

**Comment by Amnesia1000** [comment]
I have the same problem. I know they are currently slowing down Citra updates, but I hope they can fix this problem soon.

**Comment by emihead** [comment]
Just here to say that I'm having this issue too. Would be amazing to be able to play this game on a more recent version but health bars are critical.
