### ISSUE TITLE
"Preference" Window OK button unreachable Mac OS

### ISSUE THREAD

**Issue by PyrDeus** [citra-emu/citra#5212]
The "Preference" window for Citra (on Mac OS) is y size fixed when you want change on "Controls" and the "OK" button go outside the screen.

<img width="1438" alt="Capture d’écran 2020-04-15 à 16 57 23" src="https://user-images.githubusercontent.com/49350315/79352979-c77e5f00-7f3a-11ea-89e8-3e8b3b2b4854.png">

<img width="1440" alt="Capture d’écran 2020-04-15 à 16 58 06" src="https://user-images.githubusercontent.com/49350315/79353110-e977e180-7f3a-11ea-8bad-4aecc33b7ff9.png">

**Comment by TheBros35** [comment]
Can confirm this issue as well - it looks like due to the fact that the on screen controls boxes are confined to sit in a 2x3 grid, and also the grid boxes stay too "tall" upon resizing, when visually there is room to compress the items. This is as "short" as I could make the window with the control box opened. Tested on [db5b8b9](https://github.com/citra-emu/citra-nightly/commit/db5b8b9).
<img width="990" alt="Screen Shot 2020-04-21 at 4 24 01 PM" src="https://user-images.githubusercontent.com/3393068/79910367-95fb0d00-83ec-11ea-85a9-bebf330119ce.png">

**Comment by patrickmetz** [comment]
Same here.  I'm on a M1 MBAir with Big Sur 11.5.2.

At least the OK button becomes visible and usable, when I double click the window title.
