### ISSUE TITLE
Rhythm Heaven Megamix - Music desyncs behind sfx

### ISSUE THREAD

**Issue by oddMLan** [citra-emu/citra#5265]
Using Citra version 38c3c9c74b704050d72e397feb290db2e616209a

With #5195 merged the AAC audio playing at double speed during the minigames was fixed but the visuals in Rhythm Heaven Megamix are still out of sync with the audio. The music is behind the visuals by approx. half a second. I'll attach a webm showcasing the issue but it might be difficult to see if you're not musically inclined. 

https://cdn.discordapp.com/attachments/277545856033488897/702346763071127612/test-0.webm

~~LLE does not seem to have this desync issue (but it's hard to tell since it runs at 10 FPS on my computer).~~ Someone else confimed the issue exists in LLE as well, in an older Citra version
https://www.youtube.com/watch?v=OkSqY7yetsM

This is how it plays in real hardware
https://www.youtube.com/watch?v=lj05yKAYmZQ

I think the desync is caused by the short audio hiccups you hear in my footage.

**Comment by xperia64** [comment]
I did some testing of this. With the current build I have personally, I can say that compared to hardware, the background music tracks of games get about ~2ms ahead of hardware in a ~1 minute song. The gameplay (sound effects, button prompts, visuals, etc) however ends up almost 250ms ahead of where it should be depending on the game.

I can confirm this drift is an issue with both HLE and LLE, and that both backends drift on the side such that the gameplay gets ahead of the music track, although at slightly different rates.

**Comment by Chocolate2890** [comment]
Can confirm this is a problem as well. It makes the game barely playable. I'm not sure why this happens but I hope it gets fixed.

**Comment by xperia64** [comment]
After some testing, I believe this issue is possibly related to https://github.com/citra-emu/citra/issues/4169 and https://github.com/citra-emu/citra/issues/4527, but NOT https://github.com/citra-emu/citra/issues/4562, at least under HLE. In Theatrhythm, the gameplay does indeed get ahead of the music by quite a bit, but I've mostly noticed it desyncing suddenly during transitions in Theatrhythm, so it may be different, and not a smooth desync over time like here.

**Comment by oddMLan** [comment]
Thanks for the fixes. It is much better now. But now there is a lot of crackling that wasn't there before.
[crackle.zip](https://github.com/citra-emu/citra/files/4773319/crackle.zip)

**Comment by xperia64** [comment]
How did you record this? Is the crackling there if you use the "Dump Video" feature?

**Comment by oddMLan** [comment]
There is no crackling, but the audio still sounds messed up. libvpx and libvorbis
Also it seems that the video is a little behind the audio too.
[test.zip](https://github.com/citra-emu/citra/files/4773351/test.zip)

**Comment by xperia64** [comment]
Please open another issue for this. As the recording is correct, it's a frontend problem.

As for the video being behind the audio, that happens when starting the recording in the middle of a game sometimes.

**Comment by realguystuff** [comment]
Hello, I am aware that I am a bit late, but I can still confirm this is happening on the latest Citra. (To be honest, the other minigames are in sync, but some are not.) In Flock Step, it was making my gameplay almost unplayable, and I am sure because I played this on a real 3ds until the owner moved out.

**Comment by oddMLan** [comment]
Yes unfortunately, I believe somehow the fix got reverted or broken by a new commit.
It never worked on Citra Android either.
LLE is unaffected. To me it seems like a AAC decoding issue, judging by the loud static that plays before each minigame.
