### ISSUE TITLE
[Feature Request] Add Nearest Neighbour filter for textures

### ISSUE THREAD

**Issue by xperia64** [citra-emu/citra#5274]
Since texture filtering has been added, I believe it would be an enhancement to allow enforcing Nearest Neighbor filtering/disabling bilinear filtering on textures if possible (not just the final render output as was mentioned in #3556). It may improve the results of some of the scaling/filtering algorithms included, and may help make some things look sharper at higher resolutions.

**Comment by Anapan8** [comment]
I came here to request this as well.  I was able to fix Cave Story 3D's blurry text and weapon effects by dumping textures, batch-resizing them 800% - nearest neighbor and custom loading them.  The result is a much better experience, tho I will have to play through the entire game in order to make the fix complete, and transferrable.
