### ISSUE TITLE
Citra Nightly 1535 - Issues with multiplayer in Inazuma Eleven 1-2-3, and Inazuma Eleven 3

### ISSUE THREAD

**Issue by ObludaIE** [citra-emu/citra#5339]
Multiplayer play doesn’t work in Inazuma Eleven 1-2-3, I think I can see my opponent for a split second but it disappears too fast. We are connected to the same room, and it worked in other games.
Here's the log : `https://community.citra-emu.org/uploads/short-url/cJjXmY4Gl0floqarx7dJ9Sb7UTx.txt`
I think it has something to do with the unimplemented functions errors, at the bottom of the log.
I can give you my save file if you want to test it

**Comment by houlaidahamada** [comment]
It says `[ 114.761461] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:161: unknown / unimplemented function 'ReplySleepQuery': port='APT:U' cmd_buf={[0]=0x3e0080, [1]=0x300, [2]=0x0}` ,  `[  31.349361] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default` and `[  41.666208] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:161: unknown / unimplemented function 'SetProbeResponseParam': port='nwm::UDS' cmd_buf={[0]=0x210080, [1]=0x321f00, [2]=0x0}` so the issue seems to be coming from these unimplemented functions

**Comment by ObludaIE** [comment]
It says `[ 114.761461] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:161: unknown / unimplemented function 'ReplySleepQuery': port='APT:U' cmd_buf={[0]=0x3e0080, [1]=0x300, [2]=0x0}` ,  `[  31.349361] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default` and `[  41.666208] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:161: unknown / unimplemented function 'SetProbeResponseParam': port='nwm::UDS' cmd_buf={[0]=0x210080, [1]=0x321f00, [2]=0x0}` so the issue seems to be coming from these unimplemented functions

**Comment by ObludaIE** [comment]
Same thing for "INAZUMA ELEVEN" , all of these games are DS """remakes""", I guess that's the probem

**Comment by ObludaIE** [comment]
I did another test, this time with Inazuma Eleven 3, same result
[citra_log.txt](https://github.com/citra-emu/citra/files/4800162/citra_log.txt)

**Comment by ObludaIE** [comment]
Sorry, I pressed the wrong button

**Comment by JakoDel** [comment]
Still nothing huh? I really wanted to play the European version of ie3 with my friend :/

**Comment by SleepingSnakezzz** [comment]
This issue appears similar to this one https://github.com/citra-emu/citra/issues/5122

**Comment by obluda3** [comment]
No, they're not the same at all.

**Comment by JakoDel** [comment]
bump?
I guess this is going to be forever ignored. not that I can complain, citra is amazing, thanks to the devs! this does suck a fair bit though
