### ISSUE TITLE
Fatal error in pokemon y

### ISSUE THREAD

**Issue by Jaygraham0000** [citra-emu/citra#5383]
Whenever I open pokemon y on citra it gives me a fatal error. I have gone through the steps several times from the main page to debug it but it hasnt worked. after the steps it says if it doesnt work, file a bug report. 

the issue was in 0xA0002 for me.

**Comment by tywald** [comment]
If you are 100% sure you already tried deleting the `config` file at `nand\data\00000000000000000000000000000000\sysdata\00010017\00000000` when Citra was closed and you still get config block issue then upload a log

**Comment by Jaygraham0000** [comment]
[citra_log.txt](https://github.com/citra-emu/citra/files/4708170/citra_log.txt)

**Comment by tywald** [comment]
Ok, I want to double check.

Download a stand alone build at https://citra-emu.org/download/ by clicking on "Manual download" and extract it somewhere that is not related to your current Citra installation, e.g `C:\testfolder` then inside where its `citra-qt` is, create a new folder called `user`. This will make this build use its own settings which will make testing easier.

Now open this build's `citra-qt` and it should look like that Citra has reseted, immediately try start Pokémon Y and see if you still get a fatal error.

**Comment by B3n30** [comment]
I'm sorry to interrupt this support, but: This is an issue tracker for development and this clearly isn't any issue since 0xA0002 is the language block which is generated when the config file is generated. So there must be a mistake by Jaygraham0000 in deleting/resetting the config save game. so I suggest to move this to support in either discord or the forums
