### ISSUE TITLE
Wrong linear memory base for 3DSX

### ISSUE THREAD

**Issue by TuxSH** [citra-emu/citra#5443]
Citra only works because libctru/nnsdk code is robust enough to handle this, but 8.x+ titles have 0x30000000 as linear mem base instead of 0x14000000.

Relevant kernel function:

```cpp
u32 __fastcall KProcess::GetLinearAddrRangeBase(KProcess *this)
{
  u32 result; // r0

  if ( (this->capability.kernelFlags & 0xF00) == 0x300 || this->capability.intendedKernelVersion >= 0x22Cu )
    result = 0x30000000;                        // base sysmodules, or 8.x+ titles.
                                                // 
                                                // This code is common to O3DS/N3DS
  else
    result = 0x14000000;
  return result;
}
```

**Comment by wwylele** [comment]
Citra has already implemented linear memory base switch (or is supposed to) at
https://github.com/citra-emu/citra/blob/c605bb42dbb364cc0977c417aed0630d74b05c25/src/core/hle/kernel/process.cpp#L182

**Comment by wwylele** [comment]
If you tested citra with 3dsx, the issue is that citra assign `kernel_version = 0` when loading 3dsx (and therefore always use the old linear base).

**Comment by TuxSH** [comment]
> If you tested citra with 3dsx, the issue is that citra assign kernel_version = 0 when loading 3dsx (and therefore always use the old linear base).

libctru was publically released after 8.x kernel was released. Given that you're now trying to support the N3DS mode, I think it would make more sense to always use the new mapping for 3dsx.

**Comment by wwylele** [comment]
I changed the issue title to reflect that this is specifically for 3dsx.

**Comment by wwylele** [comment]
What kernel version does 3DSX program inherit on 3DS? If I run homebrew with an old entry point (e.g. oothax), would the kernel version be as old as OOT specified?

**Comment by fincs** [comment]
3DSX is the standard homebrew application format, officially supported by devkitPro's toolchains and libraries. It is not used with "old entrypoints", it is in fact the recommended best-practice format for homebrew, loadable by Luma3DS's custom Rosalina system module. Luma3DS of course configures a recent kernel version in the simulated exheader in order to have access to the 0x30... memory region.

**Comment by TuxSH** [comment]
With Rosalina, 8.0 kernel, recently changed to [current kernel version].

> would the kernel version be as old as OOT specified?

Yes, but it doesn't matter as libctru has always handled both mappings. On the other hand, as @fincs said, not having the 0x30000000 mapping prevents you from using more memory on N3DS (insufficient VA space).

For simplicity, you should assume that intendedKernelVersion = latest kernel version, o3ds_memtype = O3DS_PROD, n3ds_memtype = N3DS_PROD

**Comment by wwylele** [comment]
> 3DSX is the standard homebrew application format, officially supported by devkitPro's toolchains and libraries. It is not used with "old entrypoints", it is in fact the recommended best-practice format for homebrew, loadable by Luma3DS's custom Rosalina system module.

I smelled something in your tone, so I want to clarify on the potential misunderstanding. 

By 
> If I run homebrew with an old entry point, 

, I meant
>among all possible ways I knew to run a homebrew app (including all kinds of *hax and rosalina), let me just pick one as example (for the reason I have used it and am more familiar with it), could you explain to me how the kernel version is assigned?

, *instead of*
>since 3DSX is meant to be used for old entry points (and modern apps should use cia (???)), you should explain how the kernel version is assigned with old entry point and we should only implement citra in that way

.

The second thing I learned from your message is that 3DSX is not meant to be used for old entry points any more, which is a runtime specification change from what was when citra was created and when 3DSX support was initially added. It is an important message that needs to be spoken clearly so that citra can make change accordingly, which is the reason I have asked for more detail on the specification/mechanism for 3DSX on 3DS.

**Comment by fincs** [comment]
I think I missed a word here: "It is not *just* used with old entrypoints". Currently the only old entrypoint we still sort of support is hax 2.x, however we're considering dropping support for it since people should be running Luma3DS anyway.

Old entrypoints leave the underlying exheader settings undefined by their own nature, as they recycle existing processes to run homebrew code on top of. It could be very old official games, or newer post-8.x games. This is all irrelevant now anyway. The point @TuxSH and I tried to make is that ideally, running 3dsx on Citra should enable all benefits that come with newer games, including the new FCRAM memory mapping, as well as (for example) core2 access on New3DS.
