### ISSUE TITLE
Not writing to amiibo binary file

### ISSUE THREAD

**Issue by blonghong** [citra-emu/citra#5492]
**Game**: Hey! Pikmin
**Amiibo**: Link removed by moderator

**What should happen:**
In Pikmin Park, I load my amiibo, and it saves data to the amiibo. I can then use that amiibo during a level to call for Pikmin

**What happens:**
In Pikmin Park, after loading it _claims_ to have written to the amiibo, asks me to remove, and then upon trying to call for Pikmin during a level, an error occurs. The amiibo .bin file of course has not been modified at all.

**Comment by celerizer** [comment]
Citra doesn't support AppData or writing back to an amiibo. I was working on this on a fork and could probably PR it soon, but it requires you to decrypt your own amiibo dump (the one you link is encrypted, and probably illegal to be linking to :P).

https://github.com/celerizer/citra/tree/amiibo_appdata

**Comment by Shideravan** [comment]
@celerizer Sorry to bother you, but there any news about the writing feature? I'm need this for using in Chibi-robo Zip-lash (It's sad that I have own the game and the amiibo since the release, but unfortunatelly my old 3DS don't have native support for NFC, no way to get 100% in my console - such a nasty strange "paywall" to say the least). Also would be nice to use my amiibos in Smash 3DS (well, there's a lot of applications to amiibo writing to say the truth). If I can help in some way (testing for exemple), I'm up to help in anyway that I can :)

**Comment by HackMeMan** [comment]
Is this feature even considered by the devs? Is it that hard to implement, or is there something more important being worked on? Can you please inform me? @celerizer
