### ISSUE TITLE
Citra crashes on Linux when opening the rom

### ISSUE THREAD

**Issue by donielix** [citra-emu/citra#5560]
**Issue**: 
As soon as you try to open the game, the program just crashes. This happens only when I have activated the option "Enable hardware shader", and I think it might be something related to OpenGL drivers

**System Information**
* Operating System: Ubuntu 20.04 LTS
* CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
* GPU: GeForce GTX 950M
* Citra Version: Citra Nightly 1618
* Game: The Legend of Zelda: Majora's Mask

[citra_log.txt](https://github.com/citra-emu/citra/files/5269003/citra_log.txt)

In addition, when I run the program from flatpak in the terminal, when it breaks it returns the following on-screen message:

/usr/include/c++/9.2.0/optional:438: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = OpenGL::ShaderDecompiler::ProgramResult; _Dp = std::_Optional_base<OpenGL::ShaderDecompiler::ProgramResult, false, false>]: Assertion 'this->_M_is_engaged()' failed.

**Comment by Pik-a-boo** [comment]
Only the flatpak is like that

If you compile from source then it wont crash.

**Comment by donielix** [comment]
And why are not fixing such a known issue the new incoming flatpak versions?

**Comment by nmousouros** [comment]
For me it worked after I desabled hardware acceleration ( actually the box below )

**Comment by Ahmed-E-86** [comment]
> Only the flatpak is like that
> 
> If you compile from source then it wont crash.

Citra can be installed as a Snap, and it works just fine.

**Comment by TheGreatestJannet** [comment]
Same issue here. Disabling hardware shaders fixes for the time being.

**Comment by HenriqueAD7** [comment]
(System - Pop!_OS 20.04 - )

I also had the same problem. However, I realized that there were some problems with other emulators, such as GNOME Games.
In the end after updating my Nvidia video driver, for GTX 1060, to version 455.28, the same thing didn't happen anymore.

Soon, in my case, I discovered that the problem was the 450 series video driver and not the Citra Flatpak.

Detail, the same problem occurred with the precompiled version. After updating the driver, as described above, there were no further problems.

**Comment by TheGreatestJannet** [comment]
I am on 455.28 and a GTX 1060 too as it still crashes.

**Comment by EliaGeretto** [comment]
The fix is in #5561.

**Comment by TheGreatestJannet** [comment]
Any reason it hasn’t been merged yet? This is a pretty major issue.

**Comment by gal20** [comment]
Fixed with #5608.
