### ISSUE TITLE
High Memory Usage on Citra 1627 causing the program to crash?

### ISSUE THREAD

**Issue by Algester** [citra-emu/citra#5569]
This is with playing Story of Seasons: Trio of Towns where the character model would just T-Pose as a sign that the game is starting derp
![ass](https://user-images.githubusercontent.com/6236070/94906238-b2898e00-04d0-11eb-829a-73c9bafdd4ad.png)

**Comment by Algester** [comment]
[citra_log.txt](https://github.com/citra-emu/citra/files/5316917/citra_log.txt)

**Comment by Algester** [comment]
I can't test further but it seems that downgrading to 1609 which was the last "stable" version I was from worked flawlessly for now

**Comment by SleepingSnakezzz** [comment]
You have a ton of unmapped read spam in your log. That usually indicates a badly edited rom, a faulty cheat or a corrupted rom. Please try this:
1. Disable cheats.
2. Restart citra (otherwise the cheats remain active).
3. Now see if the crash still occurs.
4. If the crash still occurs, upload another log.

**Comment by Algester** [comment]
will do

**Comment by SleepingSnakezzz** [comment]
This doesn't appear to be a Citra related problem, and should've honestly been handled as a support request on the Discord server or the forums, not an issue tracker for development. Closing.
