### ISSUE TITLE
[Feature Req] Force Username in the cfg ?

### ISSUE THREAD

**Issue by soaresden** [citra-emu/citra#5783]
Hi everyone, 
I asked discord about my feature but couldn't find any useful piece of informations ...

I would like to know where on the cfg file can I get/edit my username ?
i tried some values in the [system] but seems to not work
![image](https://user-images.githubusercontent.com/54243866/117569358-9b91c680-b0c5-11eb-8b86-5789f9586717.png)

I would like to simply be able to Edit manually my Username in the config file if it's possible ?
Thanks !
![image](https://user-images.githubusercontent.com/54243866/117569375-b3694a80-b0c5-11eb-98ee-11af66384e0d.png)

**Comment by B3n30** [comment]
This shouldn't belong here since this is a develop issue tracker.

But I give you some short information: Those are system settings that are stored in the cfg savegame (3ds internal). If you want to edit it by hand you need to edit that savegame (e.g. with an hexeditor). For the exact location of the username entry you can have a look at https://www.3dbrew.org/wiki/Config_Savegame

But nevertheless I will close this and for further questions please ask in discord
