### ISSUE TITLE
State issue

### ISSUE THREAD

**Issue by SoloBackup** [citra-emu/citra#5899]
Hello. 
I'm using citra on windows 11.
I noticed that unlike other emulators (like dolphin, pcsx2 and others) citra creates a file for each time you click on save state hotkey, resulting a creation of too much files of states.
The other emulators just create a file and that is replaced every time you use the save state feature. This issue could be fixed? Because as at the end of a big game, a few gigabytes of save state files would accumulate each time you press the save button.
![image](https://user-images.githubusercontent.com/84431888/144909527-f5560bcc-fa8a-4001-b826-cf16f25b02b5.png)

**Comment by vitor-k** [comment]
> at the end of a big game, a few gigabytes of save state files would accumulate each time you press the save button.

That wouldn't happen because it's limited to 10 save states, after it reaches the 10th it will circle back to the 1st.
You can choose to save to a specific slot by using the menu (emulation > save state), and see the aforementioned slots.
The hotkey is specifically called "Save to oldest slot", so it will save  to a new slot if one is available or to the oldest slot based on the timestamp.

**Comment by SoloBackup** [comment]
Thanks for the answer, now with this information i understand how this works. Thank you very much.
