### ISSUE TITLE
Feature Request: At least try to add Vulkan

### ISSUE THREAD

**Issue by Hedwig7s** [citra-emu/citra#5916]
It is literally one of the most requested features. I have seen requests from 2017 but you still have not added it. It is 2022 surely you have some devs who know how to work with it. How about asking the yuzu team? Since yuzu and Citra are owned by the same people surely the other team can help right? yuzu has support why shouldn't Citra? There are also wrappers for OpenGL on top of Vulkan like Zink.

Please add it. It has been requested alot of times and you probably have devs who can do it.

PS: _Don't forget the poor AMD users running Windows who struggle to run Citra properly cause of this_
PPS: _No bulls**t about the yuzu and Citra devs being different please_

**Comment by SleepingSnakezzz** [comment]
You realise that this project is essentially a hobby, right?
Devs are not required to do anything, regardless of how requested it is. That's even outside of said devs having the knowledge and time to work on a Vulkan backend.

As for your claims about Citra and Yuzu's dev teams. Like I said, working on projects like these are hobbies, not jobs. Even if the Yuzu dev team has devs that are familiar with Vulkan, that doesn't mean that they are willing to spent their time on implementing it in Citra. So there's no "bullsh**t" there. Devs decide what they want to work on. The Citra dev team and the Yuzu dev team are filled with devs that destinctly contribute to one project as opposed to the other. Hence why we say that the dev teams are different --> its because they are.
Just because a dev from one project contributes to another once in a while doesn't mean that they're on the same core team (which is a weird thing to say anyways as they don't owe "loyalty" to one project or another, its just their choice of what to contribute to).

If (a) dev(s) decides to spearhead development for a Vulkan backend in Citra, great!
Until that happens though, you're just gonna have to put up with it. This isn't something we can control.

A dev from our end _has_ looked into Zink before. Which apparently looked promising but isn't quite there yet.

**Comment by Hedwig7s** [comment]
> You realise that this project is essentially a hobby, right? Devs are not required to do anything, regardless of how requested it is. That's even outside of said devs having the knowledge and time to work on a Vulkan backend.
> 
> As for your claims about Citra and Yuzu's dev teams. Like I said, working on projects like these are hobbies, not jobs. Even if the Yuzu dev team has devs that are familiar with Vulkan, that doesn't mean that they are willing to spent their time on implementing it in Citra. So there's no "bullsh**t" there. Devs decide what they want to work on. The Citra dev team and the Yuzu dev team are filled with devs that destinctly contribute to one project as opposed to the other. Hence why we say that the dev teams are different --> its because they are. Just because a dev from one project contributes to another once in a while doesn't mean that they're on the same core team (which is a weird thing to say anyways as they don't owe "loyalty" to one project or another, its just their choice of what to contribute to).
> 
> If (a) dev(s) decides to spearhead development for a Vulkan backend in Citra, great! Until that happens though, you're just gonna have to put up with it. This isn't something we can control.
> 
> A dev from our end _has_ looked into Zink before. Which apparently looked promising but isn't quite there yet.

The issue is, unlike the Switch, there are no real alternatives to Citra. All alternatives ended development and none have Vulkan support as far as I know. On the Switch side (using as an example), there is Ryujinx and yuzu. Both Ryujinx and yuzu are in development and both have (at least experimental) Vulkan support. If one didn't add support because the devs didn't know how, the other project might be able to. But with the 3DS, there are no alternatives so if Citra doesn't add it no one else will in their own project. Having only one emulator for the 3DS means that that one emulator should try to add the most requested features and not hope another project will instead. If Citra doesn't add Vulkan it just leaves AMD users on Windows basically screwed since there are no alternatives.
Do you see the problem? You can't just change emulators because you don't like something with the other/the other doesn't work well with your hardware. Citra is the only 3DS emulator in development. It should be the one which tries to support more hardware.

**Comment by Hedwig7s** [comment]
I am sure, since both projects are owned by the same people, the other team would happily help add Vulkan to Citra if they aren't working on something big.

**Comment by Hedwig7s** [comment]
Here is 2 examples of changing between Ryujinx and yuzu (which just isn't possible with Citra): If you are an AMD user and want good performance but find that Ryujinx doesn't have support/the Vulkan version is too glitchy, you can change to yuzu.
If you wanted to try LAN/LDN but find yuzu doesn't support it, you can change to Ryujinx.

**Comment by Hedwig7s** [comment]
With Citra, you can't just change emulators if you do not like something about it/it is missing a feature that you really want because of the sheer lack of alternatives.

**Comment by SleepingSnakezzz** [comment]
You seem to have glossed over a lot what I said earlier: This is a hobby, not a job or an obligation. The dev teams between yuzu and Citra are also not the same. You can keep believing that they are, the facts won't change.
Even if they were, Vulkan isn't something you can just lightheartedly implement in a couple weeks work. Implying otherwise by saying devs would "happily" implement it is very telling on how little you know about implementing something like a Vulkan backend.

gidoly reposted some links in the Citra discord that a yuzu dev posted at some point to illustrate the difference between Vulkan and OpenGL, so maybe this will give you some idea as to why your attitude on this is perceived as rather ignorant:

Hello triangle for OpenGL
https://github.com/Fr3nchK1ss/OpenGL-4.6-Hello-Triangle/blob/master/hello_colorful_triangle.cpp
Hello triangle for Vulkan
https://gist.github.com/Overv/7ac07356037592a121225172d7d78f2d
Have a look at the code for each and see if you can spot the main glaring difference.

You're also acting as if our devs, who dedicate their free time to the project, have a responsibility to implement a feature in Citra that is _very_ difficult and extremely time consuming to implement because there is no other alternate emulator for the 3DS. If I have to explain how that is a highly entitled and nonsensical point of view, then there's really no point in continuing to try and explain this to you.

**Comment by Gamemulatorer** [comment]
Vulkan is coming very soon...
https://github.com/citra-emu/citra/pull/6130
