### ISSUE TITLE
New feature request: changing the renderer

### ISSUE THREAD

**Issue by Maks7594** [citra-emu/citra#5922]
This could be helpful for people like me, because OpenGL is a way lot slower than e.x. Direct3D 11. I did this on another emulator and it was a lot faster than I expected.

**Comment by poudink** [comment]
I imagine you're an AMD user? Their OpenGL drivers on Windows are unfortunale extremely bad. Making a new renderer is a lot of work tho and Direct3D in particular probably won't happen because it's Windows-only. I've heard Vulkan might happen eventually which would be a great improvement as well, though that was a while ago and Citra development seems to have slowed considerably since.

In the meantime, switching your operating system to Linux would definitely help, if you can do that. AMD OpenGL drivers on Linux are much faster.

**Comment by SachinVin** [comment]
Closing, since there are no plans at the moment.
