### ISSUE TITLE
Failed to load ROM: No ROM specified

### ISSUE THREAD

**Issue by Qu3ntin** [citra-emu/citra#608]
![screenshot 2](https://cloud.githubusercontent.com/assets/11024491/6370432/76c4f090-bcbe-11e4-81db-04e3fb4bf0c3.png)

**Comment by Kloen** [comment]
1. Don't spam the issue tracker.
2. You already got a properly answer here #603 from @yuriks 
3. If you don't know how to read, learn to read, you should use "citra-qt" as StartUp Project instead of "citra". If people use their time to answer you, atleast you should use your time to read it and try to understand what you should do, instead of spam the same question all the time.

Sorry citra team if I take the law by my hand, but I suggest you that if you can, you should block the issue tracker for non team members, or something, because more spam like this will come soon.

**Comment by Qu3ntin** [comment]
i didnt know i new to this

**Comment by Qu3ntin** [comment]
and for some reason qt has errors

**Comment by Kloen** [comment]
Check if you have the last source from master, if not update it, if you still getting the errors, you can try to solve them, or post them here, on this issue and maybe someone could help you, but don't rush, wait for an answer, and also don't recreate more issues, cause you are spaming all the emails of all the watchers of this repo with notifications.

**Comment by Qu3ntin** [comment]
ok gotcha

**Comment by neobrain** [comment]
@Kloen Thanks for taking care of this. Unfortunately, our options with the GH issue tracker are somewhat limited, and we currently don't have the time to investigate into alternative solutions.

Anyway, closed.
