### ISSUE TITLE
Add an experimental option to change resolution to 0.75, like Yuzu

### ISSUE THREAD

**Issue by kevincrans** [citra-emu/citra#6096]
It would be interesting to test how games would work running in a 320/256×192 environment, similar to the DS.
I know that features are only added when valued by developers, however this is valued by the developers in it's sister-emulator Yuzu.

**Comment by GPUCode** [comment]
I don't personally think this option is of much use to Citra. The Nintendo Switch has a 720p native resolution and emulating it is very resource intensive, so decreasing the resolution is a natural way to make it run on lower end systems. This doesn't apply here imo because the base resolution is already very low and the hardware requirements for Citra are not very high for desktop, so having this option just doesn't make sense.

**Comment by Daisouji** [comment]
Native res is 240/360p, no point of doing .75

**Comment by kevincrans** [comment]
I agree, that if there's a bottleneck, it's not the resolution, but same for Yuzu. It does have 2 screens though, so in 3D it's technically 480p minus 30% (bottom screen).

**Comment by SleepingSnakezzz** [comment]
Spending money on 3D hardware that can actually display it properly would be better spent on upgrading your hardware to something that isn't 12+ years old. Since anything even remotely modern doesn't struggle with even 2x resolution. Let alone native resolution.
