### ISSUE TITLE
Cannot adjust game speed when using Vulkan with vsync turned on

### ISSUE THREAD

**Issue by windwakr** [citra-emu/citra#6917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2596

### Description of Issue

You cannot adjust game speed while using the Vulkan backend if you have vsync turned on. The game will continue to run at 100% speed.

### Expected Behavior

I would expect the game speed to change. When using OpenGL it will change when you have vsync enabled.

### Reproduction Steps

Turn on Vulkan and vsync, start a game, then hit Ctrl+Z.

### Log File

None

### System Configuration

CPU:
GPU/Driver: GTX 1650S
RAM:
OS: W10

**Comment by SleepingSnakezzz** [comment]
This is normal. In fact, it should be the same on OpenGL, but Vulkan is just stricter on the V-Sync requirements (@GPUCode, correct me if I'm wrong)

**Comment by GPUCode** [comment]
Vulkan and opengl mailboxes work a little differently. Opengl does not wait for frames and will always use the newest one, which means it may "jump" frames, while vulkan is more typically synchronized. I would recommend disabling vsync when using vulkan as it uses mailbox present mode that prevents tearing. async presentation will also help prevent tearing without needing to enable vsync

**Comment by windwakr** [comment]
> This is normal.

Could you show me another emulator where the fast forward button ceases to function when vsync is enabled?

**Comment by GPUCode** [comment]
Then, please, I would like some specific examples of emulators that have unlimited speed with vsync to reference

**Comment by GPUCode** [comment]
Just to clear some confusion opengl vsync != vulkan vsync. Vulkan by default has no tearing because it uses mailbox presentation mode. This means you dont have to enable vsync in vulkan to avoid tearing, unless your hardware doesn't support that mode. Though I do agree that this should be better exposed to the user. The checkbox will probably be converted to a dropdown with all the presentation modes available

**Comment by GPUCode** [comment]
I have reworked the vsync setting in the next canary. The current vsync off has been made vsync on while vsync off now allows for tearing. Feel free to reopen if that doesn't solve your problem

**Comment by oilbugxx** [comment]
> I have reworked the vsync setting in the next canary. The current vsync off has been made vsync on while vsync off now allows for tearing. Feel free to reopen if that doesn't solve your problem

i think what many emu do is by deactivate vsync in conjunction to adjusting the emulation speed when the toggle key being input. so you dont have to disable vsycn to speed up. btw i am just guessing thats the case here, because whenever speed up is on it always have the screen tearing while the normal speed dont. but then i know nothing about technical stuff so, is that possible that being the case here?
