### ISSUE TITLE
Direct3d 11 support

### ISSUE THREAD

**Issue by jm1358343** [citra-emu/citra#7004]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### What feature are you suggesting?

Direct3d 11 support 

### Why would this feature be useful?

Help low end pcs run Citra better

**Comment by vitor-k** [comment]
There is no inherent performance benefit to using Direct3d 11, and there are numerous downsides to it.
To begin with, it is exclusive to Windows, while Citra targets multiple Operation Systems and platforms.
Second, there is no reason to choose Direct3d11 instead of something more modern like Direct3d 12.
Third, the implementation of a graphics backend takes months to years of work, as can be seen by the Vulkan development, and requires a developer with knowledge of the graphics API being implemented, plus willingness to maintain it.
