### ISSUE TITLE
Japanese characters not working in file names

### ISSUE THREAD

**Issue by JanetMerai** [citra-emu/citra#730]
Just as it says, when I boot up a game in Citra that has Japanese characters in its file name, it won't load at all.

Renaming the game with English makes it work again.

**Comment by kemenaran** [comment]
Accentuated characters in path (like `/usr/john/Émulation/demo.3dsx`) don't work either.

**Comment by mailwl** [comment]
russian too, because of latin encoding

**Comment by JanetMerai** [comment]
I've tested Japanese characters in some of my dumps and it still doesn't work.
When I open Citra, I see boxes instead of proper Japanese characters.

Any idea or estimation when this will be implemented?

**Comment by yuriks** [comment]
I think I'm the only one interested in this, but I haven't had much time to work on Citra in a while, so this has been getting very low priority.

**Comment by LittleWhite-tb** [comment]
This bug does not appear in Linux. I will take some time to set my environment on Windows and see which code does cause this problem.

**Comment by LittleWhite-tb** [comment]
After investigation, I don't think there is much to do.
With just need to compile using UNICODE to handle this case. All the code handling UNICODE and wstring is already implemented and it should work on the go.
*BUT*, by enabling UNICODE, it will not compile perfectly, there is small defect in string_util.cpp/.h . Moreover, in Qt code, there will be no need to convert in Latin/Local8bit anywmore. Just pass the QString as std::string (toStdString()) and the internal code will handle it perfectly.

I will bring the minor changes soon and see how to make CMake enabling UNICODE.

**Comment by yuriks** [comment]
We use std::string to store and process filenames, I don't think just enabling UNICODE will work. The proper way to do this would be to either use QString throughout the codebase (bad because we don't want a hard depedency), transcode qString into std::wstring (bad because it doesn't support all unicode characters anyway and UTF-16 is terrible) or transcode QString into a UTF-8 internally and and then go through a compat layer when opening files. I think the later is preferable, see http://www.utf8everywhere.org/ for more details and rationale for that.

**Comment by yuriks** [comment]
(That said, we should totally be compiling with UNICODE, it's just that iirc we're doing that already, the issues come from C++ standard library io stuff.)

**Comment by neobrain** [comment]
Adding on a detail of what @yuriks said:

> The proper way to do this would be to either use QString throughout the codebase (bad because we don't want a hard depedency),

Loading files through QString would of course be the easiest and hence preferred way, but yuriks raises a valid point. However, the only reason it's an issue is that file loading is currently done in core code. If instead the frontend were to load the input program file and pass it (or rather, the information stored in that file) to the emulator core, this would be a perfectly acceptable solution.

In fact, I would argue that filesystem access (and hence in particular application loading) should possibly be a responsibility of the frontend (especially when considering that console ports would possibly require custom IO functions anyway).

**Comment by LittleWhite-tb** [comment]
@yuriks I created a simple test to better understand what the heck is going with Windows. In file_utils.cpp we use a function _tfopen() which accepts a std::string to open a file. These functions are like an interface (or wrapper). When MSBC is enabled, the function acts like fopen() (accepting std::string). Otherwise (when UNICODE), the function is like wopen() (accepting std::wstring).
-> https://msdn.microsoft.com/en-us/library/yeby3zcb.aspx
My test is using a path containing japanese characters in filename, and specific European character 'É' in folder name.
I did use a QFileChooser to choose the specific file (and to be as close as possible to the citra case). The filename is converted from QString to whatever it is possible (toLatin1/toLocal8bit/toUTF8/toStdString).
When MSBC is enabled, _tfopen **can't** open the file at all. No conversion would work.
When UNICODE is enabled, _tfopen can open the file when converted from QString using toStdWString().

I wanted to transpose that in Citra. My solution was to enable UNICODE. This is because the developers of file_utils.cpp have already thought about these convertions and everything was in place. The incoming std::string in converted to std::wstring (only when UNICODE is enabled) and the file could be loaded.

From my point of view:
* There is no need to bring QString everywhere (and as you said, it's a bad idea anyway). std:string can do the job.
* There is no need to change the actual implementation since:
* Dolphin guys did the job very well from and this bug can be closed using UNICODE
* I naively think that Dolphin users should have met this bug and it would have been fixed it a long time ago

My plan from there:
* Bring a commit to enable UNICODE and fix the compilation error related to that
* Bring an additional commit in order to implement neobrain's idea of handling the loading in frontend code

---
Side note: 
Since file_utils.cpp (and others) comes from Dolphin project, why are not we picking their commit for these files in case they would fix something ?

**Comment by yuriks** [comment]
@neobrain For a simpler system I'd totally agree with putting filesystem code in the frontend. However, Citra has several more complex requirements (RomFS streaming, several different filesystem types, etc.) that moving file code to the front-end would result in a very large amount of code duplication. At that point I think it would be better to just properly consistently use cross platform functions for opening files assuming wtf-8 encoded filenames.

@LittleWhite-tb Any MSBC support currently present in common should IMO be completely removed as deprecated cruft. There is 0 good reasons to do MSBC builds and not use W APIs exclusively. Conversion from the Qt strings to internal strings should always be done by encoding them as UTF-8. All systems treat filenames as utf-8 encoded raw string blobs. Windows is the only outlier here, and using std::wstring IMO only invites additional subtle (e.g. non-BMP related) bugs in the future.

I stand by my opinion that this should be handled by making all Windows APIs wide, and explicitly transcoding to/from UTF-8 and UCS-16. (**Never** to the local codepage.)

**Comment by turbedi** [comment]
Is this fixed now that #1620 is merged?

**Comment by polaris-** [comment]
@turbedi I believe that PR should've probably fixed this issue. I just tested it with Korean and Japanese and it worked for me. They did what yuriks was suggesting by using the wide Windows APIs and such.

**Comment by yuriks** [comment]
I believe it was. Yay!
