### ISSUE TITLE
QT: Remove gray border from rendering canvas

### ISSUE THREAD

**Issue by filfat** [citra-emu/citra#815]
Currently there's a ~10px gray border between the rendered 3DS screen and window border, this is not only a waste of screen space but also doesn't fit the style of the modern operating systems.
![](http://i.imgur.com/X0hIdQX.png)
(Left: Now. Right: How it should be.)

**Comment by archshift** [comment]
The issue is not Citra, but how Windows 10 chooses to render windows now. See:

![example](http://blogs-images.forbes.com/antonyleather/files/2015/04/windows-10.jpg)

**Comment by yuriks** [comment]
Nope, there's definitely a border:

![Citra](http://i.imgur.com/Q02pLiO.png)

I'm not really bothered by it, but if anyone wants to remove it be my guest.

**Comment by archshift** [comment]
Oh, that's because the Qt render area doesn't fill the entirety of the space unoccupied by widgets. When there aren't any widgets, the gap remains.

I think it'd be pretty strange if there was no gap while there were widgets on the window, so if anyone wants to "fix" this it'd be best to make a special case for when no widgets are being shown.

**Comment by filfat** [comment]
@archshift on the testing i've done so far it looks quite good without any gap at all even with widgets, almost "flat" (which is the style everybody is going towards). I do realize style isn't important but this would be a real quick fix and make the application feel way more at home in both Windows and OSX. :)

**Comment by SeannyM** [comment]
1 line of code is all it takes to remove the border, and widgets are still have empty space between one another because of how they're set up. If this looks good to everyone, I could easily create a PR.
![nowidgets](https://cloud.githubusercontent.com/assets/3057954/7872970/b462e462-056a-11e5-8e86-964c6f1f9aef.png)
![widgets](https://cloud.githubusercontent.com/assets/3057954/7872971/b66d7b64-056a-11e5-91f3-ac5c8ca4e5ac.png)
