### ISSUE TITLE
y2r:u - Not all conversion output formats have been implemented

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#833]
After implementing y2r (b/w videos playback) Persona Q get's a crash before video should be played.

![persona q crash](https://cloud.githubusercontent.com/assets/11453507/7897762/c2b4d384-06e8-11e5-90b2-234fe96b50f7.PNG)

LOG - http://pastie.org/10215149

**Comment by archshift** [comment]
What's interesting to note is that the game isn't calling `SetOutputFormat` at all, and is calling an unknown command `0x2901C0`. This command probably takes the place of SetSendingY, but it's possible that it also specifies the input and output formats itself. Otherwise, the game relies on the default input and output formats (and other parameters) to do the conversion.

**Comment by archshift** [comment]
Documented `0x2901C0` after REing the camera module. Results [here](http://3dbrew.org/w/index.php?title=Camera_Services&curid=1717&diff=12719&oldid=12718).

**Comment by JohnGodgames** [comment]
Crash fixed by https://github.com/yuriks/citra/tree/y2r-color
