### ISSUE TITLE
Yoshi's New Island uses VS default attribute index 16, which is reported invalid

### ISSUE THREAD

**Issue by archshift** [citra-emu/citra#945]
![Related screenshot](https://i.imgur.com/gqhtDjl.png)

[Related CiTrace](https://copy.com/9PvNfVfH2Ll88FAI)

To reproduce:
- Load Yoshi's New Island / CiTrace in Citra
- Wait a few seconds
- You will see an image like the screenshot above, and the console will flood with "Invalid VS default attribute index 16"

**Comment by yuriks** [comment]
Etrian Odyssey IV is also affected by this.

**Comment by mailwl** [comment]
what if limit index to 0xF? something like:
`setup.index &= 0xF;`

**Comment by neobrain** [comment]
@mailwl Pretty sure it's not supposed to work like that. Wouldn't really make sense for games to exploit such a thing.

**Comment by yuriks** [comment]
I discovered that this is functionality similar to OpenGL's immediate-mode, where vertices can be fed directly from the command stream instead of from vertex arrays.

I'm currently trying to reproduce it in homebrew, based off EO4 command lists. I got it working once but after rebooting the 3DS it stopped working again, so it seems to require specific register settings to work.

Even after it's RE'd though, it'll require some significant restructuring of our vertex loading code to implement.

**Comment by yuriks** [comment]
I got my homebrew working and added a hacky (not inaccurate per-se, but lot's of code copy&pasting) implementation, try it out here: https://github.com/yuriks/citra/tree/immediate-mode

Unfortunately EO4 has other issues that prevent it from properly rendering, but it's drawing, so this is at least partially working.

**Comment by archshift** [comment]
Unfortunately, using that branch made no difference to the graphical errors shown above.

**Comment by JayFoxRox** [comment]
Is this still a thing?

**Comment by yuriks** [comment]
No, this was #1394
